### ISSUE TITLE
Unable do modify loot tables with datapacks (overrid not working)

### ISSUE THREAD

**Issue by Gbergz** [terrarium-earth/Ad-Astra#10]
Title^

Unable to modify the datapacks for loot table chests such as the meteors.
Trying to change the steel ingots to my own steel type but it doesn't change them.

Minecraft: 1.18.2
Fabric: 0.14.9
Fabric API: 0.58.0
Cloth Config: 6.2.62
Ad Astra: 1.0.0 | https://www.curseforge.com/minecraft/mc-mods/ad-astra/files/3932056

**-** Gbergz

**Comment by Aulluna** [comment]
Can u also upload the datapack ? just to make sure you're not doing it wrong

**Comment by Gbergz** [comment]
Sure, I tried with KubeJS initially, but it didn't work there so I switched to a vanilla datapack zip, didn't work there either.
[loot_table.zip](https://github.com/AlexNijjar/Ad-Astra-Fabric/files/9438367/loot_table.zip)

**Comment by AlexNijjar** [comment]
For some reason, the meteor loot table is in the /minecraft datapack directory and not the /ad_astra directory. So to override it, put the file in "/data/minecraft/loot_tables/loot.json" No idea why it's like that. It will be changed when the meteor structures are redone.
