### ISSUE TITLE
[Bug]: tier 1 rocket will not launch

### ISSUE THREAD

**Issue by casezzz** [terrarium-earth/Ad-Astra#101]
### Bug Description

I read that you can launch the rocket by pressing the space bar but nothing happens. i have checked through the key bindings and cant find anything related to the rocket at all. is there a way to lauch it or is this a bug? im not the only one with this problem. Im playing dreamcraft on curseforge and the mod that is troublesome is ad astra.

### Expected Behavior

i expected the rocket to launch. but nothing happened.

### Version

1.11.8

### Mod Loader Version

1.19.2 1.18.1

### Mod Loader

Forge

### Logs or additional context

https://www.curseforge.com/minecraft/mc-mods/ad-astra

**Comment by AlexNijjar** [comment]
It's fixed in the latest version: 1.11.9
