### ISSUE TITLE
[Bug]: Crash after update botarium

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#102]
### Bug Description

Crash game when starting minecraft after botarium update to 1.7.15

### How to Reproduce?

1. Install botarium 1.7.15 with Ad Astra! 1.11.9
2. Launch Minecraft.

### Version

1.11.9

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/JLbu94Ba

**Comment by ixDarkLorD** [comment]
It's happening to me also
I got the same crash today!

**Comment by AlexNijjar** [comment]
Try on the latest botarium version
