### ISSUE TITLE
[Bug]: crash

### ISSUE THREAD

**Issue by Aces-and-Jacks** [terrarium-earth/Ad-Astra#104]
### Bug Description

crashed when i shift clicked a rocket in the landing pod thing

### How to Reproduce?

open landing pod thing
shift click rocket

### Expected Behavior

no crash

### Version

1.11.9

### Mod Loader Version

0.17.8 for 1.19.3

### Mod Loader

Quilt

### Logs or additional context

https://mclo.gs/sx6tpx4

**Comment by AlexNijjar** [comment]
It's an iris issue #35
You'll have to wait for them to fix it or remove it for now

**Comment by Aces-and-Jacks** [comment]
should I link this issue in iris then or is there already an issue in iris GitHub?

**Comment by Aces-and-Jacks** [comment]
oh

**Comment by Aces-and-Jacks** [comment]
never mind sorry missed your link

**Comment by Aces-and-Jacks** [comment]
wait in the comments of that link they said it was fixed in 1.4.1 however iris is at 1.4.6. shouldn't it be made open again or another issue be linked?

**Comment by AlexNijjar** [comment]
I'm not sure. Maybe they delayed it or the fix didn't work. This exact issue has been happening for many months now across multiple mods and iris seems to be the root cause; they're very aware of it.

**Comment by Aces-and-Jacks** [comment]
So...should i make a new issue?

**Comment by Aces-and-Jacks** [comment]
on iris

**Comment by Aces-and-Jacks** [comment]
I don't even know what the issue on iris is called or if it's been closed already

**Comment by Aces-and-Jacks** [comment]
I could probably just make an issue and they'll mark it as duplicate and link the main issue

**Comment by Aces-and-Jacks** [comment]
also mail is slow. I just got the notification for your response now which would be 36 minutes ago. also sorry for spamming

**Comment by AlexNijjar** [comment]
You can make another issue if you want, letting them know that this is still happening.
