### ISSUE TITLE
[Bug]: Crash after the launch of a rocket

### ISSUE THREAD

**Issue by Lolothepro** [terrarium-earth/Ad-Astra#106]
### Bug Description

Crash after the launch of a rocket
https://streamable.com/poswdn

### Version

1.11.9

### Mod Loader Version

1.19.2 - 0.14.12

### Mod Loader

Fabric, Quilt

### Logs or additional context

[crash-2022-12-23_14.10.03-server.txt](https://github.com/terrarium-earth/Ad-Astra/files/10295265/crash-2022-12-23_14.10.03-server.txt)
[crash-2022-12-23_14.08.10-server.txt](https://github.com/terrarium-earth/Ad-Astra/files/10295266/crash-2022-12-23_14.08.10-server.txt)

https://pastebin.com/TMFhzbVz

**Comment by AlexNijjar** [comment]
This’ll be fixed in the next update. A temporary fix is to install architectury api
