### ISSUE TITLE
[Bug]: Ad Astra 1.19.2 Orbital Catalog is blank

### ISSUE THREAD

**Issue by AtreidesNutz** [terrarium-earth/Ad-Astra#107]
### Bug Description

After finishing my first rocket and launching into space, the orbital catalog doesn't appear to be working. There's supposed to be buttons for me to click on to choose where to go and land. Instead it's just an empty box. And now I'm stuck in orbit without any ability to open chat or the esc menu or anything. No matter what I try I am unable to do anything to fix this.

### Expected Behavior

I expected to be able to choose where to land while in orbit.

### Version

1.11.8

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
can you send the latest.log in a world where you experienced the issue?

**Comment by AlexNijjar** [comment]
Will be fixed in the next version
