### ISSUE TITLE
[Bug]: put fluid to filled up mek pipe link with a filled up mek tank will cause crash

### ISSUE THREAD

**Issue by Uptobillion** [terrarium-earth/Ad-Astra#109]
### Bug Description

put fluid to filled up mek pipe link with a filled up mek tank will cause crash

### How to Reproduce?

put fluid to filled up mek pipe link with a filled up mek tank will cause crash

### Version

1.11.9

### Mod Loader Version

1.19.2-43.2.1

### Logs or additional context

---- Minecraft Crash Report ---- // Uh... Did I do that? Time: 2022-12-25 01:22:54 Description: Ticking block entity java.lang.IllegalStateException: Can't modify the empty stack. 	at net.minecraftforge.fluids.FluidStack.setAmount(FluidStack.java:175) ~[forge-1.19.2-43.2.1-universal.jar%23225!/:?] {re:classloading} 	at earth.terrarium.botarium.forge.fluid.ForgeFluidHolder.setAmount(ForgeFluidHolder.java:57) ~[botarium-forge-1.19.2-1.8.0.jar%23189!/:?] {re:classloading} 	at earth.terrarium.botarium.api.fluid.SimpleUpdatingFluidContainer.extractFluid(SimpleUpdatingFluidContainer.java:68) ~[botarium-forge-1.19.2-1.8.0.jar%23189!/:?] {re:classloading} 	at earth.terrarium.botarium.forge.fluid.ForgeFluidContainer.drain(ForgeFluidContainer.java:46) ~[botarium-forge-1.19.2-1.8.0.jar%23189!/:?] {re:classloading} 	at mekanism.common.content.network.transmitter.MechanicalPipe.pullFromAcceptors(MechanicalPipe.java:83) ~[Mekanism-1.19.2-10.3.5.473.jar%23203!/:10.3.5] {re:classloading} 	at mekanism.common.tile.transmitter.TileEntityMechanicalPipe.onUpdateServer(TileEntityMechanicalPipe.java:59) ~[Mekanism-1.19.2-10.3.5.473.jar%23203!/:10.3.5] {re:classloading} 	at mekanism.common.tile.transmitter.TileEntityTransmitter.tickServer(TileEntityTransmitter.java:89) ~[Mekanism-1.19.2-10.3.5.473.jar%23203!/:10.3.5] {re:classloading} 	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:classloading} 	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:classloading} 	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {} A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Render thread Stacktrace: 	at net.minecraftforge.fluids.FluidStack.setAmount(FluidStack.java:175) ~[forge-1.19.2-43.2.1-universal.jar%23225!/:?] {re:classloading} 	at earth.terrarium.botarium.forge.fluid.ForgeFluidHolder.setAmount(ForgeFluidHolder.java:57) ~[botarium-forge-1.19.2-1.8.0.jar%23189!/:?] {re:classloading} 	at earth.terrarium.botarium.api.fluid.SimpleUpdatingFluidContainer.extractFluid(SimpleUpdatingFluidContainer.java:68) ~[botarium-forge-1.19.2-1.8.0.jar%23189!/:?] {re:classloading} 	at earth.terrarium.botarium.forge.fluid.ForgeFluidContainer.drain(ForgeFluidContainer.java:46) ~[botarium-forge-1.19.2-1.8.0.jar%23189!/:?] {re:classloading} 	at mekanism.common.content.network.transmitter.MechanicalPipe.pullFromAcceptors(MechanicalPipe.java:83) ~[Mekanism-1.19.2-10.3.5.473.jar%23203!/:10.3.5] {re:classloading} 	at mekanism.common.tile.transmitter.TileEntityMechanicalPipe.onUpdateServer(TileEntityMechanicalPipe.java:59) ~[Mekanism-1.19.2-10.3.5.473.jar%23203!/:10.3.5] {re:classloading} 	at mekanism.common.tile.transmitter.TileEntityTransmitter.tickServer(TileEntityTransmitter.java:89) ~[Mekanism-1.19.2-10.3.5.473.jar%23203!/:10.3.5] {re:classloading} 	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:classloading} 	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:classloading} 	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:A} -- Block entity being ticked -- Details: 	Name: mekanism:basic_mechanical_pipe // mekanism.common.tile.transmitter.TileEntityMechanicalPipe 	Block: Block{mekanism:basic_mechanical_pipe}[fluid_logged=empty] 	Block location: World: (45,104,-11), Section: (at 13,8,5 in 2,6,-1; chunk contains blocks 32,-64,-16 to 47,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1) 	Block: Block{mekanism:basic_mechanical_pipe}[fluid_logged=empty] 	Block location: World: (45,104,-11), Section: (at 13,8,5 in 2,6,-1; chunk contains blocks 32,-64,-16 to 47,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1) Stacktrace: 	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:classloading} 	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:classloading} 	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B} 	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:331) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ad_astra-common.mixins.json:ServerLevelMixin,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {} -- Affected level -- Details: 	All players: 0 total; [] 	Chunk stats: 841 	Level dimension: ad_astra:moon 	Derived: true 	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) 	Level time: 10967085 game time, 12775830 day time 	Level name: 192 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true 	Level weather: Rain time: 40012 (now: false), thunder time: 76731 (now: false) 	Known server brands: forge 	Level was modded: true 	Level storage version: 0x04ABD - Anvil Stacktrace: 	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:classloading,pl:runtimedistcleaner:A} 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23220!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A} 	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by AlexNijjar** [comment]
Fixed in latest botarium version
