### ISSUE TITLE
[Bug]: Unexpected flag broken and don't drop as item

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#111]
### Bug Description

1. Flag was broken after place another flag at bottom
2. And it's doesn't dropped as item.

![Flag](https://user-images.githubusercontent.com/44163945/209458638-c0bfb681-651f-4e8a-8a09-ffd194dcaf55.gif)

### How to Reproduce?

1. Place Flag.
2. Break bottom block from flag.
3. Place another flag at broken places.

### Expected Behavior

1. I was expect to it will can't place flag in broken places.
2. even If can place, first flag have to drop as items.

### Version

1.11.9

### Mod Loader Version

0.69.0

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
Ah, I fixed this in my other mod, handcrafted, but not this one. The expected behaviour is that the flag should not be playable if there's a block above it, as it can break any block, even bedrock
