### ISSUE TITLE
[Bug]: The hand rendering is broken with Iris and a Netherite spacesuit.

### ISSUE THREAD

**Issue by Lolothepro** [terrarium-earth/Ad-Astra#112]
### Bug Description

https://user-images.githubusercontent.com/68275908/209724262-66eaa09a-b041-43a0-8afa-84cc7fca4c73.mp4

https://user-images.githubusercontent.com/68275908/209724268-41e2ae11-4a7b-4ff8-8752-b1127ad4b7ff.mp4

### How to Reproduce?

1. Install Iris, Sodium, and Ad Astra!
2. Go to the edge of a block
3. Activate a shaderspack

### Version

1.11.9

### Mod Loader Version

1.19.2 - 0.14.12

### Mod Loader

Quilt

**Comment by xllifi** [comment]
For me the hand is also half transparent and glowing. (rethinking voxels, BSL, AstraLex)
![Hand bloom](https://github.com/terrarium-earth/Ad-Astra/assets/70767436/b06763fc-c173-4979-a802-cf3fbca45a29)

Fabric 0.14.19
Minecraft 1.19.2
Iris 1.6.2
Ad Astra 1.12.6

**Comment by AlexNijjar** [comment]
there is now a config option to disable custom hand rendering
