### ISSUE TITLE
[Bug]: Oil, fuel, and cryo fuel are wrongly included in the minecraft:water tag

### ISSUE THREAD

**Issue by JustinHuPrime** [terrarium-earth/Ad-Astra#116]
### Bug Description

Oil, fuel, and cryo fuel are included in the minecraft:water tag, but these really don't seem like they should be considered similar to water.

### Expected Behavior

Oil, fuel, and cryo fuel should not be included in the minecraft:water tag

### Version

Minecraft 1.19.2/Mod 1.11.9

### Mod Loader Version

Minecraft 1.19.2/Forge 43.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
In order to give the fluid collision properties, it has to be in the water tag. If it's not, water just acts like air.
