### ISSUE TITLE
[Bug]: Crash upon 

### ISSUE THREAD

**Issue by billyp673** [terrarium-earth/Ad-Astra#117]
### Bug Description

Upon launching a tier one rocket and reaching the top, where the gui should open, the game crashes with [this](https://pastebin.com/gZ3Pkmg3) report.

### How to Reproduce?

launch a tier 1 rocket
ride it up
game crashes

### Expected Behavior

space gui opens

### Version

1.11.9

### Mod Loader Version

1.19.2-0.14.11

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/gZ3Pkmg3

**Comment by AlexNijjar** [comment]
It's in issue with architectury that will be fixed in the next update. You can fix it for now by downloading architectury API

**Comment by billyp673** [comment]
cheers mate
