### ISSUE TITLE
[Bug]: Crash at worldgen

### ISSUE THREAD

**Issue by agentwolf88** [terrarium-earth/Ad-Astra#118]
### Bug Description

The game crashs in my modpack with Ad Astra.

[crash-2023-01-01_12.32.32-server.txt](https://github.com/terrarium-earth/Ad-Astra/files/10328687/crash-2023-01-01_12.32.32-server.txt)

### Version

ad_astra-forge-1.19.2-1.11.9.jar

### Mod Loader Version

Forge 43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
try uninstalling immersive portals

**Comment by AlexNijjar** [comment]
if that doesn't fix it lmk
