### ISSUE TITLE
[Feature Request]: 1.18 Forge Support

### ISSUE THREAD

**Issue by Yang-qwq** [terrarium-earth/Ad-Astra#119]
### Is your feature request related to a problem?

**I am not a native English speaker, if you can't understand what I am saying, I'm sorry for that**
I would like to ask if this mod will be updated with other version (like 1.18) support?
If you think this is spam question, please close this issue.

---

我想问一下这个模组是否会更新其他版本（如 1.18）的支持？
如果您认为这是个冒犯的问题，请关闭此issue。

### Mod Version

none

### Mod Loader Version

1.18.2 - 40.1.92

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
The mod is highly complex with a ton of stuff to back port. In addition, Ad Astra has 3 dependencies, only 1 which is on 1.18, so they'd have to back port as well. Because of this we will not be back porting.
