### ISSUE TITLE
[Feature Request]:  Ability to add dimensions to destination map and oxygen config for dimension

### ISSUE THREAD

**Issue by Subthy** [terrarium-earth/Ad-Astra#122]
### Is your feature request related to a problem?

This feature is no related to any problems. I want to have an option to add dimensions to destination map and what ship is needed to travel to the dimension, as that would allow modpack makers to have a twist how to get to other dimension, without using the mods portal. Plus it would be nice to add like a "whitelist" option to oxygen, so you can remove oxygen from other dimensions. Like you would need to have oxygen tanks for Twilight forest.

### Mod Version

1.11.9

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
For adding custom planets, it can be done with a datapack and resource pack. There’s no wiki at the moment but you can reference the built-in ad astra data and resource pack and just copy your own. It even allows you to make your own galaxies and solar systems + you can choose if the planet has oxygen or not.

https://github.com/terrarium-earth/Ad-Astra/tree/1.19/common/src/main/resources/data/ad_astra/planet_data/planets

https://github.com/terrarium-earth/Ad-Astra/tree/1.19/common/src/main/resources/assets/ad_astra/planet_resources

**Comment by Subthy** [comment]
Gotcha, Thank ya my man

**Comment by AlexNijjar** [comment]
Decided to make the wiki: https://github.com/terrarium-earth/Ad-Astra/wiki

**Comment by Subthy** [comment]
Good job and thank you. Keep up the good work
