### ISSUE TITLE
[Feature Request]: A dorsal combination with a stationary elevation

### ISSUE THREAD

**Issue by phiphila** [terrarium-earth/Ad-Astra#123]
### Solution(s)

Can we consider having a dorsal combination with a stationary elevation.  for example activated by a key on the keyboard and then you can go up and down as you wish by two other keys on the keyboard.  that would be easier for building our structures.

### Mod Version

1.19.2

### Mod Loader Version

1.19.2

**Comment by AlexNijjar** [comment]
what exactly do you mean? is this for building space stations in orbit? or flying in the jet suit?
