### ISSUE TITLE
[Bug]: Compressor inputs / outputs vanish after the first compression finishes (FABRIC)

### ISSUE THREAD

**Issue by AgentStormy44** [terrarium-earth/Ad-Astra#125]
### Bug Description

Instead of producing more than one output (per time the block is placed), all input and output in a compressor is quickly deleted straight into thin air. It does not go anywhere outside the block, it just vanishes without a trace.

### How to Reproduce?

1. Put a steel ingot into a compressor after giving it energy.
2. Wait for it to finish.
3. Add another steel ingot and watch what happens.

### Expected Behavior

I would expect the machine to work as normal by working as a normal furnace-like GUI. However, the contents seem to just disappear into thin air...?

### Version

1.12.0

### Mod Loader Version

1.19.2 - Fabric 1.14.2

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
It'll be fixed in the next update. I'll release it later today

**Comment by AgentStormy44** [comment]
Thanks! You're a great dev - thanks for the great mod and taking community feedback to help refine it.

**Comment by AlexNijjar** [comment]
no problem! tysm
