### ISSUE TITLE
[Bug]: Game crash when your rocket leaves earth. (Vivecraft)

### ISSUE THREAD

**Issue by totallysoulless** [terrarium-earth/Ad-Astra#128]
### Bug Description

After I launched the rocket and went up, I went up to the very end and then the game crashed. Nothing else.
I assume that it's supposed to have a planet selection screen when you reach the end, which did not happen. It simply crashed.
**ALL OF THIS USING VIVECRAFT**

### How to Reproduce?

1. Go inside a rocket
2. Launch the rocket
3. When rocket reaches a certain point the game crashes

### Expected Behavior

I expected for it to show me a planet selection screen in my Vivecraft "hud" (I had my hud placed on my wrist, so any HUD element that would show up in front of a normal screen would show up in the wrist.)

### Version

1.11.9

### Mod Loader Version

1.19.2 - Fabric 0.14.12

### Mod Loader

Fabric

### Logs or additional context

[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/10367747/latest.log)
[crash-2023-01-05_22.07.23-client.txt](https://github.com/terrarium-earth/Ad-Astra/files/10367748/crash-2023-01-05_22.07.23-client.txt)
[crash-2023-01-05_22.07.03-server.txt](https://github.com/terrarium-earth/Ad-Astra/files/10367749/crash-2023-01-05_22.07.03-server.txt)

**Comment by AlexNijjar** [comment]
Update to the latest version: 1.12.1
