### ISSUE TITLE
[Bug]: Server keeps crashing on the modpack ATM8 1.19.2

### ISSUE THREAD

**Issue by sakura6003** [terrarium-earth/Ad-Astra#129]
### Bug Description

I really do not understand it myself, so just going to paste a pastebin here with the whole crash log

### How to Reproduce?

1. Start server
2. Let it load
3. It crashes
4: repeat

### Expected Behavior

I expected the server to work

### Version

1.12.1

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/EeZaF02j

**Comment by AlexNijjar** [comment]
you’re using botarium 1.19.3. did you manually add that?

**Comment by sakura6003** [comment]
Nope, it came automatically when installing ATM8 to the server
________________________________
Fra: Alex Nijjar ***@***.***>
Sendt: tirsdag 10. januar 2023 00:49
Til: terrarium-earth/Ad-Astra ***@***.***>
Kopi: SakuraTM_ ***@***.***>; Author ***@***.***>
Emne: Re: [terrarium-earth/Ad-Astra] [Bug]: Server keeps crashing on the modpack ATM8 1.19.2 (Issue #129)


you’re using botarium 1.19.3. did you manually add that?

**Comment by sakura6003** [comment]
It came automatically with the ATM8 modpack when installing it on the server

**Comment by sakura6003** [comment]
> you’re using botarium 1.19.3. did you manually add that?

It came automatically with the ATM8 modpack when installing it on the server

**Comment by AlexNijjar** [comment]
try doing a fresh reinstall. if it’s still happening maybe atm broke their server pack and should thus be reported to them
