### ISSUE TITLE
[Bug]: Coal generator consumes lava buckets without leaving them behind

### ISSUE THREAD

**Issue by TooManyLimits** [terrarium-earth/Ad-Astra#130]
### Bug Description

When using a lava bucket to fuel the coal generator, the bucket is consumed along with the lava.

### How to Reproduce?

This issue happened to me while playing the All of Fabric 5 modpack. I haven't tested it outside of the modpack yet.
1. Place a lava bucket in the coal generator.
2. Watch as the entire bucket disappears.

### Expected Behavior

I expected the bucket to remain in the fuel slot after the lava was consumed, as this is what happens in the vanilla furnace and in many other modded combustion generators.

### Version

1.0.5-1.18.2

### Mod Loader Version

0.14.12

### Mod Loader

Fabric

**Comment by TooManyLimits** [comment]
Inspecting the source code, this issue appears to have been resolved in the 1.19 branch by disallowing the use of bucket items as fuel. However the 1.18 branch does not have any such restriction in place, and just decrements the item count regardless of the fuel type.

**Comment by AlexNijjar** [comment]
We no longer support 1.18, however if we ever decide to update it for whatever reason, I can back port the fix.
