### ISSUE TITLE
[Bug]: Compressor deletes all items input

### ISSUE THREAD

**Issue by Warentan** [terrarium-earth/Ad-Astra#131]
### Bug Description

When inputting any item into the compressor, the item is deleted. Also deletes any outputs.

### How to Reproduce?

Go into compressor and input any items

### Expected Behavior

Compressor should not smelt invalid items, but still should not delete them.

### Version

1.12.0

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
update to 1.12.1
