### ISSUE TITLE
[Bug]: The mod will not run

### ISSUE THREAD

**Issue by FatFrosty** [terrarium-earth/Ad-Astra#132]
### Bug Description

I'm running forge 43.2.0 the recommended version and I keep getting the error:
An unexpected issue occurred and the game has crashed. We're sorry for the inconvenient
Exit Code: 1
I really love to try this mod and don't know what I'm doing wrong.
Help would be appreciated thanks.

### Version

1.12.1

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
logs please

**Comment by MokahTGS** [comment]
This issue doesn't generate a crash log.  This happens with both ad_astra-forge-1.19.2-1.12.1.jar and ad_astra-forge-1.19.2-1.12.0.jar version.  If you roll back to ad_astra-forge-1.19.2-1.11.9.jar everything is fine.

**Comment by AlexNijjar** [comment]
send the latest.log

**Comment by MokahTGS** [comment]
https://pastebin.com/m8tiGxu3

**Comment by AlexNijjar** [comment]
update resourcefullib to 1.1.19
