### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by willis1030** [terrarium-earth/Ad-Astra#133]
### Bug Description

Put an ingot into compressor, the ingot will disappear, unless dig the compressor off and replace it! after 1 time normal use, 2nd time will bug.

### Version

1.19.2-1.12.0

### Mod Loader Version

forge-1.19.2-43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
update to 1.12.1
