### ISSUE TITLE
[Bug]: 1.19.2 Wrong flag model

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#136]
### Bug Description

![image](https://user-images.githubusercontent.com/44163945/211832030-1906d548-1970-4883-acc2-b13c769dab55.png)

### Version

1.12.1

### Mod Loader Version

1.19.2-43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
oops. will be fixed in a patch

**Comment by AlexNijjar** [comment]
fixed in latest
