### ISSUE TITLE
[Bug]: Machines fluid not saved

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#137]
### Bug Description

Machines fluid be empty after join world

![Fluid](https://user-images.githubusercontent.com/44163945/211835012-da3aea26-db82-4029-8bf5-4f3da925b54c.gif)

### How to Reproduce?

1. Fill machine with fluid
2. Save and quit to title
3. Join world again

### Expected Behavior

1. Show fluid as i saved.

### Version

1.12.1

### Mod Loader Version

1.19.2-43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
fixed in latest
