### ISSUE TITLE
[Feature Request]: Allow Moving/Hiding HUD Items

### ISSUE THREAD

**Issue by Avakining** [terrarium-earth/Ad-Astra#140]
### Is your feature request related to a problem?

HUD for space/jet suits overlaps with/covers other HUD elements, such as minimaps.

### Solution(s)

A config for position of the battery and oxygen levels HUD.

### Describe alternatives you've considered

Allow hiding HUDs instead?

### Mod Version

1.12.1

### Mod Loader Version

1.19.2 - 0.14.12

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
there's an option in the config already to change the position of the oxygen and energy overlay
