### ISSUE TITLE
[Bug]: Sky textures get corrupt on Earth

### ISSUE THREAD

**Issue by Warentan** [terrarium-earth/Ad-Astra#141]
### Bug Description

After playing for a while, I noticed that the sun had become a large white square rapidly flashing (see below). Eventually, after equipping my space suit, the "Sun" turned into the O2 texture.

### How to Reproduce?

Unknown...
Occurred randomly during gameplay. Hasn't happened since. I assume As Astra! is related due to the O2 texture.

### Expected Behavior

Sun should stay consistent

### Version

1.12.1

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

![2023-01-11_22 08 09](https://user-images.githubusercontent.com/113652968/212223031-1b7f9047-aa23-4ea5-8d1f-212bef695956.png)
![2023-01-11_22 01 34_4](https://user-images.githubusercontent.com/113652968/212223066-12a5b849-46c7-4105-9e17-95c892e03eaa.png)
![2023-01-11_22 01 34_3](https://user-images.githubusercontent.com/113652968/212223109-aed8d439-a154-47b5-b2f5-80dcdd68c072.png)

**Comment by AlexNijjar** [comment]
do you have optifine, sodium, or iris?

**Comment by Warentan** [comment]
No, I am playing with zero shaders, just the Ad Astra! mod.

**Comment by AllyJaxx** [comment]
Isn't this a vanilla issue that just happens at complete random? Swear I've seen posts about this happening to random people in vanilla.

**Comment by AlexNijjar** [comment]
if it is, there's nothing we can do about it and no one else has been able to reproduce it
