### ISSUE TITLE
[Suggestion]: Too large Oxygen and Energy indicator bar

### ISSUE THREAD

**Issue by willis1030** [terrarium-earth/Ad-Astra#142]
### Is your feature request related to a problem?

Oxygen and energy bar(jet suit) are too large so that covered minimap, and ocupied 2 corners. can you make a smaller one and put them at one corner?

### Mod Version

1.19.2-1.12.1

### Mod Loader Version

1.19.2-43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
you can move their position in the config

**Comment by willis1030** [comment]
Yes, it work, but energyBarXOffset=0 is from right side. because of screen resolusion or windows size, it is hard to move  energyBar to the left cornor.

**Comment by AlexNijjar** [comment]
I added an option to change the scale. it'll be available in the next update
