### ISSUE TITLE
[Bug]: Machines fluid and power lost after dimension released and reloaded (server)

### ISSUE THREAD

**Issue by willis1030** [terrarium-earth/Ad-Astra#144]
### Bug Description

Machines fluid and power lost after dimension released and reloaded (server play), although it is reported before by another one.

https://user-images.githubusercontent.com/16789564/212468320-45ebf2cd-4058-42ff-b319-c01be4f705d2.mp4

### Version

ad_astra-forge-1.19.2-1.12.1

### Mod Loader Version

forge-1.19.2-43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
it should be fixed in the latest version: 1.12.2

**Comment by willis1030** [comment]
Yes, it fixed in latest version, thankyou!
