### ISSUE TITLE
[Bug]: empty catalog and crash report

### ISSUE THREAD

**Issue by Rogenar** [terrarium-earth/Ad-Astra#145]
### Bug Description

after launch still the catalog is empty and i have to close and reopen the game, also it works with version of botarium-fabric-1.19.3-2.0.1.jar but version of botarium-fabric-1.19.3-2.0.4.jar causes it to crash.

### Version

1.19.3

### Mod Loader Version

1.19.3-1.13.1

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
fixed in 1.13.3
