### ISSUE TITLE
[Bug]: Crash on 1.19.2 Fabric Latest Version!

### ISSUE THREAD

**Issue by pokesmells** [terrarium-earth/Ad-Astra#146]
### Bug Description

When updating to version ad_astra-fabric-1.19.2-1.12.2.jar

Crashes on start up!

Reverted to version ad_astra-fabric-1.19.2-1.12.1.jar.

### How to Reproduce?

1. Update the mod to 
ad_astra-fabric-1.19.2-1.12.2.jar

2. Start up the profile

3. Crash on start up

### Expected Behavior

I expected it to run as normal.

### Version

ad_astra-fabric-1.19.2-1.12.2.jar

### Mod Loader Version

1.19.2 - Fabric 0.14.12

### Mod Loader

Fabric

### Logs or additional context

[crash-2023-01-14_12.20.47-client.txt](https://github.com/terrarium-earth/Ad-Astra/files/10418546/crash-2023-01-14_12.20.47-client.txt)

**Comment by challenger1** [comment]
This exact error in my modpack came from adding Tree Harvester + Collective.

**Comment by AlexNijjar** [comment]
It looks like a Collective issue. please report it on their GitHub
