### ISSUE TITLE
[Feature Request]: Ability to change or disable Meteorites spawn

### ISSUE THREAD

**Issue by Patryk122PL** [terrarium-earth/Ad-Astra#149]
### Is your feature request related to a problem?

Not able to change meteorites spawning behaviour tends to clash with other mods like Applied Energistics 2.

AE2 tends to spawn it more inside ground (invisible on first glance) and their meteorite have a purpose, but if for some reason user / modpack maker wants to change it, he can at least disable spawning.

Without an option to disable or change spawning rules of Ad Astra meteorites the overworld tends to be a little bit too crowded with giant holes ;)

### Solution(s)

Please add configuration options for world-gen Meteorites.

The best solution would be if we could modify spawning chance, radius, size and height, but as far as I'm aware this seems to be difficult in 1.19.

A least an option to disable it completely would be much appreciated.

### Mod Version

1.12.2

### Mod Loader Version

1.19.2 - 43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
the meteorite structure is defined in ad astra's internal data pack so you can remove it by making your own data pack that overrides this tag and makes it empty https://github.com/terrarium-earth/Ad-Astra/blob/1.19/common/src/main/resources/data/ad_astra/tags/worldgen/biome/has_structure/meteor_biomes.json

**Comment by Patryk122PL** [comment]
Sure.. I know about datapack way but that is not very elegant solution long term. It can break if you change structure name and for regular player not familiar  with minecraft datapacks structure it's difficult if not impossible to disable.

Edit: Also it requires manual datapack activation for every newly created world or another mod e.g Open Loader to do this automatically..
