### ISSUE TITLE
Glacian trap doors not placed properly

### ISSUE THREAD

**Issue by Aulluna** [terrarium-earth/Ad-Astra#15]
Glacian trap doors will always be placed east-west axis no matter where it is facing ( north , east , west , south )
But this is only when it is not activated 
Here are some screenshots :
- a trap door facing south 
![image](https://user-images.githubusercontent.com/76559595/189481017-4cfe3bd8-d89a-4929-9a2f-bbe4e9745a1c.png)
- a trap door facing east , u can see that they are on the same axis
![image](https://user-images.githubusercontent.com/76559595/189481117-c57885ab-2998-4f55-83d1-0b457abd77b9.png)
- and now when I activated the trapdoor , for some reason the axis changed 
![image](https://user-images.githubusercontent.com/76559595/189481218-7d1e7cf8-2d65-41e8-96f9-aca6efbcbfa2.png)

**Comment by AlexNijjar** [comment]
This might be a minecraft issue; I'll check it out but I don't think I can do anything about it.
