### ISSUE TITLE
[Bug]: Ad Astra: Stuck in Loading Screen

### ISSUE THREAD

**Issue by Bronkaaa** [terrarium-earth/Ad-Astra#150]
### Bug Description

I currently have a bug on our All the mods 8 Minecraft Server. I launched my first rocket trying to go to space. After the rocket launches it opens up a new screen where you are supposed to select the planet you want to land on. The problem is this screen is completely bugged. I cant select anything because i dont have any buttons to click on and i also have no idea how to ever get out of this loading screen. I cant even open the chat with t to teleport me or something so im completely stuck. If somebody knows an answer to this please help me. Thank you!

### Version

1.19.2-1.12.2

### Mod Loader Version

43.1.55

### Mod Loader

Forge

### Logs or additional context

![Unbenannt](https://user-images.githubusercontent.com/108400219/212498637-8d77ba11-c54b-4445-bfa7-7601cf979154.PNG)

**Comment by AlexNijjar** [comment]
can you send the latest.log?

**Comment by MckeksikYTB** [comment]
i have the same problem

**Comment by AlexNijjar** [comment]
are you sure the mod version is 1.19.2-1.12.2? because this was supposed to be fixed in 1.12.0

**Comment by MckeksikYTB** [comment]
oh thanks i missed it
