### ISSUE TITLE
[Bug]: blank catalog

### ISSUE THREAD

**Issue by Rogenar** [terrarium-earth/Ad-Astra#151]
### Bug Description

planets not appearing in catalog when rocket reaches limit after launch
![sddsa](https://user-images.githubusercontent.com/122460325/212499706-816c8430-b1a8-4907-af1e-1b2f5424a86b.png)

### Version

1.19.3

### Mod Loader Version

1.19.3-1.13.2

**Comment by AlexNijjar** [comment]
fixed in 1.13.3
