### ISSUE TITLE
[Bug]: Unable to select a planet in the loading screen

### ISSUE THREAD

**Issue by SlytherTheUndertaker** [terrarium-earth/Ad-Astra#152]
### Bug Description

I have a problem when selecting planets.
I'm playing 1.19.2, and I'm already loving this mod!
However, I have one issue that has affected my gameplay. Whenever I try to select a space station (even if all requirements are met), it just sends me back to the catalog screen. That problem has been the same with all the "orbit" and "planet" options. (with the exception being Earth).

Is there any fix to this?

### Version

1.12.2

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
if you do the command “/execute in” does it show a list of the ad astra dimensions? or just the vanilla ones?

**Comment by SlytherTheUndertaker** [comment]
I tried out the command. It shows a list of the Ad Astra dimensions, so when I tried launching the rocket and chose mars.. it worked just fine now.
Perhaps in a previous world, it didn't work initially, but now it works now ig

**Comment by ThatGravyBoat** [comment]
If you have this happen again can you send your log as if there is a network issue causing this it will log the problems.

**Comment by Firezone87** [comment]
i have the same problem but if i do the command "/execute in" it doesnt show the ad astra dimensions

**Comment by pPkMnh4to8994h** [comment]
Same issue.
`/execute in` doesn't show any new dimensions.
Version is 1.12.3

**Comment by AlexNijjar** [comment]
even if you exist the world and rejoin?

**Comment by pPkMnh4to8994h** [comment]
> even if you exist the world and rejoin?

Yes, even creating new world does nothing.

**Comment by pPkMnh4to8994h** [comment]
[Log file](https://gist.github.com/pPkMnh4to8994h/781c3a34df3769df630d92a70adc8b95)
UPDATE: For all of those who stumble upon this page by googling or searching, **updating Forge** solves this. If you're using CurseForge launcher, you are very likely to hit this problem because CF launcher automatically sets Forge version 43.2.0 instead of the latest version, which is 43.2.4.

**Comment by Mathis1769** [comment]
Hey, I have forge 43.2.4 and ran into this issue, when I do /execute in it only shows the vanilla dimensions

**Comment by AlexNijjar** [comment]
> Hey, I have forge 43.2.4 and ran into this issue, when I do /execute in it only shows the vanilla dimensions

try the solution above
