### ISSUE TITLE
[Bug]: Cryo fuel unreasonable temperature value

### ISSUE THREAD

**Issue by Patryk122PL** [terrarium-earth/Ad-Astra#153]
### Bug Description

Cryo fuel "-10000000" temperature value breaks mods that use thermal conductivity mechanics such as e.g. Pneumaticcraft.
 
![2023-01-16_08 04 47](https://user-images.githubusercontent.com/9610133/212619562-61ed622d-1e52-445b-b585-23f93b03a76c.png)

### Expected Behavior

If we want to be realistic, then nothing can be less than -273*C (absolute zero temperature).

Cryo fuel more or less resembles liquid nitrogen therefore it should be around -196*C.

### Version

1.12.2

### Mod Loader Version

1.19.2 - 43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
changed to -196 and will release and update in a bit
