### ISSUE TITLE
[Bug]: Game crashes when loading on the moon

### ISSUE THREAD

**Issue by ChewyALEC** [terrarium-earth/Ad-Astra#157]
### Bug Description

I play on a minecraft server with a few of my friends (1.19.2)
We have a few mods installed but whenever we attempt to go to the moon, it crashes the server!
Last time this happened it was on a previous server, and no one was able to connect to the server
This time it appears that everyone else can play on the server but whenever I load in, it crashes! 
I checked the crash-report and it appears to be a "Exception ticking world" error, which is the same error I had gotten prior on a previous server.

### How to Reproduce?

(This can happen on a single player world aswell but mainly a 1.19.2 Forge server)
1. Launch your rocket into orbit
2. Select Moon
3. Load Chunks
4. If nothing has crashed, walk around for a few chunks to load more

### Expected Behavior

I expected to be able to at least land on the moon. The last attempted time I landed but it crashed shortly after (Within 5 minutes) in which it crashed with the error being an internal tick error.
I then expected since this is a different modpack with a different list of mods, there would be different results but it appears not.

### Version

1.12.2

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/ECCegD0C
^The first server crash report on the previous server with different modpack^

https://pastebin.com/jSUiL68S
^ The latest server crash report ^

**Comment by AlexNijjar** [comment]
It looks like an incompatibility with immersive weathering. you should report it to them 

https://github.com/AstralOrdana/Immersive-Weathering/blob/5cee950273ef70343428ad0fad86df70d204a062/forge/src/main/java/com/ordana/immersive_weathering/mixins/forge/FluidInteractionRegistryMixin.java
