### ISSUE TITLE
[Bug]: mobs spawn on the moon and immediately die 

### ISSUE THREAD

**Issue by AEther000** [terrarium-earth/Ad-Astra#158]
### Bug Description

mobs (like flies) spawn on the moon and immediately die 

### How to Reproduce?

go to the moon
wait for mobs to start spawning
mobs that are not supposed to spawn start spawning

### Expected Behavior

i was expecting only intended mobs to be able to spawn on the moon

### Version

1.13.3

### Mod Loader Version

1.19.2

**Comment by AlexNijjar** [comment]
i don't really think we can do anything about this on our side; this should be reported to alex's mobs
