### ISSUE TITLE
Very high memory usage.

### ISSUE THREAD

**Issue by ZekeZDev** [terrarium-earth/Ad-Astra#16]
Hi,

Ad-astra was recently added to a new release of one of my modpacks and upon hosting a server with it we noticed excessive ram usage. It seems to fill all available ram we started at 6 and upgraded to 8. No direct performance impact is visible however this is concern for stability. If this is something that could be addressed that would be greatly appreciated. 

Modpack: https://modrinth.com/modpack/hexmc-modpack

I have yet to directly test this however it only seems to happen active worlds that have generated the dimensions.

**Comment by AlexNijjar** [comment]
Have you run a spark report to see exactly what mods are using high memory?

https://www.curseforge.com/minecraft/mc-mods/spark

**Comment by ZekeZDev** [comment]
Ill try using it again however I wasnt able to find useful information from it last time. So far its incredibly noticable difference in removing ad-astra from the modpack. Ill get back to you when I have time to profile it.

**Comment by ZekeZDev** [comment]
It seems to be a server related issue that has now been resolved, thanks for your time and keep up the good work!
