### ISSUE TITLE
[Bug]: (1.19.2 Fabric) Using a waystone (Fabric Waystones) to travel between planets without having used a rocket prior to teleporting in any given session will cause the game to ignore player gravity changes

### ISSUE THREAD

**Issue by AgentStormy44** [terrarium-earth/Ad-Astra#161]
### Bug Description

Essentially, when using a waystone with the mod "Fabric Waystones", I have discovered that if I have not travelled to the destination planet in that session via a Rocket, I will not be given any gravitational changes(for example, teleporting to the moon from the earth will leave me on the moon with normal earth gravity).

I would assume this is due to gravitational adjustments being given at the solar system/planet selection screen, which may break third party methods of travel between dimensions.

### How to Reproduce?

1. Use "Ad Astra" with the mod "Fabric Waystones" (For example, on a server, this bug occurs)
2. Travel to the moon and place down a waystone
3. Go back to Earth and place down a waystone
4. Reload the world/server on the earth, and teleport to the moon via the earth waystone
5. Gravity does not function properly

### Expected Behavior

Gravity would change with each planet regardless of the means of travel.

### Version

1.12.1

### Mod Loader Version

1.19.2 - Fabric 1.14.2

### Mod Loader

Fabric

### Logs or additional context

(This bug was encountered on a server - I have not tested it in singleplayer)

**Comment by AlexNijjar** [comment]
interesting; i've played ad astra with fabric waystones before in AOF5 1.18 and it was working fine. Maybe something changed on their end in 1.19? i'll check it out

**Comment by AgentStormy44** [comment]
Thanks! I've discovered the same thing sometimes happens upon logging into the world on a non-earth planet after having logged out there. I have a guess that maybe it has to do with loading into the world with normal gravity that maybe changes as you are travelling to other planets, but I'm not sure if this is the case as I do not know if gravity is bound to the planet/dimension or assigned via different methods. Regardless, thanks for looking into it!

**Comment by ThatBlockyPenguin** [comment]
Can confirm that this bug also occurs in the Forge version, mod version 1.12.2 Forge version 13.1.52, when using the Forge Waystones mod.

**Comment by axcyia** [comment]
Encountered the same bug in Forge as well. Mod version 1.19.2, Forge version 43.2.3.
Happens with not only the Waystones mod, but Mekanism's teleporter as well.

**Comment by depthbysoul** [comment]
no gravity also can occur if entering a dungeon on moon with no gravity once get out grav stays gone sometimes.

**Comment by AlexNijjar** [comment]
will be fixed in the latest version. You are correct. This happens because the gravity data is only sent to the client when they open the planet selection screen. so on a dedicated server the client uses the earth gravity since it's never sent the moon gravity
