### ISSUE TITLE
[Bug]: Energy is not transferred to any devices

### ISSUE THREAD

**Issue by freyzik228** [terrarium-earth/Ad-Astra#162]
### Bug Description

when trying to use a coal generator or a solar panel, they do not transfer energy to the compressor and other energy-demanding units

https://user-images.githubusercontent.com/119435074/213909756-2ab032ce-6666-401f-ad1e-6e3e3f08632e.mp4

### How to Reproduce?

1charge the coal generator
2place a compressor or other device nearby
3energy is not transferred

### Expected Behavior

the coal generator was supposed to transmit energy

### Version

1.12.2 

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by freyzik228** [comment]
don't mind that i'm on the moon, it doesn't work on earth either

**Comment by freyzik228** [comment]
.

**Comment by freyzik228** [comment]
don't mind that i'm on the moon, it doesn't work on earth either

**Comment by freyzik228** [comment]
> <img alt="@freyzik228" width="20" height="20" src="https://avatars.githubusercontent.com/u/119435074?s=40&amp;v=4">

**Comment by Mattslayer2006** [comment]
how did you resolve this issue

**Comment by AlexNijjar** [comment]
do you happen to have optifine installed?

**Comment by Mattslayer2006** [comment]
yes
