### ISSUE TITLE
[Bug]: The energy is not transferring to energy needing machines

### ISSUE THREAD

**Issue by Mattslayer2006** [terrarium-earth/Ad-Astra#163]
### Bug Description

The energy generated by a an energy generator is not transferring to energy needing machines.

### How to Reproduce?

1. Grab an energy producer and any machine from the ad astra tab menu.
2. connect them together with either wires or place them side by side.
3. Fill the energy producer with the needed fuel (if needed).

### Expected Behavior

The energy generator is filling up with energy but it is not transferring energy to the machines.

### Version

1.11.8

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
do you happen to have optifine installed by chance? if not, what machine from what mod are you trying to connect it to?

**Comment by Mattslayer2006** [comment]
of the same mod and yes i have optifine

**Comment by AlexNijjar** [comment]
can you try without it? some people have been reporting some very weird issues with optifine and energy

**Comment by Mattslayer2006** [comment]
ok il try

**Comment by Mattslayer2006** [comment]
Thx it worked
