### ISSUE TITLE
[Bug]: Breaking Lander crashes the game 1.19.3

### ISSUE THREAD

**Issue by AyavouyaGR** [terrarium-earth/Ad-Astra#165]
### Bug Description

Landing on a planet and breaking the lander causes the game to freeze and quit
I tested this in Creative Mode

### How to Reproduce?

1. Get into a creative minecraft world with the mod
2. Launch to a planet of your choice
3. Land
4. Break the Lander

### Expected Behavior

I expected for the lander to break and drop.

### Version

1.13.3

### Mod Loader Version

Forge 1.19.3-44.1.8

### Mod Loader

Forge

### Logs or additional context

[crash-2021-03-12_19.39.48-client.txt](https://github.com/terrarium-earth/Ad-Astra/files/10511999/crash-2021-03-12_19.39.48-client.txt)

**Comment by AlexNijjar** [comment]
It's fixed I'll release an update soon
