### ISSUE TITLE
[Bug]: Weird Meteor Generation

### ISSUE THREAD

**Issue by fizzzydev** [terrarium-earth/Ad-Astra#166]
### Bug Description

Seed: -2278166681177540571
Pos: -407 109 231 
Mod: 1.13.3
Minecraft 1.19.3
![2023-01-27_11 49 07](https://user-images.githubusercontent.com/116093367/215070205-566bbdf8-1358-46ea-bc1b-631e37605e01.png)
![2023-01-27_11 53 28](https://user-images.githubusercontent.com/116093367/215070283-62fbdbcf-4c65-41df-b4f7-d7927ff122f8.png)

### Expected Behavior

The Meteor should blend in to natural terrain.

### Version

1.13.3

### Mod Loader Version

0.14.13

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
that just looks like an unlucky spawn? I can't really do anything about it
