### ISSUE TITLE
[Bug]: carry on mode crash

### ISSUE THREAD

**Issue by Rogenar** [terrarium-earth/Ad-Astra#167]
### Bug Description

The game crashes when I pick up a professional lunarian with the carry on mode. But the game doesn't crash when I pick up an unprofessional lunarian.
versiyon astra-fabric-1.19.3-1.13.3
[rei-issues.log](https://github.com/terrarium-earth/Ad-Astra/files/10527358/rei-issues.log)
[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/10527359/latest.log)
[rei.log](https://github.com/terrarium-earth/Ad-Astra/files/10527363/rei.log)
[crash-2023-01-28_16.17.24-client.txt](https://github.com/terrarium-earth/Ad-Astra/files/10527366/crash-2023-01-28_16.17.24-client.txt)

**Comment by depthbysoul** [comment]
good to know as havent tryed this yet but was gonna today lol

**Comment by Rogenar** [comment]
The problem is not in the name astra mode, there is an error in the carry on mode. Generally dealing with a professional villager causes the game to crash.
