### ISSUE TITLE
[Feature Request]: Compat for Tinted 

### ISSUE THREAD

**Issue by ThugPug43** [terrarium-earth/Ad-Astra#168]
### Is your feature request related to a problem?

The problem is that when ad astra and Tinted are both installed the flags do not exist in Tinted's added colors. 

### Solution(s)

The solution would be to have flags which are available when Tinted is installed which are in the colors their mod adds.

### Describe alternatives you've considered

I considered not having support for the flags, especially since armor works probably due to how dyeing that is more flexible, and that alternative is how it works already. That is not as fun as support for all the dyes in my opinion.

### Mod Version

 ad_astra-forge-1.19.2-1.12.2.jar

### Mod Loader Version

43.2.0 (1.19.2)

### Mod Loader

Forge

### Additional context

Tinted is a pretty cool mod which adds new dye types and it already supports natively a lot of mods, supporting Tinted would be a fun way to get more colors for the people playing with both and would expand the audience of both mods since people will want to use both of them together.

**Comment by AlexNijjar** [comment]
Tinted should add support to Ad Astra, not the other way around. This would not be something I'd be interested in adding support for.
