### ISSUE TITLE
[Suggestion] Generation options

### ISSUE THREAD

**Issue by Drezkil** [terrarium-earth/Ad-Astra#17]
While testing a modpack of mine i just happened to find a village destroyed by a meteor.

You can say it's fine but knowing that it can happen and it might be really bothersome i was expecting to find options about meteor generation but there is none.

So i would like to know if you're planning to add one like generating only in certain biomes (blacklist/whitelist) or to simply disable it.

**Comment by Aulluna** [comment]
You can do that with datapacks afaik

**Comment by Drezkil** [comment]
Well i don't know all i found was the author saying you may be able to add planets and stuff.

This is a different case, i want to remove something it might be a little trikier.

Anyway i think i'll go post my suggestion in the discord for more visibility and then close this issue.
