### ISSUE TITLE
[Bug]: No oil generates when "oh the biomes you'll go" is installed.

### ISSUE THREAD

**Issue by patrlim** [terrarium-earth/Ad-Astra#170]
### Bug Description

the title says it all, i have explored a vast swathe of ocean and haven't found any oil, I've found at minimum 10 ocean monuments, no oil.

### How to Reproduce?

1. Download Ad Astra
2. Download Oh The Biomes You'll Go
3. Explore
4. Find no oil.

### Expected Behavior

There would be oil

### Version

Latest

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
I don't see why it wouldn't work. the oil spawns in the #minecraft:is_ocean tag and byg adds their biomes to that tag. maybe another mod is breaking it?

https://github.com/AOCAWOL/BYG/blob/1.19.X/Common/src/main/resources/data/minecraft/tags/worldgen/biome/is_ocean.json

https://github.com/terrarium-earth/Ad-Astra/blob/1.19.3/common/src/main/resources/data/ad_astra/tags/worldgen/biome/has_structure/oil_well_biomes.json

**Comment by gittibene** [comment]
Works fine for me with BYG, Terralith and others

**Comment by opschnecke** [comment]
I've got the same issue and found something in the log: 
`[18May2023 19:19:09.115] [main/WARN] [net.minecraft.core.MappedRegistry/]: Not all defined tags for registry ResourceKey[minecraft:root / minecraft:worldgen/biome] are present in data pack: ad_astra:has_structure/oil_well_biomes`

Should I create a new Issue?
