### ISSUE TITLE
[Bug]: Cannot extract from Fuel Refinery with Create Fluid Pipes

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [terrarium-earth/Ad-Astra#171]
### Bug Description

When using the Create mod's Fluid Pipes/Mechanical Pump, I can insert Oil, but cannot extract Fuel.

### How to Reproduce?

1. Install the Create Mod
2. Place a Fuel Refinery
3. Add one Create Mechanical Pump on either side of the Fuel Refinery, one pointing in and one pointing out.
4. Add a source of Oil on the input pump, and any block that accepts fluid on the extract pump.
5. Power the pumps with rotational force
6. Watch the Oil get inserted, and no Fuel get extracted

### Expected Behavior

I would expect the Fuel to be exported.

### Version

1.12.2

### Mod Loader Version

13.1.52

### Mod Loader

Forge

**Comment by KLONOA9X6** [comment]
Did you tried "smart fluid pipe" in create?

**Comment by WindFox** [comment]
Same issue with Mekanism pipes and Thermal's fluiducts.

**Comment by bcrotty** [comment]
The Pipez Fluid Pipe works.

**Comment by ThatBlockyPenguin** [comment]
> Did you tried "smart fluid pipe" in create?

Yes, they don't work either :(

**Comment by KLONOA9X6** [comment]
> > Did you tried "smart fluid pipe" in create?
> 
> Yes, they don't work either :(

Are you sure? The smart fluid pipe must connect straightly to machine and need set a fluid which need to transport.

**Comment by ThatBlockyPenguin** [comment]
Yes, I am sure.

https://github.com/terrarium-earth/Ad-Astra/assets/38588376/8767279e-0c86-4ab5-a5c0-e3ee62ab7291

**Comment by AlexNijjar** [comment]
Should be fixed in 1.15.7. If it's not, let me know.

**Comment by NolanHewitt** [comment]
I can't get create pipes to work with ad astra machines in 1.15.17
