### ISSUE TITLE
[Bug]: Interaction between Compressor and Coal Generator causes some blocks to disappear on right-click only

### ISSUE THREAD

**Issue by MaikPaechter** [terrarium-earth/Ad-Astra#172]
### Bug Description

The issue seems to appear when placing the compressor next to the coal generator (powered or not, I am not sure yet). This causes a lot of blocks in this chunk to stay visible after breaking and vanish only when right-clicked by a player. I tested it on a multiplayer dedicated server. I am not sure about singleplayer.

### How to Reproduce?

1. Place Compressor and Coal Generator next to each other
2. Power Coal Generator (maybe not necessary to reproduce)
3. Try to break or place some blocks in the chunk
4. Some blocks should stay visible after breaking
5. Right-click block "phantoms"
6. Right-clicked blocks should disappear

### Expected Behavior

The interaction between those machines or every machine on it's own should'nt affect the blocks of the chunk they are placed in.

### Version

1.12.2

### Mod Loader Version

1.19.2 - 43.2.1

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
does this happen with just ad astra and its dependencies installed? and no performance mods like Optifine

**Comment by MaikPaechter** [comment]
yeah no performance mods on client side and nothing on server side which could affect blocks in such a way in my opinion

**Comment by AlexNijjar** [comment]
what do you mean in your opinion? did you test it with only ad astra?

**Comment by MaikPaechter** [comment]
That I think they wont affect the bug but I can test it further. I did not have the bug in singleplayer. I am adding the mod list of the server as a screenshot here if you want me to remove some specific mods for testing. I cannot remove some of the bigger content mods because I don't want to break something in the world.

![image](https://user-images.githubusercontent.com/101045825/222722002-00e058d8-1798-464e-9e94-29818c7aeaa3.png)

**Comment by AlexNijjar** [comment]
well what I'm asking is if this bug is an ad astra issue or a mod incompatibility issue. I need to know if some mod on that list is breaking ad Astra or if this is something on my end I need to fix. you can test this by seeing if you can reproduce this issue with only ad astra and its dependencies installed

**Comment by MaikPaechter** [comment]
I see your point, thank's for clarfying. I took the time and tested it on a new world with just ad astra and it's dependencies and didn't get the bug. The same with this mod subset. So I guess it's an incompatibility issue. 
![image](https://user-images.githubusercontent.com/101045825/222792092-577f761b-51b4-4a5e-90ef-c299e2e2cb41.png)

**Comment by AlexNijjar** [comment]
yeah I don't really know how to fix this if it's a large pack like this with many mods. if you can find the specific mod that's breaking with ad astra I can try to fix it
