### ISSUE TITLE
[Feature Request]: Config options for world structure generation

### ISSUE THREAD

**Issue by Branjoman** [terrarium-earth/Ad-Astra#174]
### Is your feature request related to a problem?

For the pack I'm making I want to turn off the oil spouts generated by ad astra (and maybe the meteors also), but there doesn't appear to be a config option avaliable to do this, or change any of the spawning properties of the structures (like rarity, what dimensions they're allowed in etc.).

### Solution(s)

Add config options to the spawning of ad astra structure to be able to modify how they spawn, up to turning them off if needed.

### Mod Version

1.12.2

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
you can change this in a datapack
