### ISSUE TITLE
[Bug]: MCA head is invisible

### ISSUE THREAD

**Issue by 29Naybla** [terrarium-earth/Ad-Astra#176]
### Bug Description

When I wear the space helmet using MCA, my head becomes invisible.

### How to Reproduce?

1.With MCA installed, choose the MCA model and create a character;
2.Wear the space helmet.

### Expected Behavior

The head shouldn't be invisible.

### Version

1.12.2

### Mod Loader Version

1.19.2 - 43.2.4

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
what is MCA?

**Comment by 29Naybla** [comment]
Minecraft Comes Alive

**Comment by AlexNijjar** [comment]
I believe we are switching to geckolib armor models in the rework so it should be fixed when that comes out.

**Comment by AlexNijjar** [comment]
Fixed in rework
