### ISSUE TITLE
[Bug]: crashed when interacting with lander

### ISSUE THREAD

**Issue by depthbysoul** [terrarium-earth/Ad-Astra#178]
### Bug Description

when i try to remove the lander after reaching destination my game crashes

### How to Reproduce?

once landed clicking on the lander in any way crashes the user from server

### Expected Behavior

expected to remove the lander or put n inventory something so its not just scattered everywhere upon my travels

### Version

1.13.3 fabric

### Mod Loader Version

1.19.3 

### Mod Loader

Fabric

### Logs or additional context

[crash-2023-02-04_14.14.35-client.txt](https://github.com/terrarium-earth/Ad-Astra/files/10609454/crash-2023-02-04_14.14.35-client.txt)

**Comment by EntangledLabs** [comment]
I have the exact same issue but with fabric loader 0.14.13

**Comment by depthbysoul** [comment]
o found out using carroy on i can at least pick them up n relocate them somewhere unseen lol

its a hassle as you move so slow carrying things but works to declutter area.

there is like 30 landers now lmao

**Comment by AlexNijjar** [comment]
it's fixed I'll release an update soon
