### ISSUE TITLE
Crashes on every download for 1.19.3 (FORGE)

### ISSUE THREAD

**Issue by IndigobyJas** [terrarium-earth/Ad-Astra#181]
### Bug Description

I am unable to use the mod, I keep getting a crash error 1

![Issue](https://user-images.githubusercontent.com/110175731/217526937-f9a830db-0aa2-4982-92e4-357ad9aced16.jpeg)

### How to Reproduce?

Unsure

### Expected Behavior

I expected to be able to use the mod

### Version

1.19.3

### Mod Loader Version

All 1.19.3

### Mod Loader

Forge

### Logs or additional context

It only comes up with crash error 1

**Comment by AlexNijjar** [comment]
check #180
