### ISSUE TITLE
[Bug]: Crash after hitting a ship after landing on a planet.

### ISSUE THREAD

**Issue by Gari756** [terrarium-earth/Ad-Astra#182]
### Bug Description

When I landed on any planet I wanted to destroy the ship to get it back to eq. At the same time the game crashes.

### How to Reproduce?

1. Land
2. Try to break ship after landing.
3. Crash

### Version

1.13.3

### Mod Loader Version

1.19.3

### Mod Loader

Fabric

### Logs or additional context

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-02-08 22:44:03
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_1739 cannot be cast to class earth.terrarium.ad_astra.common.item.vehicle.VehicleItem (net.minecraft.class_1739 and earth.terrarium.ad_astra.common.item.vehicle.VehicleItem are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @6b67034)
	at earth.terrarium.ad_astra.common.entity.vehicle.Vehicle.drop(Vehicle.java:245)
	at earth.terrarium.ad_astra.common.entity.vehicle.Lander.drop(Lander.java:45)
	at earth.terrarium.ad_astra.common.entity.vehicle.Vehicle.method_5643(Vehicle.java:229)
	at net.minecraft.class_1657.method_7324(class_1657.java:1274)
	at net.minecraft.class_636.method_2918(class_636.java:416)
	at net.minecraft.class_310.method_1536(class_310.java:1709)
	at net.minecraft.class_310.method_1508(class_310.java:2033)
	at net.minecraft.class_310.method_1574(class_310.java:1863)
	at net.minecraft.class_310.method_1523(class_310.java:1150)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at earth.terrarium.ad_astra.common.entity.vehicle.Vehicle.drop(Vehicle.java:245)
	at earth.terrarium.ad_astra.common.entity.vehicle.Lander.drop(Lander.java:45)
	at earth.terrarium.ad_astra.common.entity.vehicle.Vehicle.method_5643(Vehicle.java:229)
	at net.minecraft.class_1657.method_7324(class_1657.java:1274)
	at net.minecraft.class_636.method_2918(class_636.java:416)
	at net.minecraft.class_310.method_1536(class_310.java:1709)
	at net.minecraft.class_310.method_1508(class_310.java:2033)

-- Affected level --
Details:
	All players: 1 total; [class_746['Gari_756'/3, l='ClientLevel', x=-7837.44, y=108.00, z=2847.40]]
	Chunk stats: 4096, 1670
	Level dimension: ad_astra:venus
	Level spawn location: World: (-5416,71,7391), Section: (at 8,7,15 in -339,4,461; chunk contains blocks -5424,-64,7376 to -5409,319,7391), Region: (-11,14; contains chunks -352,448 to -321,479, blocks -5632,-64,7168 to -5121,319,7679)
	Level time: 273714 game time, 114642 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, resourcePack.continuity.default.name, resourcePack.continuity.glass_pane_culling_fix.name, file/Particles+ 1.19.x .zip, file/Icons 1.19.x .zip, file/Crops-3D 1.19.x .zip, file/SimpleHotbar 1.19.x .zip, file/Obscuria's-Tools-1.19.zip, file/VanillaTweaks_r709269.zip, file/Crystal_Sculk 1.19.x .zip, replaymod_lang, essential

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2150392816 bytes (2050 MiB) / 6140461056 bytes (5856 MiB) up to 15032385536 bytes (14336 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i9-12900K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: Alder Lake
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 16
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3070 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2482
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2824
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 38721.55
	Virtual memory used (MB): 23771.27
	Swap memory total (MB): 6144.00
	Swap memory used (MB): 165.95
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx14G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		accurateblockplacement: Accurate Block Placement 1.0.16
		ad_astra: Ad Astra! 1.13.3
		adaptive-tooltips: Adaptive Tooltips 1.1.1
			com_github_llamalad7_mixinextras: mixinextras 0.1.1
		additionalstructures: Additional Structures 4.1.1
		amecs: Amecs 1.3.8+mc.1.19.3
		animatica: Animatica 0.5+1.19
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.0.66
		attributefix: AttributeFix 18.0.1
		autoattack: Auto Attack 1.2.3
		axolotlitemfix: Axolotl Item Fix 1.1.4
		balm-fabric: Balm 5.0.1
		betterf3: BetterF3 5.1.0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.4+a91e48b785
		bettermounthud: Better Mount HUD 1.2.1
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 2.1.+1.19.3
		betterthirdperson: Better Third Person 1.9.0
		blur: Blur (Fabric) 2.6.0
		bookshelf: Bookshelf 17.0.3
		botarium: Botarium 2.0.4
			team_reborn_energy: Energy 2.2.0
		cardinal-components: Cardinal Components API 5.1.0
			cardinal-components-base: Cardinal Components API (base) 5.1.0
			cardinal-components-block: Cardinal Components API (blocks) 5.1.0
			cardinal-components-chunk: Cardinal Components API (chunks) 5.1.0
			cardinal-components-entity: Cardinal Components API (entities) 5.1.0
			cardinal-components-item: Cardinal Components API (items) 5.1.0
			cardinal-components-level: Cardinal Components API (world saves) 5.1.0
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.1.0
			cardinal-components-world: Cardinal Components API (worlds) 5.1.0
		cem: Custom Entity Models 0.7.1_S8_1.19
		chat_heads: Chat Heads 0.9.0
		chesttracker: Chest Tracker 1.1.19
			libgui: LibGui 6.5.1+1.19.3
				jankson: Jankson 5.0.0+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			whereisit: Where Is It 1.14.14
		chime: Chime 1.4.0
		citresewn: CIT Resewn 1.1.3+1.19.3
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.19.3
		cleancut: CleanCut 1.19.3-5.2-fabric
		clickthrough: ClickThrough 1.19.3-fabric0.68.1-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		cloth-config: Cloth Config v9 9.0.93
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.2.1
			coat: Coat 1.0.0-beta.19+mc1.19.3
			completeconfig-base: completeconfig-base 2.2.1
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.1
			completeconfig-gui-coat: completeconfig-gui-coat 2.2.1
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.2.1
		continuity: Continuity 3.0.0-beta.2+1.19.3
		craftingtweaks: Crafting Tweaks 16.0.1
		deeper_oceans: Deeper Oceans 1.0
		ecologics: Ecologics 2.1.12
		elementa: Elementa 572
		enchdesc: EnchantmentDescriptions 14.0.6
		entity_texture_features: Entity Texture Features 4.3.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		essential: Essential 11794+deploy-staging+g1ba2ff8eb
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		fabric-api: Fabric API 0.72.0+1.19.3
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.19+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.0+b5d379b085
			fabric-block-api-v1: Fabric Block API (v1) 1.0.4+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.29+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.11+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.21+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+3fc4752e85
			fabric-commands-v0: Fabric Commands (v0) 0.2.38+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.46+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.13+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.4+1134c5b885
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.40+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.6+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.39+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.42+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.29+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.8+1134c5b885
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.11+1134c5b885
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.30+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.28+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.9+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.19+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.23+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.13+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.30+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.26+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.16+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.33+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.3.0+85f102ee85
			fabric-particles-v1: Fabric Particles (v1) 1.0.19+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.4+1134c5b885
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.0+9f179aa185
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+9f179aa185
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.29+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.24+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.17+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.32+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+6dc0edd785
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.2+1134c5b885
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.40+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.12+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.7+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.14+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.0+5b9a588b85
		fabric-language-kotlin: Fabric Language Kotlin 1.9.0+kotlin.1.8.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.12
		foodeffecttooltips: Food Effect Tooltips 1.1.1-1.19.3
		forgeconfigapiport: Forge Config API Port 5.0.6
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		freecam: Freecam (Modrinth Edition) 1.1.8+1.19
		iceberg: Iceberg 1.1.4
		iknowwhatimdoing: I Know What I'm Doing 4.1.1
		indium: Indium 1.0.12+mc1.19.3
		inventoryhud: Inventory HUD + 3.4.7
		inventorytabs: Inventory Tabs 0.9.0-beta-1.19.3
		invmove: InvMove 0.8.2
		iris: Iris 1.5.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre8
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		keebsz: Keebsz's Battle Towers 0.4.1
		lambdynlights: LambDynamicLights 2.2.0+1.19.3
			pride: Pride Lib 1.2.0+1.19.3
			spruceui: SpruceUI 4.1.0+1.19.3
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.4.1
		lithium: Lithium 0.10.4
		malilib: MaLiLib 0.14.0
		midnightlib: MidnightLib 1.1.0
		minecraft: Minecraft 1.19.3
		minecraftcapes: MinecraftCapes Mod 12.2.2
		minihud: MiniHUD 0.25.0
		mobhealthbar: MobHealthBar 2.1.2
		modmenu: Mod Menu 5.0.2
		mousewheelie: Mouse Wheelie 1.10.7+mc1.19.3
			amecsapi: Amecs API 1.3.7+mc1.19.3
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.19.3
			tweed4_base: tweed4_base 1.7.1+mc1.19.3
			tweed4_data: tweed4_data 1.2.1+mc1.19.3
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.19.3
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.19.3
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.3+mc1.19.3
		notenoughanimations: NotEnoughAnimations 1.6.2
		optigui: OptiGUI 1.1.6
			org_apache_commons_commons-text: commons-text 1.9
		org_jetbrains_annotations: annotations 13.0
		pathunderfencegates: Path Under Fence Gates 1.3.0
		peek: Peek 1.19.3-1.0.3
		prism: Prism 1.0.4
		puzzle: Puzzle 1.4.2-1.19.3
			puzzle-base: Puzzle Base 1.4.2-1.19.3
			puzzle-gui: Puzzle GUI 1.4.2-1.19.3
			puzzle-models: Puzzle Models 1.4.2-1.19.3
			puzzle-splashscreen: Puzzle Splash Screen 1.4.2-1.19.3
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		replaymod: Replay Mod 1.19.3-2.6.10
		resourcefulconfig: Resourcefulconfig 1.1.2
		resourcefullib: Resourceful Lib 1.2.7
			com_teamresourceful_yabn: yabn 1.0.2
		roughlyenoughitems: Roughly Enough Items 10.0.581
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.2.0
		satin: Satin 1.10.0
		simple-rpc: Simple RPC 3.2.1
			me_hypherionmc_simplerpc_simple-rpc-common: simple-rpc-common 4.2.10
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.3
		sodium: Sodium 0.4.8+build.22
		sodium-extra: Sodium Extra 0.4.17+mc1.19.3-build.95
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		symbol-chat: Symbol Chat 1.19.3-0.6.1
		tcdcommons: TCD Commons API 2.0+1.19.3
		tectonic: Tectonic 1.1.7
		thiccpackets: Extra Thicc Packets 1.17-1.19+
		toolstats: ToolStats 13.0.1
		travelersbackpack: Traveler's Backpack 1.19.3-8.3.2
			reach-entity-attributes: Reach Entity Attributes 2.3.1
		tweakeroo: Tweakeroo 0.15.0
		universalcraft: UniversalCraft 254
		vanilla-notebook: Vanilla Notebook 2.0.0
		vigilance: Vigilance 272
		visuality: Visuality 0.6.0
		waterdripsound: Drip Sounds 1.19-0.3.1
		waveycapes: WaveyCapes 1.2.2
		xaerominimap: Xaero's Minimap 22.17.0
		xaeroworldmap: Xaero's World Map 1.28.7
		yet-another-config-lib: YetAnotherConfigLib 2.2.0
		zoomify: Zoomify 2.9.2
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.3.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.6
	Loaded Shaderpack: ComplementaryShaders_v4.5.1.zip
		Profile: Custom (+31 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.12-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.24, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, continuity:default, continuity:glass_pane_culling_fix, file/Particles+ 1.19.x .zip (incompatible), file/Icons 1.19.x .zip (incompatible), file/Crops-3D 1.19.x .zip (incompatible), file/SimpleHotbar 1.19.x .zip, file/Obscuria's-Tools-1.19.zip (incompatible), file/VanillaTweaks_r709269.zip, file/Crystal_Sculk 1.19.x .zip (incompatible)
	Current Language: English (US)
	CPU: 24x 12th Gen Intel(R) Core(TM) i9-12900K
	Server Running: true
	Player Count: 1 / 8; [class_3222['Gari_756'/3, l='ServerLevel[Solo 2023 NeverEndingStory!]', x=-7837.44, y=108.00, z=2847.40]]
	Data Packs: vanilla, fabric, file/nullscape-v1-2a.zip, file/Amplified-Nether-Data-Pack-1.19.3.zip, file/geophilic-1.19-1.0.1.zip, file/deathpoint-v6-1.zip, bundle, file/New-Desert-Temple.zip (incompatible), file/New-Ruined-Portals.zip (incompatible), file/armored elytra v1.0.6.zip, file/chunk loaders v1.0.4.zip, file/double shulker shells v1.3.3.zip, file/fast leaf decay v2.0.6.zip
	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
	World Generation: Experimental

**Comment by depthbysoul** [comment]
mod author commented on my post abt a week ago abt it is fixed and will release update soon.

been checking daily for it lol. my world has gotten very cluttered

**Comment by AlexNijjar** [comment]
fixed
