### ISSUE TITLE
[Bug]: Can't find cable/pipe in creative tab/JEI

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#183]
### Bug Description

cable, pipe items are surely exist.
but cant found in creative tab and jei.

![image](https://user-images.githubusercontent.com/44163945/218133981-5e598b15-5aae-4aa3-92ea-56e6635a1f14.png)

![image](https://user-images.githubusercontent.com/44163945/218133288-44f4e8e5-9a95-429d-ab3a-1dccc1e8077a.png)

### How to Reproduce?

1. Update Ad-Astra to 1.19.2-1.12.3
2. Join world and search cable/pipe items.

### Version

1.12.3

### Mod Loader Version

1.19.2-43.2.4

### Mod Loader

Forge

**Comment by gisellevonbingen** [comment]
That items looks not assigned ItemGroup. in f6ad92f3c1ac6ec89d18582db0df4ae334ddf041

https://github.com/terrarium-earth/Ad-Astra/blob/f6ad92f3c1ac6ec89d18582db0df4ae334ddf041/common/src/main/java/earth/terrarium/ad_astra/common/registry/ModItems.java#L64-L70

**Comment by AlexNijjar** [comment]
oh, yeah it's because that was backported from 1.19.3 where it doesn't exist any more so I forgot to re-add it to the tabs on 1.19.2

**Comment by AlexNijjar** [comment]
will be fixed in next update
