### ISSUE TITLE
Game freezes when connecting cables

### ISSUE THREAD

**Issue by Rogenar** [terrarium-earth/Ad-Astra#186]
### Bug Description

After I go to the moon, I set up the mechanism to create oxygen there. There was no problem in the first setup, but when connecting other cables, the game freezes, mobs do not move, I cannot switch to game mode and I cannot even open the inventory. Cables won't even connect.

### Version

1.19.3

### Mod Loader Version

1.19.3-1.13.4

### Mod Loader

Fabric

### Logs or additional context

![SS1](https://user-images.githubusercontent.com/122460325/218165973-a88ea09a-70da-4ead-9ad0-7bb497d9285b.png)

**Comment by AlexNijjar** [comment]
can you take a screenshot of the exact setup so I can reproduce it

**Comment by AlexNijjar** [comment]
update to the latest and reopen if it's still happening
