### ISSUE TITLE
[Bug]: Crash when I start minecraft

### ISSUE THREAD

**Issue by Frederich343** [terrarium-earth/Ad-Astra#187]
### Bug Description

When I start Minecraft with other mods the games crash, but when I unistall Ad Astra the game start, all the support mod are istalled

### Version

1.13.4

### Mod Loader Version

1.19.3 - 44.1.16

### Mod Loader

Forge

### Logs or additional context
[2023-02-11-12.log](https://github.com/terrarium-earth/Ad-Astra/files/10713971/2023-02-11-12.log)

**Comment by AlexNijjar** [comment]
send the latest.log

**Comment by Frederich343** [comment]
I have now added it

**Comment by AlexNijjar** [comment]
<img width="1035" alt="Screenshot 2023-02-11 at 9 37 58 AM" src="https://user-images.githubusercontent.com/61668546/218267138-ab961bb9-2a8f-4473-a924-746674a9b3fe.png">
you're missing resourceful lib and resourceful config. check that you have the right version and didn't install the fabric version
