### ISSUE TITLE
[Bug]: Energizer does not store power when broken

### ISSUE THREAD

**Issue by Pancakes33** [terrarium-earth/Ad-Astra#188]
### Bug Description

Fully charged or partially charged energizer when broken loses all charge. no indication of charge level besides LED bar on front.

### How to Reproduce?

place energizer
charge energizer
break energizer

### Expected Behavior

upon breaking energizer it should keep its charge

### Version

1.19.2-1.12.2

### Mod Loader Version

43.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
update to 1.12.3
