### ISSUE TITLE
[Feature Request]: Backport Ad Astra to 1.18.2 FORGE

### ISSUE THREAD

**Issue by yegordeez** [terrarium-earth/Ad-Astra#191]
### Is your feature request related to a problem?

Ad Astra is really better than beyond earth and it also released for forge 1.19, but there are couple of people who needs ad astra on forge 1.18, because of other mods releases.

### Solution(s)

Release ad astra on forge 1.18

### Mod Version

1.13.4

### Mod Loader Version

1.19.3 - 43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
no

**Comment by Anthonity** [comment]
no u

**Comment by Consructor** [comment]
I thought Team Ad Astra were suppose to be the nicer bunch. Apparently not.

**Comment by CodexAdrian** [comment]
> I thought Team Ad Astra were suppose to be the nicer bunch. Apparently not.

We’ve answered this question about 100 times. At this point it’s easier for us just to say no
