### ISSUE TITLE
[Bug]: Fluid Pipe Duct not transferring fluid

### ISSUE THREAD

**Issue by GitCat3** [terrarium-earth/Ad-Astra#192]
### Bug Description

I got the fluid duct from the give command, but it appears that it does not actually transfer fluid (in this case water) from the water pump to the oxygen distributer

### How to Reproduce?

1. place down any block with fluid storage
2. attach a fluid pipe duct to it and pipes from the duct to another block with fluid storage

### Expected Behavior

I expected water to be transferred from my water pump to my oxygen distributer

### Version

1.12.3

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
well the fluid duct isn't a pipe per se. it's meant to be connected to other pipes to seal oxygen and doesn't do anything on its own
