### ISSUE TITLE
[Bug]: placing/using certain block entities causes softlock

### ISSUE THREAD

**Issue by R3venant272** [terrarium-earth/Ad-Astra#193]
### Bug Description

using the energizer, power cables and solar panels for some reason after a short amount of time freezes entities, prevents me from spawning new entities, prevents me for interacting with all block entities (vanilla ones as well), prevents me from changing gamemode and stops the game from generating new chunks. Then when I try to close the game it gets frozen trying to save the game and I have to close it with task manager .not sure if this is relevant but when creating a new world and opening previous ones a warning pops up and says something about the new experimental settings being activated, which I havent activated. that last bit might just be something strange going on with my minecraft but I thought it was worth mentioning. (this was all in creative mode)

### How to Reproduce?

see screenshots bellow as to how exactly i found it, connecting multiple solar panels to the same energy cable seems to cause this bug

### Expected Behavior

using the mods features wouldnt cause a softlock

### Version

1.13.4

### Mod Loader Version

fabric-loader-0.14-1.19.3

### Mod Loader

Fabric

### Logs or additional context

![2023-03-04_14 34 01](https://user-images.githubusercontent.com/125321205/222908427-4f64b0d9-27e5-491b-acff-47ea8d67aa78.png)
![2023-03-04_14 34 13](https://user-images.githubusercontent.com/125321205/222908432-b1ef1416-cbb5-40b9-9ffc-419e8c1aff0e.png)
![2023-03-04_14 33 56](https://user-images.githubusercontent.com/125321205/222908434-55bd68d1-c6d9-4231-aa8a-90c9ba91baa8.png)

just tested it on the forge version too, and now the bug is here, i didnt notice it on this version before. i think its something to do with the energy cables not liking it when multiple power sources are connected to the same cable, ive only noticed it with the solar panels but i also havent tested it with anything else. Also for some reason i cant access the energy cables in the creative inventory or in the jei menu, not sure if this is related.

**Comment by R3venant272** [comment]
ive just realised i downloaded the forge version of patchouli, im not sure if that was the issue but hopefully its solved now lol

**Comment by AlexNijjar** [comment]
can you take a screenshot of the setup so I can reproduce it?

**Comment by R3venant272** [comment]
ive updated the post to be a bit more accurate and added screenshots, hope this helps

**Comment by ThatGravyBoat** [comment]
This is because of #210 which needs to be ported to 1.19.3

**Comment by ThatGravyBoat** [comment]
65b0b19 is the commit that needs to be ported

**Comment by AlexNijjar** [comment]
👍
