### ISSUE TITLE
[Bug]: Disassembling create contraption with desh pipes crashes server

### ISSUE THREAD

**Issue by gittibene** [terrarium-earth/Ad-Astra#195]
### Bug Description

Built create minecart contraption with pump, oxygen loader, distributer. Machines do not assemble with the rest of the contraption, desh pipes do. As soon as the contraption is getting disassembled, the game crashes - and keeps crashing every time i try to connect to the server :(

### How to Reproduce?

1. Built create contraption with ad astra pump and connect desh pipes
2. super glue
3. assemble contraption - pump doesn't assemble, pipes do
4. disassemble contraption
5. game crash
6. game crashes keeps crasheing on login

### Expected Behavior

Machines assemble correctly and don't crash the server

### Version

1.12.3

### Mod Loader Version

1.19.2 Fabric 0.14.14

### Mod Loader

Fabric

### Logs or additional context

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-02-16 06:54:14
Description: Ticking block entity

java.lang.IllegalArgumentException: Cannot get property class_2754{name=down, clazz=class earth.terrarium.ad_astra.common.block.pipe.PipeState, values=[none, normal, insert, extract]} as it does not exist in Block{minecraft:air}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at earth.terrarium.ad_astra.common.block.pipe.PipeBlock.updatePipeState(PipeBlock.java:123)
	at earth.terrarium.ad_astra.common.block.pipe.PipeBlock.method_9559(PipeBlock.java:168)
	at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:980)
	at com.simibubi.create.content.contraptions.components.structureMovement.Contraption.addBlocksToWorld(Contraption.java:1024)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.disassemble(AbstractContraptionEntity.java:659)
	at com.simibubi.create.content.contraptions.components.structureMovement.OrientedContraptionEntity.method_5848(OrientedContraptionEntity.java:156)
	at net.minecraft.class_1297.method_5772(class_1297.java:2011)
	at com.simibubi.create.content.contraptions.components.structureMovement.mounted.CartAssemblerTileEntity.disassembleCart(CartAssemblerTileEntity.java:223)
	at com.simibubi.create.content.contraptions.components.structureMovement.mounted.CartAssemblerTileEntity.disassemble(CartAssemblerTileEntity.java:193)
	at com.simibubi.create.content.contraptions.components.structureMovement.mounted.CartAssemblerTileEntity.tryAssemble(CartAssemblerTileEntity.java:85)
	at com.simibubi.create.content.contraptions.components.structureMovement.mounted.CartAssemblerTileEntity.tick(CartAssemblerTileEntity.java:64)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at earth.terrarium.ad_astra.common.block.pipe.PipeBlock.updatePipeState(PipeBlock.java:123)
	at earth.terrarium.ad_astra.common.block.pipe.PipeBlock.method_9559(PipeBlock.java:168)
	at net.minecraft.class_4970$class_4971.method_26191(class_4970.java:980)
	at com.simibubi.create.content.contraptions.components.structureMovement.Contraption.addBlocksToWorld(Contraption.java:1024)
	at com.simibubi.create.content.contraptions.components.structureMovement.AbstractContraptionEntity.disassemble(AbstractContraptionEntity.java:659)
	at com.simibubi.create.content.contraptions.components.structureMovement.OrientedContraptionEntity.method_5848(OrientedContraptionEntity.java:156)
	at net.minecraft.class_1297.method_5772(class_1297.java:2011)
	at com.simibubi.create.content.contraptions.components.structureMovement.mounted.CartAssemblerTileEntity.disassembleCart(CartAssemblerTileEntity.java:223)
	at com.simibubi.create.content.contraptions.components.structureMovement.mounted.CartAssemblerTileEntity.disassemble(CartAssemblerTileEntity.java:193)
	at com.simibubi.create.content.contraptions.components.structureMovement.mounted.CartAssemblerTileEntity.tryAssemble(CartAssemblerTileEntity.java:85)
	at com.simibubi.create.content.contraptions.components.structureMovement.mounted.CartAssemblerTileEntity.tick(CartAssemblerTileEntity.java:64)
	at com.simibubi.create.foundation.tileEntity.SmartTileEntityTicker.tick(SmartTileEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)

-- Block entity being ticked --
Details:
	Name: create:cart_assembler // com.simibubi.create.content.contraptions.components.structureMovement.mounted.CartAssemblerTileEntity
	Block: Block{create:cart_assembler}[backwards=true,powered=false,rail_type=regular,shape=north_south,waterlogged=false]
	Block location: World: (-242,84,-356), Section: (at 14,4,12 in -16,5,-23; chunk contains blocks -256,-64,-368 to -241,319,-353), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Block: Block{create:cart_assembler}[backwards=true,powered=false,rail_type=regular,shape=north_south,waterlogged=false]
	Block location: World: (-242,84,-356), Section: (at 14,4,12 in -16,5,-23; chunk contains blocks -256,-64,-368 to -241,319,-353), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:660)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:714)
	at net.minecraft.class_1937.method_18471(class_1937.java:456)
	at net.minecraft.class_3218.method_18765(class_3218.java:376)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['DrCumberBen'/1642, l='ServerLevel[NewestWorld]', x=-245.71, y=83.00, z=-354.58]]
	Chunk stats: 7048
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,165,0), Section: (at 0,5,0 in 0,10,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 273891750 game time, 60395796 day time
	Level name: NewestWorld
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 92486 (now: false), thunder time: 57115 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.class_3176.method_3813(class_3176.java:289)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.4.0-139-generic
	Java Version: 17.0.1, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 6069231288 bytes (5788 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Integrated Matrox G200eW3 Graphics Controller
	Graphics card #0 vendor: Matrox Electronics Systems Ltd. (0x102b)
	Graphics card #0 VRAM (MB): 16.00
	Graphics card #0 deviceId: 0x0536
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 184273.55
	Virtual memory used (MB): 126815.53
	Swap memory total (MB): 120000.00
	Swap memory used (MB): 19057.75
	JVM Flags: 20 total; -Xms8192M -Xmx8192M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		ad_astra: Ad Astra 1.12.3
		ad_astra_giselle_addon: Ad Astra!: Giselle Addon 1.12
		adorn: Adorn 3.7.0+1.19.2
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.17
		ae2: Applied Energistics 2 12.8.5
		architectury: Architectury 6.3.56
		artifacts: Artifacts 7.1.1+fabric
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 17.1.3
		automobility: Automobility 0.4.1+1.19.2-fabric
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			jsonem: JsonEM 0.1.2+1.19
		awesomedungeon: Awesome dungeon 3.0.0
		awesomedungeonend: Awesome dungeon the end 3.0.0
		awesomedungeonnether: Awesome dungeon nether 3.0.0
		awesomedungeonocean: Awesome dungeon edition ocean 3.0.1
		balm-fabric: Balm 4.5.2+0
		bclib: BCLib 2.1.5
		betteranimalsplus: Better Animals Plus 1.19.2-11.0.10
		betterbeds: Better Beds 1.2.0
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betternether: Better Nether 7.1.2
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.6-1.19.2
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		botarium: Botarium 1.8.2
		brewinandchewin: Brewin And Chewin fabric-1.0.5+1.19.2
		buildinggadgets: st'ructure tools 1.0.30
			cardinal-components-item: Cardinal Components API (items) 5.0.0-beta.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
			mm: Manningham Mills 2.3
		byg: Oh The Biomes You'll Go 2.0.0.7
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chisel: Chisel Refabricated 1.4.5
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		collective-fabric: Collective (Fabric) 5.16
			fiber: fiber 0.23.0-2
		create: Create 0.5.0.i-946+1.19.2
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			milk: Milk Lib 1.0.51
				dripstone_fluid_lib: Dripstone Fluid Lib 2.0.1
			porting_lib: Porting Lib 2.1.766+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.766+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.766+1.19.2
				porting_lib_base: Porting Lib Base 2.1.766+1.19.2
				porting_lib_common: Porting Lib Common 2.1.766+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.766+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.766+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.766+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.766+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.766+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.766+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.766+1.19.2
				porting_lib_models: Porting Lib Models 2.1.766+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.766+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.766+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.766+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
			registrate-fabric: Registrate for Fabric 1.1.50-MC1.19.2
		createaddition: Create Crafts & Additions 20230211a
		createchunkloading: Create Chunkloading 1.3.0
		createdeco: Create Deco 1.2.12-1.19.2
		creeperoverhaul: Creeper Overhaul 2.0.5
		crittersandcompanions: Critters and Companions 1.19.2-1.0.2
		croptopia: Croptopia 2.1.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		culturaldelights: Cultural Delights Fabric 0.14.9+1.19.2
		deeperdarker: Deeper and Darker 1.1.4
			customportalapi: Custom Portal Api 0.0.1-beta54-1.19
			paragon: Paragon 1.0.3
		delightchef: Chef's Delight 1.0.1-1.19.2
			structurized-reborn: Structurized Reborn 1.19-01
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.3.5_1
		ecologics: Ecologics 2.1.10
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		fabric-api: Fabric API 0.73.2+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.13
		factory_blocks: Factory Blocks Mod 1.0.1+1.19
		fallingtree: FallingTree 3.10.0
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmersknives: Farmer's Knives 2.2
		ferritecore: FerriteCore 5.0.3
		fishofthieves: Fish of Thieves 2.1.0-rc4
		forgivingvoid: Forgiving Void 7.0.0
		friendsandfoes: Friends&Foes 1.6.8
			com_github_llamalad7_mixinextras: MixinExtras 0.1.1
		fwaystones: Fabric Waystones 3.0.5+mc1.19.2
		geckolib3: Geckolib 3.1.37
			com_eliotlash_mclib_mclib: mclib 20
		graveyard: The Graveyard 2.3
		graveyard_biomes: The Graveyard Biomes 1.6
			omega-config: OmegaConfig 1.2.2-1.18.1
		iceberg: Iceberg 1.0.46
		indypets: IndyPets - Independent Pets 1.1.0-1.19.2
		inventoryessentials: Inventory Essentials 5.0.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		laserbridges: LaserBridges 1.19.2-0
		lazydfu: LazyDFU 0.1.3
		libraryferret: Library ferret 3.0.0
		lithium: Lithium 0.10.4
		mca: Minecraft Comes Alive 7.4.0+1.19.2
		mcwbridges: Macaw's Bridges 2.0.5
		mcwdoors: Macaw's Doors 1.0.7
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.2.1
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		mcwwindows: Macaw's Windows 2.1.0
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		minecraft: Minecraft 1.19.2
		mobscarecrow: Mob Scarecrow 2.2.1-1.19.1
		moonlight: Moonlight 1.19.2-2.2.6
		moreleads: Moreleads 1.19.2-1.0.0
		mythicmounts: Mythic Mounts 1.19.2-7.1
		nethersdelight: Nether's Delight 1.0.0
			forgeconfigapiport: Forge Config API Port 4.2.9
				com_electronwill_night-config_core: core 3.6.5
				com_electronwill_night-config_toml: toml 3.6.5
		notenoughbreeding: Not Enough Breeding 1.19.2-1.0.0-fabric
		openpartiesandclaims: Open Parties and Claims 0.16.4
		overpoweredmending: OverpoweredMending 2.8.2
		owo: oωo 0.8.2+1.19
			blue_endless_jankson: jankson 1.2.1
		oxidized: Oxidized 1.7.2
		patchouli: Patchouli 1.19.2-76-FABRIC
		quarryplus: QuarryPlus 19.1.672
		reborncore: Reborn Core 5.4.0
		resourcefulconfig: Resourcefulconfig 1.0.17
		resourcefullib: Resourceful Lib 1.1.19
		respawnablepets: Respawnable Pets 1.19-2
		rocks: This Rocks! 1.6.1
			midnightlib: MidnightLib 0.5.2
		rottencreatures: Rotten Creatures 1.0.1
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		roughlyenoughitems: Roughly Enough Items 9.1.574
			error_notifier: Error Notifier 1.0.9
		smoothchunk: Smooth chunk save Mod 1.19.1-2.0
		smwyg: Show Me What You Got 1.0.3
		spark: spark 1.9.45
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		supplementaries: Supplementaries 1.19.2-2.2.46
		t_and_t: Towns and Towers 1.10
		tawct: Time & Wind Custom Ticker 1.4.3+1.19.2
		techreborn: Tech Reborn 5.4.0
			team_reborn_energy: Energy 2.3.0
		terrablender: TerraBlender 2.0.1.130
		terralith: Terralith 2.3
		timeoutout: TimeOut Out 1.0.3+1.19.1
		travelersbackpack: Traveler's Backpack 1.19.2-8.2.12
		trinkets: Trinkets 3.4.1
		vinery: Vinery 1.1.4
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		voidz: VoidZ 1.0.9
		windchimes: Windchimes 1.2.1
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		wondrouswilds: Wondrous Wilds 1.19.2-1.1.5
		wunderreich: Wunderreich 3.0.18
		xaerominimap: Xaero's Minimap 22.17.0
		xaeroworldmap: Xaero's World Map 1.28.7
		xps: Xp Obelisk 0.4.7-r+1.19.2-Fabric
		yigd: You're in Grave Danger 1.4.6
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.2
			org_javassist_javassist: javassist 3.28.0-GA
			org_reflections_reflections: reflections 0.10.2
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Server Running: true
	Player Count: 1 / 4; [class_3222['DrCumberBen'/1642, l='ServerLevel[NewestWorld]', x=-245.71, y=83.00, z=-354.58]]
	Data Packs: vanilla, Fabric Mods, file/Chunk-Loader-Datapack.zip, Supplementaries Generated Pack
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by AlexNijjar** [comment]
will be fixed in next update
