### ISSUE TITLE
[Feature Request]: Add an option to prevent the player from being attacked while in the rocket

### ISSUE THREAD

**Issue by thehobojoe** [terrarium-earth/Ad-Astra#199]
### Is your feature request related to a problem?

Players on my server are very frequently dying to hostile mobs while in the rocket. During landing you are incapable of defending yourself or dodging attacks, and during liftoff the rocket countdown is locked-in and uncancellable, so if you exit the rocket to defend yourself you will be left behind

### Solution(s)

Make it so the player cannot be attack while inside the rocket, either as a basic mod change or as a config option.

### Mod Version

1.13.4

### Mod Loader Version

1.19.2-0.14.14

### Mod Loader

Fabric

**Comment by username90001** [comment]
> ### Is your feature request related to a problem?
> Players on my server are very frequently dying to hostile mobs while in the rocket. During landing you are incapable of defending yourself or dodging attacks, and during liftoff the rocket countdown is locked-in and uncancellable, so if you exit the rocket to defend yourself you will be left behind
> 
> ### Solution(s)
> Make it so the player cannot be attack while inside the rocket, either as a basic mod change or as a config option.
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Mod Version
> 1.13.4
> 
> ### Mod Loader Version
> 1.19.2-0.14.14
> 
> ### Mod Loader
> Fabric
> 
> ### Additional context
> _No response_

man just tell them to do fence or wall
