### ISSUE TITLE
Pipes not transferring oxygen correctly

### ISSUE THREAD

**Issue by HexBugOrion** [terrarium-earth/Ad-Astra#20]
Not sure if there's a thing I'm missing though

**Comment by AlexNijjar** [comment]
Are you trying to extract it from an oxygen loader or similar machine? It only supports fluid insertion, not extraction at the moment. I'll work to make it extractable as well, though.

**Comment by HexBugOrion** [comment]
Extracting it from the thing that makes oxygen I think

**Comment by AlexNijjar** [comment]
Fixed in the latest 1.19.2 update
