### ISSUE TITLE
[Bug]: Can't make a space station

### ISSUE THREAD

**Issue by FLSM777** [terrarium-earth/Ad-Astra#200]
### Bug Description

Hey, as i said. I can't make a space station on my server with this mod even tho i have all of the required materials to build one.

### Version

ad_astra-fabric-1.19.2-1.12.3

### Mod Loader Version

0.14.12

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
so it's saying you have the required materials but when you click on the space station button it does nothing?
