### ISSUE TITLE
[Bug]: Glacian wood biome is not generating

### ISSUE THREAD

**Issue by ghost** [terrarium-earth/Ad-Astra#201]
### Bug Description

The wood that is supposed to generate on planet glacio is not generating. Only flat biomes and ice peak biomes are generating.

### Expected Behavior

Wood should generate

### Version

ad_astra-fabric-1.19.2-1.12.2

### Mod Loader Version

fabric-api-0.72.0+1.19.2

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
the wood isn’t added yet; it’s creative-only for now
