### ISSUE TITLE
[Feature Request]: Allow to eat when in a rocket

### ISSUE THREAD

**Issue by zeid0ne** [terrarium-earth/Ad-Astra#202]
### Is your feature request related to a problem?

I cant eat when i am in a rocket.

### Solution(s)

Allow to eat inside a rocket.

### Mod Version

1.19.2-1.12.3

### Mod Loader Version

1.19.3 - 0.14.14

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
well when ur inside the rocket, your right-click interaction will always be the rocket interaction so I don't think you can right-click to eat food at the same time. we are changing the way rockets work tho so maybe in a future update it'll be possible
