### ISSUE TITLE
[Bug]: Incompatibility with the waystone mods

### ISSUE THREAD

**Issue by tbvns2** [terrarium-earth/Ad-Astra#203]
### Bug Description

When you teleport yourself on a planet with a waystone, the gravity and all the sound effecte doesn't work properly.

### How to Reproduce?

1. Uses Ad Astra and the [Waystone](https://www.curseforge.com/minecraft/mc-mods/waystones) mods.
2. Teleport to a planet or a space station.
3. Jump
4. Be not affected by gravity.

This doesn't work each time, but when it happens, it won't stop until you use a rocket to go back where the way stone is.

### Expected Behavior

The gravity and the sound effect should work as intended  

### Version

1.12.1

### Mod Loader Version

1.19.2 43.2.4

### Mod Loader

Forge

### Logs or additional context

I don't know how you detect when to apply the gravity, but I think you should check when a player is entering a new dimension, and if this dimension has gravity, then change it. This is just an idea on how to fix this issue, but I really think this will work.

Also, there are no errors in the log.

**Comment by AlexNijjar** [comment]
update to the latest version
