### ISSUE TITLE
[Bug]: Z fighting with hopper and Cryo Freezer

### ISSUE THREAD

**Issue by zeid0ne** [terrarium-earth/Ad-Astra#204]
### Bug Description

![image](https://user-images.githubusercontent.com/38461940/220158986-09fb05d1-51d0-43c9-ab51-9b303c8645d2.png)

### How to Reproduce?

Put an hopper on top of a Cryo Freezer

### Expected Behavior

There is no Z fighting 

### Version

1.19.2-1.12.3

### Mod Loader Version

1.19.3 - 0.14.14

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
the model is larger than one block so yeah that makes sense. just don't place a hopper on top of it I guess? the model is being changed in the future anyway
