### ISSUE TITLE
[Bug]: Waterlogging in space station

### ISSUE THREAD

**Issue by mthp1999** [terrarium-earth/Ad-Astra#205]
### Bug Description

In the newest update blocks get waterlogged whenever placed in a space station

### How to Reproduce?

1. Go to space station
2. Place waterlogg-able block
3. It will be waterlogged when it shouldn't be
![image](https://user-images.githubusercontent.com/12549239/220563812-0e822f3c-bbe9-48ad-bad4-689b1dc7ac3b.png)

### Expected Behavior

Blocks shouldn't waterlog

### Version

1.12.3

### Mod Loader Version

1.19.2- 43.2.3

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
what block is that? I'm trying with stairs and it's working fine

**Comment by AlexNijjar** [comment]
if ur still experiencing this on the latest version reopen the issue. as I said I can't reproduce it and it appears that block is from a very specific mod
