### ISSUE TITLE
[Bug]: POWER SYSTEM BROKEN

### ISSUE THREAD

**Issue by username90001** [terrarium-earth/Ad-Astra#206]
### Bug Description

i tried connect coal generator to fuel refinery it didnot worked after i found that i need desh wrench so i used creative to get it
still dont work
GAME UNPLAYABLE i even tried solar panels and other cables and also wrench needs desh that as i remember from gc is from mars

### How to Reproduce?

1 do any source of energy
2 try use cables
3 realize to conenct things u need wrench that needs desh that needs spacetravel that needs desh
4 power dont work or conduct
5 leave game
6 remove mod and return to 1.12.2 

### Expected Behavior

cables are broken + u need desh for wrench so only way to play is use creative for fuel and desh

### Version

Feb 10, 2023

### Mod Loader Version

1.19.3 - 44.1.17

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
remove optifine

**Comment by username90001** [comment]
> remove optifine

thank u
