### ISSUE TITLE
[Bug]: Mod ignores hammerDurability changes

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [terrarium-earth/Ad-Astra#207]
### Bug Description

I've set hammerDurability to 128 in the config file, yet it doesn't actually change anything, and it stays at 64.

### How to Reproduce?

1. Change hammerDurability to 128 (or any other value).
2. Boot the game, log into your world (or create a new one)
3. Try to craft a stack of plates
4. Hammer breaks, which means the durability is unchanged

### Expected Behavior

Being able to change the durability.

### Version

1.12.3

### Mod Loader Version

1.19.2 - 43.2.4

### Mod Loader

Forge

### Logs or additional context

This was tested on a completely clear CurseForge profile, so this is not some compatibility issue.

**Comment by ThatGravyBoat** [comment]
Are you restarting after you change it?

**Comment by pPkMnh4to8994h** [comment]
> Are you restarting after you change it?

Yeah.

**Comment by pPkMnh4to8994h** [comment]
Just tried this on a 1.19.3, the issue is also there.
