### ISSUE TITLE
[Bug]: Kicked from lander as soon and dimension loads

### ISSUE THREAD

**Issue by Pancakes33** [terrarium-earth/Ad-Astra#209]
### Bug Description

After choosing which planet to land on I am instantly kicked from the lander. I get killed from falling and the lander explodes.
This happens on all planets and the moon.

### How to Reproduce?

1. Launch Rocket
2. Select destination
3. kicked from lander

### Expected Behavior

I should be able to ride the lander down to the surface

### Version

1.19.3-1.13.4

### Mod Loader Version

44.1.17

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
do you have https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway

**Comment by Pancakes33** [comment]
> do you have https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway

Yes I do have that installed. Is there a fix? Do I need to remove that mod?

**Comment by AlexNijjar** [comment]
yeah you gotta remove it. I don't know what they do but it kicks you out of the lander with that mod installed
