### ISSUE TITLE
{SUGGESTION} Oxygen and electricity storage blocks

### ISSUE THREAD

**Issue by HexBugOrion** [terrarium-earth/Ad-Astra#21]
Name says it all

**Comment by Lego245** [comment]
i think this suggestion is quite good and we might considering it into the mod soon

**Comment by AlexNijjar** [comment]
This is planned

**Comment by phiphila** [comment]
Great 😊
    I only have this mod and I can't store the energy produced with the coal generator and the solar panel, and moreover the coal generator continues to burn coals even when the internal energy storage is full... it is not convenient...
