### ISSUE TITLE
[Bug]: Solar Panels Crash Server

### ISSUE THREAD

**Issue by PolyframeX** [terrarium-earth/Ad-Astra#210]
### Bug Description

When Playing Ad Astra, Placing Two Solar Panels Adjacent To Each Other, The Server Crashes.

### How to Reproduce?

1. Use A Server
2. Place 2 Solar Panels Next To Each Other
3. Game Will Eventually Crash

### Expected Behavior

The Solar Panels Should Function Properly And Not Crash The Server.

### Version

1.12.3

### Mod Loader Version

0.14.14

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/FK747L4h
Crash Log

**Comment by CodexAdrian** [comment]
How did you place 2 solar panels next to each other? Solar panels do not allow you to place them next to each other

**Comment by PolyframeX** [comment]
After some more testing the game crashes when doing any of these setups:

![image](https://user-images.githubusercontent.com/80133652/221461313-75ba5ec2-562b-4bb7-9ea0-1a0a63b99db2.png)

**Comment by CodexAdrian** [comment]
So crashes with 2 solar panels in world? Just 1 solar panel does not cause this issue?

**Comment by PolyframeX** [comment]
A single solar panel does not have the issue, but multiple do.

**Comment by PolyframeX** [comment]
It is also exclusive to a server.
