### ISSUE TITLE
[Feature Request]: Upgranding Oxygen distributor

### ISSUE THREAD

**Issue by RafaelSSchneider** [terrarium-earth/Ad-Astra#211]
### Is your feature request related to a problem?

I am making a space station to make my base there, and i put some oxygen distributor thinking it will increase how many blocks they can distribute the oxygen, but they don't increase, and i dont have any form to upgrade the producing oxygen and distribution, so my idea is to add an item to upgrade the machines to produce and cover more 

### Mod Version

1.12.3

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
the oxygen distributor can be very performance-intensive as it has to check thousands of blocks every few seconds so increasing the range is not something we'd like to do. However you can increase the check rate and maximum blocks in the config if you got a beefier server
