### ISSUE TITLE
[Feature Request]: Allow The Jet Suit To Be Toggleable

### ISSUE THREAD

**Issue by PolyframeX** [terrarium-earth/Ad-Astra#213]
### Is your feature request related to a problem?

It is very annoying to navigate with a Jet Suit because typically players will try to sprint jump, but when doing so, it will launch them, this is especially annoying when your walking a small distance and get launched farther.

### Solution(s)

Make it where a certain keybind toggles the jet suits flight ability. This will make it useful for land and air.

### Describe alternatives you've considered

Another alternative is making it where there are diffrent modes, such as off, hover, elytra. Etc;

### Mod Version

1.12.3

### Mod Loader Version

0.14.15

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
Added in 1.15.7
