### ISSUE TITLE
[Bug]: no dimensions at initial load w/ immersive protals

### ISSUE THREAD

**Issue by AlienXtream** [terrarium-earth/Ad-Astra#214]
### Bug Description

when creating a new world with immersive portals loaded the dimensions do not initially exist and thus can not be traveled to. relaunching the server/client resolves this issue.

### How to Reproduce?

create new world.
load rocket or perform "/execute in <dimension>"

### Version

1.19.2-1.12.3

### Mod Loader Version

43.2.6

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
Immersive portals breaks everything; you should not be using it with other mods.
