### ISSUE TITLE
[Bug]: Coal Generator Doesn't Power Plate Compressor

### ISSUE THREAD

**Issue by ghost** [terrarium-earth/Ad-Astra#216]
### Bug Description

I tried a hundred different ways and no matter what, the Coal Generator does not power the Plate Compressor. The Coal Generator powers when I put coal inside but does not send power to the Compressor.

### How to Reproduce?

1.Place powered Coal generator next to plate Compressor
2.It doesn't work.

### Expected Behavior

Power for the plate compressor when they are next to each other.

### Version

1.13.4

### Mod Loader Version

44.1.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
do you have optifine

**Comment by ghost** [comment]
Yes, is that an issue?

**Comment by AlexNijjar** [comment]
yes it breaks fluid and energy interaction for many mods

**Comment by ghost** [comment]
Alright, thank you.
