### ISSUE TITLE
[Bug]: Planet catalogue dissapears when scrolling

### ISSUE THREAD

**Issue by martinscout** [terrarium-earth/Ad-Astra#223]
### Bug Description

Planet catalogue dissapears when one of the planets in the list is created by a datapack when scrolling a bit too far down or up

<img width="214" alt="Skjermbilde 2023-03-06 190855" src="https://user-images.githubusercontent.com/78684735/223194592-89e12cbc-cc82-4e72-afeb-fb5ed7c88492.png">

### How to Reproduce?

1. add an extra planet datapack to the datapack folder
2. launch rocket
3. catalogue opens with all the planets, one of them being from the datapack
4. scroll further than the length of the list and the list suddenly dissapears 

### Version

1.13.3

### Mod Loader Version

1.19.3-44.1.21

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
can you send the data pack so I can test it

**Comment by martinscout** [comment]
[ad_astra_extra_planets.zip](https://github.com/terrarium-earth/Ad-Astra/files/10941146/ad_astra_extra_planets.zip)
does that work? This one requires twilight forest

**Comment by AlexNijjar** [comment]
seems to be a 1.19.3 specific issue because I can't reproduce it on the 1.19.2 version

**Comment by martinscout** [comment]
I was gonna play on 1.19.2 from now on anyways, but yeah interesting. Thanks
