### ISSUE TITLE
[Bug]: Outdated Ore Textures

### ISSUE THREAD

**Issue by HexBugOrion** [terrarium-earth/Ad-Astra#224]
### Bug Description

I found that the moon ore textures are outdated

### How to Reproduce?

1. Launch game with Ad Astra
2. Go to the moon and find / place the moon ores

### Expected Behavior

The textures should match the color of the surrounding moon stone

### Version

1.12.4

### Mod Loader Version

1.19.3-0.14.14

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
fixed
