### ISSUE TITLE
[Bug]: Space Stations not saving

### ISSUE THREAD

**Issue by zurgeg** [terrarium-earth/Ad-Astra#225]
### Bug Description

Whenever I build anything on any space station, leave, and come back, I see it all is wiped.

### How to Reproduce?

1. Launch a rocket to any station in Creative Mode
2. Build anything
3. Go somewhere off the station
4. Go back, jack, do it again
5. Notice that it is wiped.

### Expected Behavior

I intended for the building to still be there

### Version

1.12.2

### Mod Loader Version

MC 1.19.2 - 0.14.17

### Mod Loader

Fabric

**Comment by CodexAdrian** [comment]
What other mods do you have in your modlist? We haven't noticed that behavior in Vanilla Ad Astra

**Comment by zurgeg** [comment]
> What other mods do you have in your modlist? We haven't noticed that behavior in Vanilla Ad Astra

- Adorn 3.81+1.19.2
- Applied Energistics 2 12.9.2
- Botarium 1.8.2
- Create 0.5.0.i-961+1.19.2
- Create Crafts & Additions 
- Fabric API 0.75.1+1.19.2
- Fabric Language Kotlin 1.9.1+kotlin.1.8.10
- Fabric Waystones 3.0.5+mc1.19.2
- owo 0.8.2+1.19
- Resourceful Lib 1.1.19 & 1.1.21 (I'll try with 1.1.21 only)
- Resourcefulconfig 1.0.19
- Sandwhichable 1.3a+1.19

I should note that, as far as I know, none of these mods interface with Ad Astra (other than the libmods used by it)

**Comment by zurgeg** [comment]
Just tried with Resourceful 1.1.21 only, still not saving.

**Comment by zurgeg** [comment]
I figured out that I wasn't going to the same station every time... Is there a way to control which station that the rocket lands on?

**Comment by AlexNijjar** [comment]
it's based on the launch coords

**Comment by zurgeg** [comment]
> it's based on the launch coords

Ah. Is there a way to figure out where the rocket will land? Thanks though.

**Comment by AlexNijjar** [comment]
it will land in the exact coords that you launch. so if you launch at (100, 100), your space station will spawn at (100, 100) and you will land at (100, 100) in orbit

**Comment by zurgeg** [comment]
> it will land in the exact coords that you launch. so if you launch at (100, 100), your space station will spawn at (100, 100) and you will land at (100, 100) in orbit

Ah. Does it spawn a new station every time? Because I noticed it spawns a station on top of the other one

**Comment by AlexNijjar** [comment]
yes, it will override the current space station. it's currently an issue we have to fix #139

**Comment by zurgeg** [comment]
Great, thanks
