### ISSUE TITLE
[Bug]: game crashed

### ISSUE THREAD

**Issue by caterpillarrex** [terrarium-earth/Ad-Astra#227]
### Bug Description

i broke an oxygen dispense and the game crashed

### How to Reproduce?

break the oxygen dispense well in space station idk if need max oxygen or if the wires and pipes being connect brake some thing

### Expected Behavior

broke oxygen dispense game crashed

### Version

1.19.2

### Mod Loader Version

forge 1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
send the log

**Comment by AlexNijjar** [comment]
try latest
