### ISSUE TITLE
[Bug]: Oxygen distributor working despite open space and water not freezing on the moon

### ISSUE THREAD

**Issue by ItsRBus** [terrarium-earth/Ad-Astra#228]
### Bug Description

https://imgur.com/a/kebViEM

### Version

1.12.4

### Mod Loader Version

1.19.2 43.2.6

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
the oxygen distributor allows there to be open space. it just works inefficiently by draining energy and oxygen a lot faster. the water not freezing is an issue tho
