### ISSUE TITLE
[Feature Request]: Make it harder or not possible to dismount Rocket in transit

### ISSUE THREAD

**Issue by trunksbomb** [terrarium-earth/Ad-Astra#235]
### Is your feature request related to a problem?

One press of the Shift key and you're out of the Rocket, no matter where it's at. If sufficiently high up, this can kill the player via fall damage.

### Solution(s)

Maybe a "Hold shift" to dismount? Or preventing dismount entirely? I'm not sure why (other than funny "rocket go boom" antics) you would want to leave the Rocket while it's in flight.

### Describe alternatives you've considered

N/A

### Mod Version

1.12.3

### Mod Loader Version

1.19.2-0.14.17

### Mod Loader

Fabric

**Comment by MissPotato** [comment]
I second this. I don't even really understand why shift ejects you out of vehicles in vanilla to begin with...

**Comment by AlexNijjar** [comment]
in a recent update, you now have to hold down shift for 2 seconds to dismount
