### ISSUE TITLE
[Bug]: No way to make Oxygen Tanks

### ISSUE THREAD

**Issue by NotChico** [terrarium-earth/Ad-Astra#238]
### Bug Description

Playing through the mod, everything seems to be working as intended, but I don't seem to have Iron Rods, which I believe are used to make the Oxygen Tanks. 

Have they been removed from the game? Or how do I go about making oxygen tanks on my modpack?

Using v1.12.5 on Fabric 1.19.2.

### Version

1.12.5

### Mod Loader Version

1.19.2 Fabric 0.14.17

### Mod Loader

Fabric

**Comment by NotChico** [comment]
So just an update, actually doing the recipe's to make the item seems to work, just a weird incompatibility with JEI, not showing recipes for certain items and straight up not showing that Iron Rods are in the game.

**Comment by AlexNijjar** [comment]
it may be a recipe conflict with other mods because it's working fine for me
<img width="223" alt="Screenshot 2023-03-21 at 11 35 06 AM" src="https://user-images.githubusercontent.com/61668546/226678394-52e2885b-6be4-47b9-8cdf-635e6c0e7d45.png">
