### ISSUE TITLE
[Bug]: Game Crashes From Rendering Entity

### ISSUE THREAD

**Issue by PolyframeX** [terrarium-earth/Ad-Astra#239]
### Bug Description

The game will randomly crash whilst rendering an entity from Ad Astra. It seems to be linked to space suits, specifically the jet suit, and a potential flywheel incompatibility?

### How to Reproduce?

Unknown Cause For Crash, Cannot Reproduce.

### Expected Behavior

Game Should Not Crash.

### Version

1.12.5

### Mod Loader Version

0.14.17

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/EDzQbNCp

**Comment by AlexNijjar** [comment]
did you change the config in any way? and how often is this happening?

**Comment by PolyframeX** [comment]
The only thing I changed in the config is the speed and amount of battery for the jet suit, that was it, this happens semi often, every couple of hours or so it will randomly crash, even when I am doing nothing.
