### ISSUE TITLE
[Bug]: Distributer doesnt let me have more than 2000 blocks of oxygen

### ISSUE THREAD

**Issue by SkyMZ** [terrarium-earth/Ad-Astra#240]
### Bug Description

I have edited my configs so that the Oxygen Distributer will let me have bases with over 2k blocks inside. But when I try to use the 1 distributor it still only lets me have 2k blocks of oxygenated air. I built a dome so having multiple Distributers is not practical as it would require a bunch of floating Distributers that would clutter up the dome ruining my idea.

### Version

1.12.4

### Mod Loader Version

1.19.2 43.2.6

**Comment by AlexNijjar** [comment]
update to the latest version
