### ISSUE TITLE
[Bug]: Coal Generator and Fuel Refinery don't work in 1.19.2 !

### ISSUE THREAD

**Issue by Sympathix** [terrarium-earth/Ad-Astra#241]
### Bug Description

Hello, 
The energy from the coal generator  don't want to get over to the fuel refinery so I can not produce any fuel for my rocket. Please fix that problem for 1.19.2. By the way, this bug only exists in 1.19.2

### Version

1.12.5

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
do you have optifine

**Comment by Sympathix** [comment]
yes i have


Am Mi., 15. März 2023 um 17:55 Uhr schrieb Alex Nijjar <
***@***.***>:

**Comment by AlexNijjar** [comment]
Optifine breaks energy and fluids of many mods including ad astra. please do not use it

**Comment by Sympathix** [comment]
Thank you!

Alex Nijjar ***@***.***> schrieb am Mi. 15. März 2023 um
17:57:
