### ISSUE TITLE
[Bug]: Netherrite Space Suit Textures Broken

### ISSUE THREAD

**Issue by NsCones** [terrarium-earth/Ad-Astra#247]
### Bug Description

I was playing the most recent version of the mod and when i crafted the netherrite space suit its texture didn't show up except the visor on the helmet and no matter what i try like reinstalling the mod, repairing the profile on Curseforge or reinstalling MC entirely
 Nothing worked.

Also i didn't have any optimization mods enabled like sodium or optifine nor did i have Resource packs enabled.

![2023-03-16_21 47 48](https://user-images.githubusercontent.com/101743431/225749345-ac32862a-62d7-4c48-b70d-8106f1c7ea75.png)

### Version

1.12.5

### Mod Loader Version

1.19.2 - 0.14.14

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
fixed in 6c629fc
