### ISSUE TITLE
[Bug]: My Lander landed on a Launch Pad, broke it, and then despawned

### ISSUE THREAD

**Issue by aaronhowser1** [terrarium-earth/Ad-Astra#248]
### Bug Description

![image](https://user-images.githubusercontent.com/15698722/225850423-b0231a9b-9688-4d05-9c05-3499a0e29684.png)

My satellite is just like this. I went to the moon and then came back, and landed directly on top of the Launch Pad as expected.

I was kicked from the Lander, the Launch Pad broke, and the Lander disappeared. Now I have no Rocket to get back in.

I did this all in creative, but would that be a factor? I didn't have a full inventory or anything, so I shouldn't have voided the items or anything.

### Version

ad_astra-forge-1.19.2-1.12.5

### Mod Loader Version

1.19.2 - 43.2.6

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
did you hold down space? if you hit the ground too hard your lander will explode so you need to hold space to soften the landing

**Comment by aaronhowser1** [comment]
I did, there wasn't an explosion and no blocks besides the launch pad broke. There was no sound either. It was kind of like when falling sand lands on a torch and breaks.

**Comment by AlexNijjar** [comment]
weird, I just tested it and the lander landed normally and I was able to obtain the rocket item
![2023-03-21_12 12 01](https://user-images.githubusercontent.com/61668546/226689170-9350c0eb-b50b-4c3e-b0e7-3686ab443806.png)
![2023-03-21_12 12 15](https://user-images.githubusercontent.com/61668546/226689175-b94eeeb8-ecf1-4a30-ba19-f7f98b354a96.png)
