### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SirButterNips** [terrarium-earth/Ad-Astra#249]
### Bug Description

I'm attempting to build a space station. While setting up oxygen I keep getting a bug where my oxygen distributers are filling with water without using a water pump and using a ton of power. I set the distributer down and power it for it to fill up by its self.

### Version

ad_astra-fabric-1.19.2-1.12.3.jar

### Mod Loader Version

Dreamcraft 1.19.2 V8-1.0.36

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
can you take a screenshot of your setup?

**Comment by AlexNijjar** [comment]
should be fixed
