### ISSUE TITLE
[Feature Request]: Create Compatibility 

### ISSUE THREAD

**Issue by ghost** [terrarium-earth/Ad-Astra#250]
### Is your feature request related to a problem?

The only way to automatically farm metal plates from Ad Astra in Create is to use a mixer and a hammer which is really weird because of the existence of mechanical presses. Also crushing, washing or blasting don't have the benefit of possible secondary drops. Processing those ores is just smelting them with extra steps. In addition, wrench and pipe compatibility would be a dream of mine. However, pipe therefore fluid compatibility should be hard to implement while wrench compatibility should be relatively easy (sidenote: please change the texture of the wrench, everything in Ad Astra looks so we'll designed and polishes, but the wrench is horrific).

### Solution(s)

-Being able to create various metal plates from Ad Astra with the mechanical press
-Being able to process Ad Astra ores with the crushing wheels, washing and blasting fan and therefore add secondary drops when processed
-Using Create's pipes in Ad Astra machines and vice versa
-New texture and behavior for the wrench 

### Describe alternatives you've considered

Like I said using the hammer and the ingot in a basin with a mixer feels very off and ores having no secondary drops when precessed feels incomplete. 

### Mod Version

1.12.3

### Mod Loader Version

1.19.2 (0.14.17)

### Mod Loader

Fabric

**Comment by KLONOA9X6** [comment]
> Being able to create various metal plates from Ad Astra with the mechanical press

Implemented in version 1.12.5

Also check my datapack!
[Ad_Astra-Create](https://github.com/KLONOA9X6/Ad_Astra-Create)

**Comment by FullMetalMaster** [comment]
has this beiing updated to 1.20.1 i want to pump water in to the oxygen loader with create pipes
