### ISSUE TITLE
[Bug]: Unable to put fuel into rocket

### ISSUE THREAD

**Issue by unnfunnyy** [terrarium-earth/Ad-Astra#254]
### Bug Description

When going to put fuel into the rocket, nothing happens. The fuel doesn't enter the rocket and just remains in the bucket when putting it in the appropriate spot.
![2023-03-23_22 46 01](https://user-images.githubusercontent.com/128767589/227411496-bff6855c-792f-4763-bc5b-cc8091641c59.png)

### Expected Behavior

The fuel to fill up in the rocket so it could launch.

### Version

1.0.7

### Mod Loader Version

1.18.2

### Mod Loader

Fabric

**Comment by CodexAdrian** [comment]
1.18 is no longer supported. Your bug is likely because a mod in your modpack might have messed up the fluid tag for rocket fuel.

**Comment by AlexNijjar** [comment]
actually it looks like I may have broke the fuel tag on 1.18

**Comment by CodexAdrian** [comment]
🤦‍♂️

**Comment by unnfunnyy** [comment]
> actually it looks like I may have broke the fuel tag on 1.18

so it's just not going to work?

**Comment by AlexNijjar** [comment]
I'll update it since that's a breaking issue. problem was that the tag was called "fuel" in 1.19 but "fuels"in 1.18 so the ad astra fuels were getting adding to the wrong tag

**Comment by unnfunnyy** [comment]
> I'll update it since that's a breaking issue. problem was that the tag was called "fuels" in 1.19 but "fuel"in 1.18 so the ad astra fuels were getting adding to the wrong tag

okay that you very much!!!

**Comment by AlexNijjar** [comment]
@unnfunnyy 
https://modrinth.com/mod/ad-astra/version/1.0.8
