### ISSUE TITLE
[Bug]: When starting game with the mods i have it crashes when loading title page

### ISSUE THREAD

**Issue by walterwhite67** [terrarium-earth/Ad-Astra#255]
### Bug Description

I updated a couple mods including ad astra and since then every time i start the game with ad astra in my mods folder it crashes just before loading into the title screen saying "The game crashed whilst rendering overlay"

crash report: [crash-2023-03-24_19.50.06-client.txt](https://github.com/terrarium-earth/Ad-Astra/files/11067367/crash-2023-03-24_19.50.06-client.txt)

debug.log: [debug.log](https://github.com/terrarium-earth/Ad-Astra/files/11067366/debug.log)

### How to Reproduce?

N/A

### Version

1.12.6

### Mod Loader Version

1.19.2 43.2.6

### Mod Loader

Forge

**Comment by CBJaxxx** [comment]
I have this bug also.

**Comment by CBJaxxx** [comment]
make sure you have the dependencies downloaded, they don't stand out much but there are 3 of them

**Comment by walterwhite67** [comment]
It turns out reasourceful config just needed an update! My bad, and anyone who has a similar issue please check your dependencies.
