### ISSUE TITLE
[Bug]: Astrodux cannot be opened [Fabric 1.18.2]

### ISSUE THREAD

**Issue by Web7283** [terrarium-earth/Ad-Astra#256]
### Bug Description

Even with patchouli installed, the astrodux will not open. It will simply play a right-click animation with your hand but nothing will open. 

### How to Reproduce?

Install Patchouli
Get Astrodux
Open Astrodux

### Expected Behavior

Astrodux should open a GUI screen

### Version

1.0.8

### Mod Loader Version

1.18.2

### Mod Loader

Fabric

**Comment by wellcoming** [comment]
same for me

**Comment by wellcoming** [comment]
It seems that 1.18 does not include Astrodux

**Comment by AlexNijjar** [comment]
It's because I recently backported all the 1.19 assets but forgot to backport the astrodux. I'll update it soon
