### ISSUE TITLE
[Bug]: Catalog list empty (Quilt 1.19.4)

### ISSUE THREAD

**Issue by k2helix** [terrarium-earth/Ad-Astra#259]
### Bug Description

When launching a rocket and reaching the needed height for the gui to be shown, the catalog list is empty and nothing can be selected. This also happens when using /planetgui

### How to Reproduce?

1. Build a rocket or get it from creative
2. Place it on the launch platform
3. Add fuel
4. Launch and reach the orbit height
5. See empty catalog

### Expected Behavior

The catalog list should not be empty as all ad astra dimensions exist (checked using /execute in` and the save logs)

### Version

1.14.1

### Mod Loader Version

1.19.4 - 0.18.6

### Mod Loader

Quilt

### Logs or additional context

Screenshot of the planet gui:
![image](https://user-images.githubusercontent.com/49949593/227774801-14987c84-0635-4792-826a-4d943bf52801.png)

**Comment by AlexNijjar** [comment]
is it only on quilt? have you tested on fabric?

**Comment by k2helix** [comment]
> is it only on quilt? have you tested on fabric?

It seems to have fixed itself, no idea what could have caused it
