### ISSUE TITLE
Crash on startup [Bug]: 

### ISSUE THREAD

**Issue by caleb2wavyyy** [terrarium-earth/Ad-Astra#260]
### Bug Description

Everytime I try to start the game, it crashes with an error code of 1. When I remove the Ad Astra mod from the mods folder, the game starts up fine. Im not good with this kind of stuff. Plz help
[launcher_log.txt](https://github.com/terrarium-earth/Ad-Astra/files/11094522/launcher_log.txt)

### Version

idk

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
do you have the dependencies? also that's the wrong log

https://www.curseforge.com/minecraft/mc-mods/ad-astra/files/4452052
<img width="625" alt="Screenshot 2023-03-28 at 5 09 08 PM" src="https://user-images.githubusercontent.com/61668546/228377729-20e090e2-52de-40bc-aef0-25a8c2f02f11.png">

**Comment by caleb2wavyyy** [comment]
I do have the dependencies. Which log should I send?

**Comment by AlexNijjar** [comment]
latest.log

**Comment by caleb2wavyyy** [comment]
[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/11094573/latest.log)

**Comment by AlexNijjar** [comment]
can you send a screenshot of your mods folder too?

**Comment by caleb2wavyyy** [comment]
![2022-11-08](https://user-images.githubusercontent.com/129229918/228379157-6abe7736-20a4-4e6f-b291-252b157c3726.png)

**Comment by caleb2wavyyy** [comment]
![2023-03-28 (1)](https://user-images.githubusercontent.com/129229918/228379330-fd576b70-be5d-471c-9cf7-def0af991110.png)

**Comment by caleb2wavyyy** [comment]
sorry i uploaded the wrong one at first

**Comment by AlexNijjar** [comment]
where exactly did you download ad astra from? "Ad-Astra-Mod-Forge-1.19.2" is not the naming scheme we use

**Comment by caleb2wavyyy** [comment]
9minecraft if i remember right

**Comment by AlexNijjar** [comment]
9minecraft is a mod pirating website, don't use it. here are the 2 official sources, try with one of them

https://modrinth.com/mod/ad-astra
https://www.curseforge.com/minecraft/mc-mods/ad-astra

**Comment by caleb2wavyyy** [comment]
Ahhh I will keep that in mind. I downloaded from curseforge and now I just need a newer version of the config mod. I think I can handle that. Thanks for the help!
