### ISSUE TITLE
[Feature Request]: Allow To Reposition The Battery/Oxygen UI For Suits.

### ISSUE THREAD

**Issue by PolyframeX** [terrarium-earth/Ad-Astra#261]
### Is your feature request related to a problem?

This issue is present when wearing a jet suit or a space suit, and you have for say a minimap mod, the battery or oxygen will cover the minimap, making it unreadable, it would be very useful if you could reposition the battery or oxygen.

### Solution(s)

You can make a setting in the config that allows for a x and y offset.

### Describe alternatives you've considered

Alternatives is preset settings for positions.

### Mod Version

1.12.6

### Mod Loader Version

0.14.18

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
already a feature? it's in the suit config
