### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by superscene** [terrarium-earth/Ad-Astra#262]
### Bug Description

Unable to join the server.
Unknown recipe serializer - ad astra space suit
![image](https://user-images.githubusercontent.com/88982707/228935042-24969fb6-9064-48d1-ac03-4a1fc4d0c748.png)

### How to Reproduce?

1. join server
2. see the error
3.  console just logs joined server and left server messages
4. 

### Version

1.12.6

### Mod Loader Version

0.14.18

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/d1szs8id

**Comment by superscene** [comment]
Expected Behaviour -
Server can be joined without errors.

**Comment by AlexNijjar** [comment]
<img width="1512" alt="Screenshot 2023-03-30 at 8 54 49 PM" src="https://user-images.githubusercontent.com/61668546/229003134-5a4370d0-bba6-4903-87c1-269d4cced2f9.png">

seems to be working for me on fabric 1.12.6 with just ad astra an its dependencies
