### ISSUE TITLE
[Bug]: Skyblock

### ISSUE THREAD

**Issue by FooterManDev** [terrarium-earth/Ad-Astra#263]
### Bug Description

Hello! Got a bit of a big problem:
![2023-03-31_09 57 05](https://user-images.githubusercontent.com/71946346/229140345-0e53ac23-415c-46bf-8c02-e136fe374cda.png)
When taking a rocket from another planet back down to Earth, it generates a ton of regular Minecraft terrain, in a Skyblock set world, which pretty much completely defeats the purpose 😂. If there's no way to fix it, is there a way to disable the ability to go back to Earth in a rocket?

### How to Reproduce?

Enter a Skyblock world (Skyblock Builder mod)
Launch in a rocket to Space
Head back down to Earth

### Expected Behavior

To either fall into the void, or back on the generated Skyblock island.

### Version

1.12.6

### Mod Loader Version

1.19,2-43.2.6

### Mod Loader

Forge

### Logs or additional context

https://gist.github.com/FooterMan15/d13f6f0cdfdc6ab035360573b86d945d

**Comment by CodexAdrian** [comment]
Uh, are you sure you didnt just accidentally remove the mod that causes the world to be a skyblock world? Im fairly certain we do not touch world generation in terms of rockets. To me, this looks like the skyblock world gen mod stopped or got removed so it stopped generating the world

**Comment by FooterManDev** [comment]
Nope, still have it installed.

**Comment by FooterManDev** [comment]
I assume this is unfixeable due to the nature of Skyblock, so would it be possible to add a config entry that removes the ability to rocket to Earth?

**Comment by AlexNijjar** [comment]
you can just replace this https://github.com/terrarium-earth/Ad-Astra/blob/1.20.x/common/src/main/resources/data/ad_astra/planet_data/planets/earth.json

and set the `rocket_tier` to some high arbitrary number so that it can't be landed on

**Comment by FooterManDev** [comment]
Thank you Alex!
