### ISSUE TITLE
[Feature Request]: Config option to disable oregen

### ISSUE THREAD

**Issue by Efimero** [terrarium-earth/Ad-Astra#267]
I want to use custom worldgen/oregen and I can't figure out a good way to control ad astra materials. It'd be nice to have an option to disable the worldgen placement of ores and oil springs so I can have different methods to obtain the materials. Thank you.

### Mod Version

1.12.6

### Mod Loader Version

1.9.2 - 43.2.8

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
all of ad astra's ores are worldgen features, meaning you can disable them with a datapack or kubejs. for example, you could override the replaceable tags and remove the stone so the ore doesn't spawn https://github.com/terrarium-earth/Ad-Astra/tree/1.19/common/src/main/resources/data/ad_astra/tags/blocks

Adding a config for that is not standard for modpacks and is a lot harder for us to maintain so we won't be doing that.
