### ISSUE TITLE
Energy storage in the oxygen loader is not available

### ISSUE THREAD

**Issue by Mentos739** [terrarium-earth/Ad-Astra#268]
### Bug Description

![2023-04-08_14 10 48](https://user-images.githubusercontent.com/130226442/230721314-5b837263-8f13-4512-9f95-47bf3f6764d8.png)

### Version

ad_astra-forge-1.19.2-1.12.6.jar

### Mod Loader Version

1.19.2 forge 43.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Rios0036** [comment]
i cant load oxygen into the loader

**Comment by AlexNijjar** [comment]
assuming this is an optifine issue
