### ISSUE TITLE
[Feature Request]: buildable rocket

### ISSUE THREAD

**Issue by Thunderrock424242** [terrarium-earth/Ad-Astra#269]
### Is your feature request related to a problem?

Yes, as of now you can't build a custom rocket.

### Solution(s)

It would be cool to add like a custom rocket building mechanic for those who like to build you can place your own engine fuel tank jump drive and more so you could make your custom rocket.

### Describe alternatives you've considered

all the blocks and tools already in ad astra could make up a custom rocket. theres just no way to make one.

### Mod Version

1.19.2

### Mod Loader Version

43.2.6

### Mod Loader

Forge

### Additional context

there was once a mod that had a thing like this but it got shut down and i feel that type of mechanic would be a good thing for this mod.

**Comment by AlexNijjar** [comment]
We currently have no plans to add buildable rockets
