### ISSUE TITLE
Ability to transfer electricity and fluids through the walls

### ISSUE THREAD

**Issue by fenflow** [terrarium-earth/Ad-Astra#27]
An ability to transfer electricity and fluids through walls would be very helpful while building planetary bases. Something like airtight cables and tubes

**Comment by phiphila** [comment]
Great 😊 
A very good idea 👍

**Comment by willis1030** [comment]
It's a good suggestion. As in galacticraft 1.12.2 there is that kind of block. but how is the tile will be?
 A set of meterials should be created, including blocks and window glass. I believe that  space_glass_clear is a beautiful window glass.

**Comment by phiphila** [comment]
I would like to be able to create my own block.
A recipe that uses, among other things, a cable or a pipe and a block (this one will give the appearance).
But it could also be completely different and use concrete powder from minecraft game and a pipe or a cable, then make the concrete with water to solidify the whole thing 👍

**Comment by AlexNijjar** [comment]
For now we are adding these. we plan to add facades so you can turn any block into a cable in the future
<img width="1512" alt="Screenshot 2023-02-10 at 4 46 41 AM" src="https://user-images.githubusercontent.com/61668546/218073776-84c9b4fa-a422-4646-92f1-95d16b8b04e1.png">

**Comment by willis1030** [comment]
Wow that is great. I will try this soon.


Alex Nijjar ***@***.***> 於 2023年2月10日 週五 18:50 寫道：
