### ISSUE TITLE
[Bug]: The Sky wont go dark

### ISSUE THREAD

**Issue by MintKeyphase** [terrarium-earth/Ad-Astra#270]
### Bug Description

As title

### How to Reproduce?

Go in, load a world, time set midnight, maybe the long game time had some influence

### Expected Behavior

the sky goes dark

### Version

1.12.6

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

### Logs or additional context

Mods used
- ad_astra 1.12.6
	- additionalstructures 4.1.1
	- adorn 3.8.0+1.19.2
	- advanced_runtime_resource_pack 0.6.2 via automobility
	- alloy_forgery 2.0.17+1.19
	- architectury 6.4.62
	- autoconfig1u 3.4.0
	- automobility 0.4.1+1.19.2-fabric
	- blast 1.10
	- blue_endless_jankson 1.2.1 via owo
	- botarium 1.8.2
	- cardinal-components-base 5.0.2 via villagernames
	- cardinal-components-entity 5.0.0-beta.1 via mythicmetals
	- cardinal-components-level 5.0.2 via villagernames
	- carpet 1.4.84
	- cccbridge 1.4.1
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- collective 6.48
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 20 via geckolib3
	- com_github_llamalad7_mixinextras 0.1.1 via porting_lib_base
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_typesafe_config 1.4.1 via croptopia
	- computercraft 1.101.2
	- craftingbench 0.4-BETA+1.19
	- create 0.5.0g-796+1.19.2
	- createaddition ${version}
	- createdeco 1.2.12-1.19.2
	- croptopia 2.1.2
	- dehydration 1.3.3
	- diggusmaximus 1.5.8-1.19
	- dripstone_fluid_lib 2.0.1 via milk
	- emi 0.7.0+1.19.2
	- enchanted-vertical-slabs 1.6.2
	- environmentz 1.3.5
	- error_notifier 1.0.9 via roughlyenoughitems
	- extendedflywheels 1.19.2-0.5.0.g-1.2.5.1
	- eyemod 2.1.1
	- fabric-api 0.76.0+1.19.2
	- fabric-api-base 0.4.15+8f4e8eb390 via fabric-api
	- fabric-api-lookup-api-v1 1.6.14+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.1.1+16f1e31390 via fabric-api
	- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
	- fabric-command-api-v1 1.2.16+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.2.1+413cbbc790 via fabric-api
	- fabric-commands-v0 0.2.33+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.41+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.5.2+7c6cd14d90 via fabric-api
	- fabric-convention-tags-v1 1.3.0+4bc6e26290 via fabric-api
	- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.8+413cbbc790 via fabric-api
	- fabric-dimensions-v1 2.1.35+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.4+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.34+562bff6e90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.36+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
	- fabric-item-api-v1 1.6.6+b7d1888890 via fabric-api
	- fabric-item-groups-v0 0.3.39+9244241690 via fabric-api
	- fabric-language-kotlin 1.8.2+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.2.4+1b46dc7890 via fabric-api
	- fabric-loot-api-v2 1.1.13+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.16+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.7+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.24+33fbc73890 via fabric-api
	- fabric-networking-api-v1 1.2.11+10eb22f490 via fabric-api
	- fabric-networking-v0 0.3.28+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.2.2+d8ef690890 via fabric-api
	- fabric-particles-v1 1.0.14+4d0d570390 via fabric-api
	- fabric-recipe-api-v1 1.0.1+413cbbc790 via fabric-api
	- fabric-registry-sync-v0 0.9.32+9244241690 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690 via fabric-api
	- fabric-rendering-fluids-v1 3.0.11+4d0d570390 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.4+edbdcddb90 via fabric-api
	- fabric-screen-handler-api-v1 1.3.7+1cc24b1b90 via fabric-api
	- fabric-transfer-api-v1 2.1.6+413cbbc790 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
	- fabricloader 0.14.13
	- fabwork 1.1.7 via unicopia
	- fake-player-api 0.5.0 via create
	- ferritecore 5.0.3
	- fiber 0.23.0-2 via patchouli
	- forge_tags 3.0 via porting_lib
	- forgeconfigapiport 4.2.6 via create
	- geckolib3 3.1.38
	- hwg 1.2.10
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- io_netty_netty-codec-http 4.1.77.Final via computercraft
	- java 19
	- jsonem 0.1.2+1.19 via automobility
	- kirin 1.13.2+lts via unicopia
	- kyrptconfig 1.4.14-1.19 via diggusmaximus
	- lightestlamp 3.0.0f
	- lightmanscurrency 1.19.2-1.0.0.9a
	- lithium 0.11.1
	- magna 1.8.0-1.19 via modern_industrialization
	- mcwbridges 1.0.6
	- mcwdoors 1.0.8
	- mcwfences 1.0.7
	- mcwtrpdoors 1.0.8
	- mcwwindows 2.1.2
	- milk 1.0.51 via create
	- minecraft 1.19.2
	- mininggadgets ${version}
	- mm 2.3 via porting_lib_base
	- modern_industrialization 1.6.3
	- mythicmetals 0.16.4+1.19.2
	- omega-config 1.0.8 via magna
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- org_squiddev_cobalt 0.5.5 via computercraft
	- owo 0.8.5+1.19
	- pandamc_concreteplus 1.9.5
	- patchouli 1.19.2-77-FABRIC
	- peripheralium 0.4.17-1.19.2
	- phosphor 0.8.1
	- playerabilitylib 1.6.0 via modern_industrialization
	- porting_lib 2.1.623+1.19.2 via create
	- porting_lib_accessors 2.1.623+1.19.2 via porting_lib_extensions
	- porting_lib_attributes 2.1.623+1.19.2 via porting_lib_extensions
	- porting_lib_base 2.1.623+1.19.2 via porting_lib
	- porting_lib_common 2.1.623+1.19.2 via porting_lib_extensions
	- porting_lib_constants 2.1.623+1.19.2 via porting_lib_attributes
	- porting_lib_entity 2.1.623+1.19.2 via porting_lib
	- porting_lib_extensions 2.1.623+1.19.2 via porting_lib_transfer
	- porting_lib_lazy_registration 2.1.623+1.19.2 via porting_lib
	- porting_lib_model_generators 2.1.623+1.19.2 via porting_lib
	- porting_lib_model_loader 2.1.623+1.19.2 via porting_lib_obj_loader
	- porting_lib_models 2.1.623+1.19.2 via porting_lib
	- porting_lib_networking 2.1.623+1.19.2 via porting_lib
	- porting_lib_obj_loader 2.1.623+1.19.2 via porting_lib
	- porting_lib_transfer 2.1.623+1.19.2 via porting_lib
	- reach-entity-attributes 2.3.0 via create
	- registrate-fabric 1.1.44-MC1.19.2 via create
	- resourcefulconfig 1.0.20
	- resourcefullib 1.1.24
	- roughlyenoughitems 9.1.580
	- serialization_hooks 0.3.26 via porting_lib_base
	- space 1.1.8
	- team_reborn_energy 2.2.0 via botarium
	- travelersbackpack 1.19.2-8.2.13
	- trinkets 3.4.0
	- turtlematic 0.5.2
	- unicopia 1.0.0+lts
	- villagernames 4.5.1
	- whipdashing 1.0.4+1.19.x

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
This is likely not ad astra as I feel such a critical issue like this would have been reported a lot more. It's probably some other mod causing that.
