### ISSUE TITLE
[Feature Request]: Config Option for Entities that don't need Oxygen

### ISSUE THREAD

**Issue by razorethan** [terrarium-earth/Ad-Astra#272]
### Is your feature request related to a problem?

For some mods with added vehicles like Magitek Mechs, the vehicles die from a lack of oxygen on other planets.

### Solution(s)

It would be nice to have a whitelist for certain mobs/entities that don't need oxygen. This could be implemented in a separate portion of the existing ad_astra.toml file or in a completely separate config file. Basically, you could write down a list of mob ids for the entities that don't need oxygen and the game would apply a tag or something to them so that they would not need oxygen to breathe in environments where oxygen is absent.

### Describe alternatives you've considered

An item that could be crafted to make existing entities not require oxygen could also work; though this would be less optimal. Not to mention, this option also opens up the door for any player to do this, which with certain mobs could create game breaking scenarios. However, this option would still be better than nothing and it could have a fun model change or something like applying a glass helmet to a mob with a defined head in its model or something similar (space horses anyone???). Yet, this would once again have no real importance for things like non-living/mechanical entities that are supposed to not need oxygen to begin with.

### Mod Version

1.12.6

### Mod Loader Version

1.19.2 - 43.2.8

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
There is a tag for this, https://github.com/terrarium-earth/Ad-Astra/blob/1.19/common/src/main/resources/data/ad_astra/tags/entity_types/entities/lives_without_oxygen.json
