### ISSUE TITLE
[Bug]: Door Hitboxes Incorrect on 1.18.2-1.0.9 for Fabric

### ISSUE THREAD

**Issue by grantjbutler** [terrarium-earth/Ad-Astra#273]
### Bug Description

This is #47, but for Fabric and version 1.18.2-1.0.9 of Ad Astra (the latest version for 1.18.2 and Fabric at the time of creating this issue).

When placing down a sliding door facing west, you are able to completely walk through it when facing west, as well as walk most of the way through when facing east, but do get blocked on the far edge of the block the door is on. Additionally, the bounding box for the door when placed in this way is shown to be offset, as pictured in the screenshot below. I've been able to reproduce this for all variants of sliding doors (iron, steel, desh, and ostrum), as well as for the reinforced door and the airlock.

![2023-04-12_13 54 48](https://user-images.githubusercontent.com/526054/231542998-7971b19a-3f7c-49e2-a06a-1cb3a08efffb.png)

### How to Reproduce?

1. Install version 1.18.1-1.0.9 for Fabric (the latest at the time of creating this issue).
2. Place down a sliding door facing to the west.
3. Attempt to walk through the closed door.

### Expected Behavior

I expect to not be able to walk through a door while facing west when the door was placed facing west.

### Version

1.18.2-1.0.9

### Mod Loader Version

1.18.2-0.14.19

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
We are no longer working on the 1.18.2 version anymore so issues like these will only be fixed if there's some major bug on 1.18.2 that requires pushing a new version.
