### ISSUE TITLE
Ability to just have the old graphics from an update before back on/a simple standalone resource pack [Feature Request]: 

### ISSUE THREAD

**Issue by ghost** [terrarium-earth/Ad-Astra#274]
### Is your feature request related to a problem?

The new textures are absoluteley unfamiliar and do not go along with what Ad Astra has been so far. People have always relied on steady looks, as is the way of minecraft. There are tons of builds that now look completely different.

### Solution(s)

Adding the possibility to simply switch between the old and new textures or by adding the old ad astra textures as a standalone resource pack for people to use.

### Describe alternatives you've considered

-

### Mod Version

ad_astra-forge-1.19.2-1.12.6.

### Mod Loader Version

ad_astra-forge-1.19.2-1.12.6.

**Comment by CodexAdrian** [comment]
no

**Comment by ghost** [comment]
> no? as in arrogance?

aha so a random ass mofo answers gz,  its about people realising people dont want the retarded low res textures that got implemented, wich is fucking up builds all over the place, nobody cares about these useless tiny tech things put into the *mod* its a gloryfied texture pack at best and now that thats gone it turned into..well nothing basically, you turned your textures into garbage and you know it, also nice how you rant off wrong information on your twitter as if you knew anything...your probably some fucked up gender fluid oh lord...no gonna come bac kto this shit but you heard it bye you jackass, ill fix the textures for you no worries 

>ur shit twitter post ???
Did you just argue that if the developers thought less about the features and the overall feature set, the game would be better..? More features != more better, it would just be a jumbled up disconnected mess, and minecraft wouldn’t be the amazing and well thought game that it is
=yeah but not with your gumbo mod it isnt, the shit you say about mc tells me you have no freaking clue, stuck in your bubble in the desert

**Comment by CodexAdrian** [comment]
Whoa okay resorting to straight up hate speech now, very cool. Definitely helped you make your point.
