### ISSUE TITLE
[Bug]: Oxygen Dispenser doesn't work with beds

### ISSUE THREAD

**Issue by Zachadactyl** [terrarium-earth/Ad-Astra#276]
### Bug Description

In my moon base (420 blocks) I can run around without tanks just fine but when I stand on a bed I take oxygen and freeze damage.  The bed is placed both inset into the ground as well as on iron blocks.  This also happens with sliding doors you freeze if you get near them. I have to be on 1.19.3 for this as all my other mods are no updated yet. 

### How to Reproduce?

1. Load mod 1.19.3 Forge
2. Travel to moon
3. Create sustainable moon base
4. Add sliding doors/beds
5. Go into survival and walk on/near them
6. Feel the (frost) burn

### Expected Behavior

Not dying in my sleep 

### Version

1.18.3

### Mod Loader Version

1.19.3 - 44.1.23

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
can you try on the latest version? I'm not able to reproduce this
<img width="1512" alt="Screenshot 2023-07-14 at 7 41 10 AM" src="https://github.com/terrarium-earth/Ad-Astra/assets/61668546/ec75f101-74e7-465e-9e31-3d07c3cb1b49">
