### ISSUE TITLE
[Bug]: Failed to generate assets for Block{v_slab_compat:ad_astra/venus_sandstone_brick_vertical_slab}

### ISSUE THREAD

**Issue by Kineati** [terrarium-earth/Ad-Astra#277]
### Bug Description

As the title says, it not generated the venus_sandstoone_brick_vertical_slab, it generated a purple and black block.

### How to Reproduce?

1. Launch the Modpack

### Version

1.12.6

### Mod Loader Version

1.19.2 - 43.2.8

### Mod Loader

Forge

### Logs or additional context

[Render thread/ERROR] Failed to generate assets for Block{v_slab_compat:ad_astra/venus_sandstone_brick_vertical_slab}

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by rsslcs** [comment]
The venus_sandstone_brick_slab blockstate json references "minecraft:air" for double slab texture instead of "venus_sandstone_bricks".

Doing a little PR with the fix if it's not an intended "bug".
