### ISSUE TITLE
[Bug]: All Jet Suite Pieces Consume Energy

### ISSUE THREAD

**Issue by Plobby** [terrarium-earth/Ad-Astra#280]
### Bug Description

Just a small bug but it seems all pieces of the final Jet Suit store power but only the chestplate uses or displays the power it has stored. I only noticed this when using it with a Powah Player Transmitter. It looks as if the chestplate is not being charged because the rest of the armour takes power first.

### How to Reproduce?

1. Place any item of Jet Suit equipment into an Energizer and it will start charging
2. The chestplate will show energy level - every other armour piece will not

### Expected Behavior

Depending on the intended use:

1. If the rest of the armour is intended to store/use power, I would expect it to be displayed on each armour piece
2. If the rest of the armour is not intended to store power I would not expect it to drain power from an Energizer or Powah Player Transmitter

### Version

1.12.6

### Mod Loader Version

1.19.2 - 0.14.19

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
should be fixed in 1.12.7
