### ISSUE TITLE
[Bug]: Oxygen Loader

### ISSUE THREAD

**Issue by Rios0036** [terrarium-earth/Ad-Astra#281]
### Bug Description

i host a server latest version and oxygen will not load . 
in creative mode it does.

### Version

2.0.4c

### Mod Loader Version

0.223.1.9730

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
what does that mean? you're going to have to be more descriptive on what your issue is.
