### ISSUE TITLE
[Bug]: Sky Render No Longer Working with Rubidium 0.6.2a - works with 0.6.2

### ISSUE THREAD

**Issue by zachsai** [terrarium-earth/Ad-Astra#282]
### Bug Description

When updating rubidium from 0.6.2 to .6.2a, the sky render breaks, by that I mean that clouds are showing in orbits and planets when they have the settings to not do so.

### How to Reproduce?

Download Create Planetary modpack on version 1.1.2
Go to moon orbit or moon, see clouds

downgrade rubidium down a version, clouds disappear as intended

### Expected Behavior

no clouds

### Version

1.12.6

### Mod Loader Version

1.19.2 - 42.2.3

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Old-Man-D** [comment]
I notice the same behavior.  my modpack just updated to mod version 1.12.6 and now I have clouds in orbit too

**Comment by AlexNijjar** [comment]
Use embedium.
