### ISSUE TITLE
[Bug]: oil to water

### ISSUE THREAD

**Issue by Mimiccube** [terrarium-earth/Ad-Astra#283]
### Bug Description

If you place kelp on petroleum, the petroleum will become water.

https://youtu.be/lTWB2NqrG_g
- [ ] 

### Version

1.13.6

### Mod Loader Version

1.19.3

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by KLONOA9X6** [comment]
Looks like your video is not upload correctly...

**Comment by Mimiccube** [comment]
> Looks like your video is not upload correctly...

Oh. Sorry. I uploaded the video in my YouTube.

**Comment by Mimiccube** [comment]
Looks like your video is not upload correctly...
> Oh. sorry. I uploaded the video in my YouTube channel.
