### ISSUE TITLE
[Bug]: Crash when attempting startup after removing fastfurnace for fabric

### ISSUE THREAD

**Issue by Shibva** [terrarium-earth/Ad-Astra#285]
### Bug Description

Due to a isssue I belive I was having I decided to remove the mod aforementioned above but after trying to start the game it will now crash. I tried to see whats wrong but theres alot that the crashlog spits out and it says that its issues running "main" wtih ad astria

### How to Reproduce?

uncetain, mods present and atempt to boot using the lattest 1.19.2 version of Quilt (Fabric mods work on Quilt; its just a fork of fabric)

### Expected Behavior

Issue vanishes if you were to put FastFurnace for Fabric into the modlist for whatever reason

### Version

1.12.6

### Mod Loader Version

1.19.2 - 0.18.10

### Logs or additional context

Crashlog: https://pastebin.com/UKDcfsau

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
try making a new instance and importing all your mods except fastfurnace. It's not an incompatibility with fastfurnace and ad astra specially, something probably just broke when you removed it.
