### ISSUE TITLE
[Bug]: Major lag spikes after visiting Mercury and Venus

### ISSUE THREAD

**Issue by LandofHeros2234** [terrarium-earth/Ad-Astra#286]
### Bug Description

So I went to Mercury and Venus, but afterwards, my game started getting major lag spikes. I checked the debug menu and it showed that there were over 5000 chunks loaded server side (Or at least how I interpreted the F3 debug menu). I placed waystones from BlayTheNinth's Waystones mod so I could travel back to earth, as well to other planets, without using the limited amount of fuel available. I don't know if that has anything to do with the lag spikes, but details are important
![2023-05-07_17 24 55](https://user-images.githubusercontent.com/126440322/236708330-c8bd7f4d-dc55-4cf1-96bb-befe608d0122.png)
![2023-05-07_17 30 08](https://user-images.githubusercontent.com/126440322/236708339-07b062d2-62d2-42ab-8e58-10c8c42a9b6d.png)
Edit: I do not have any mods that change rendering in any way.
Edit 2: I also visited The Moon and Mars during the same play session and put waystones on those planets as well. I did not go to Glacio because I wanted to make a Jet Suit before going there.
Edit 3: The lag spikes went away after I closed the game. I did not test to see what would happen if I just left and rejoined the world.

### How to Reproduce?

I just went to Mercury and Venus
I placed down a waystone (Relevancy unknown)
Lag Spikes

### Expected Behavior

No lag spikes

### Version

1.12.6

### Mod Loader Version

1.19.2 - 43.2.8

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Seems to have been a fluke? Ad astra uses the vanilla dimension system
