### ISSUE TITLE
[Bug]: Crash when attempting to start on Forge

### ISSUE THREAD

**Issue by LumaTot** [terrarium-earth/Ad-Astra#287]
### Bug Description

Ad Astra is causing the game to crash before displaying the Mojang logo. This occurs because of Ad Astra, as trying to launch the game with it as the only mod in the folder causes the crash. The crash message does not show any crash report and has Exit Code 1. I have tried this on multiple versions of Forge, ranging from 43.2.0 to 43.2.11.

![image_2023-05-09_225555655](https://github.com/terrarium-earth/Ad-Astra/assets/133082280/e77c6663-6f1f-4772-b033-9b834986a095)

### Version

1.12.6

### Mod Loader Version

1.19.2 - 43.2.11

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
you are probably missing the dependencies, send the log

**Comment by LumaTot** [comment]
Oh... apparently I had downloaded the Fabric versions of the dependencies.

This is embarrassing I didn't realize... Probably would be best to somehow hide this.
