### ISSUE TITLE
[Feature Request]: Cryo Freezer Pipe Support

### ISSUE THREAD

**Issue by bcrotty** [terrarium-earth/Ad-Astra#290]
### Is your feature request related to a problem?

I can't insert ice into the Cryo Freezer using pipes from other mods.

### Solution(s)

I would like to be able to connect pipes from other mods to the Cryo Freezer to be able to insert ice. Being able to do that on any side would be ideal, but at least the top would be very helpful.

### Describe alternatives you've considered

As far as I can tell, you can only insert ice into the Cryo Freezer with vanilla hoppers from the top.

### Mod Version

1.12.6

### Mod Loader Version

1.19.2-43.2.8

### Additional context

I'm playing ATM8.

**Comment by AlexNijjar** [comment]
The cryo freezer is being removed in a future update so no further work will be put into the machine.

**Comment by sylveon** [comment]
What's the replacement for the cryo freezer?

**Comment by CodexAdrian** [comment]
it wont be replaced, the concepts we have for the mod will not necessitate the existence of the cryo freezer
