### ISSUE TITLE
[Feature Request]: Space Station FTB Teams Support

### ISSUE THREAD

**Issue by bcrotty** [terrarium-earth/Ad-Astra#291]
### Is your feature request related to a problem?

It would be great for people on the same FTB team to share a space station. Currently, it doesn't show that a space station is available until you craft your own station.

### Solution(s)

When someone on your FTB team crafts a space station, everyone should have a space station for that planet marked as completed and be able to all come.

### Describe alternatives you've considered

There are various ways to teleport to a space station someone is at.

### Mod Version

1.12.6

### Mod Loader Version

1.19.2-43.2.8

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
we won't be supporting FTB teams as we have our own teams mod called argonauts. but it'd be a cool idea if support is added to that. However space stations are going to be completely revamped in the future so I'm not sure if such support would even be possible after that

**Comment by AlexNijjar** [comment]
Added in 1.15.7
