### ISSUE TITLE
[Feature Request]: some recipes missing tags for crafting

### ISSUE THREAD

**Issue by Badgergm** [terrarium-earth/Ad-Astra#293]
### Is your feature request related to a problem?

recipes such as space suit and crafting plates allow for any steel to be used to craft the item. I was wondering if steel blocks can have the same tags to craft so the mod can be explored without using ad_astra:steel_ingots and using steel ingots from other mods. This may be the same case with other recipes but steel blocks was the main one I noticed.

### Describe alternatives you've considered

I have attempted to try fix this with datapacks but was not sucessful (I worked out datapacks, so I don't need this fixed for personal use)

### Mod Version

1.14.1

### Mod Loader Version

45.0.49

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
this was probably just me forgetting to change it to a tag and is likely just a one off thing with the steel block. If you find any more recipes like that, let me know
