### ISSUE TITLE
[Feature Request]: Space sandbox option

### ISSUE THREAD

**Issue by ElementalIdiot** [terrarium-earth/Ad-Astra#294]
### Is your feature request related to a problem?

I want to make a large spacecraft but do not want to worry about accidentally building too low or making it complicated to reach it in case I make a server for friends. Really just an excuse for an idea I had after accidentally falling out of orbit onto a planet in creative.

### Solution(s)

A "deep space" option in GUI that will transport you to a blank slate of space with no planets nearby. Maybe even a word gen option that allows "deep space" to be the natural spawn, though there would have to be a functioning space station at spawn in that case as someone spawning in survival would endlessly die.

Also, if/when a really good buildable vehicle mod comes out this would make the perfect sci-fi playground.

### Mod Version

1.12.6

### Mod Loader Version

1.19.2

### Mod Loader

Forge, Fabric

### Additional context

This isn't really a necessity (to me at least) but I think it would be neat. Just food for thought I guess.

**Comment by AlexNijjar** [comment]
We will not be adding any more orbit dimensions. In fact, we will be removing all but one of them in a future update as they're all basically the same empty void world. However the build hight will be increased.
