### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by DaddyBigDonger** [terrarium-earth/Ad-Astra#297]
### Bug Description

Struggling to use Flags -

Using Imgur for URL (duh)
Tried Copying the Imgur picture link through share button>copy link.
Tried Copying the Imgur picture link from searchbar on browser.
Tried Copying the Imgur picture link by right clicking and clicking "Copy Image"
Tried Copying the Imgur picture link by right clicking and clicking "Copy Image Adress"
Link is usually 1 unit too long and/or showing as invalid.

Feel like its something obvious but really cant get it to work.

Im playing on a All of Fabric 6 Server. (1.19.2)

Cheers :)

### Version

1.19.2

### Mod Loader Version

Fabric 0.14.19

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
can you send the link you're trying to use?

**Comment by DaddyBigDonger** [comment]
https://imgur.com/gallery/9nk7OEl

This one for example will be cut off to "https://imgur.com/gallery/9nk7OE" missing the l at the end.

**Comment by AlexNijjar** [comment]
you need to right-click on the image an select "copy image address" to get the actual image link (https://i.imgur.com/JtGFXcE.jpeg)

**Comment by AlexNijjar** [comment]
<img width="1512" alt="Screenshot 2023-05-28 at 12 07 12 AM" src="https://github.com/terrarium-earth/Ad-Astra/assets/61668546/dac91471-60c8-455f-a583-7b6403c12882">

**Comment by DaddyBigDonger** [comment]
Thanks! I appreciate the speedy reply but i figured it out for myself in the end. Right clicking and "copy image address" doesnt work but after doing that and deleting the last 3 or so digits and replacing with .jpg worked. Cheers :)
