### ISSUE TITLE
[Feature Request]: Ability to remove 1st person hand skin when wearing space suit

### ISSUE THREAD

**Issue by Nebzla** [terrarium-earth/Ad-Astra#299]
### Is your feature request related to a problem?

When wearing space suits in Ad Astra (1.19.2 is the only version i can confirm this on) while using shaders with rubidium and oculus , the hand model glows brightly and appears positioned oddly. This only happens when wearing a space suit, including both the default one and the netherite variant.

### Solution(s)

As it's probably a lot more difficult to fix issues related to shaders causing visual bugs, it would be nice if there was a config option to be able to disable the hand skin in 1st person when wearing a space suit. This would allow you to still be able to use shaders without visual issues on the hand when wearing the suit, and wouldn't require trying to work around shader issues.

### Describe alternatives you've considered

Alternatively the actual source of the issue could be fixed instead of adding a workaround to disable the hand skin, but I imagine that this is much harder to do and i have a lack of knowledge on this topic, so I presume the suggested solution is easier to impement.

### Mod Version

1.19.2

### Mod Loader Version

43.2.13

### Mod Loader

Forge

**Comment by KLONOA9X6** [comment]
First person render bug?
Hmm...
How about [this](https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/main/java/com/simibubi/create/content/equipment/armor/NetheriteBacktankFirstPersonRenderer.java)?

**Comment by Nebzla** [comment]
I dont really know a whole lot about java sorry, i'm confused what i should do with this.

**Comment by KLONOA9X6** [comment]
Create mod also modified first person hand render, and didn't occur this bug.

**Comment by ThatGravyBoat** [comment]
Create doesnt allow it to be enchanted is why it specifically works, because we allow for it to be enchanted which causes shaders to try emissive shaders on it

**Comment by KLONOA9X6** [comment]
> Create doesnt allow it to be enchanted is why it specifically works, because we allow for it to be enchanted which causes shaders to try emissive shaders on it

Are you sure it worked?
![YF VL`_4PJL38X3VT 9INCN](https://github.com/terrarium-earth/Ad-Astra/assets/95112579/7e666b26-be4c-49aa-8681-075b857412e5)

**Comment by KLONOA9X6** [comment]
Suit is enchanted but it not shown on first person hand.

**Comment by ThatGravyBoat** [comment]
it renders with the enchanted renderer so it may have worked at one point but doesn't anymore, ad astras one specifically uses the enchanted vertex buffer so that may have broken separately but create renders theirs solid full bright nothing else so that is likely why theirs works fine because no shader should ever touch the solid renderer

**Comment by KLONOA9X6** [comment]
So, it's not compatible with Create?

**Comment by ThatGravyBoat** [comment]
I never said that. I said we both do it different ways and creates way just uses the solid renderer which we don't

**Comment by KLONOA9X6** [comment]
But enchanted renderer not working...

**Comment by ThatGravyBoat** [comment]
the enchanted renderer not working doesnt mean create broke it that can mean it just broke on its own or something else, I never said create broke it

**Comment by KLONOA9X6** [comment]
(So that's the reason that I delete it...)
