### ISSUE TITLE
[Bug]: Server crash when going to another planet / moon with modpack AOF6

### ISSUE THREAD

**Issue by Ajc220304** [terrarium-earth/Ad-Astra#302]
### Bug Description

Whenever i go to the moon the server just crashes without giving any errors in console

### How to Reproduce?

1. have a server with aof6 (all of fabric) installed
2. go to moon
3. crash

### Expected Behavior

no crash

### Version

1.12.6

### Mod Loader Version

0.14.21

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I can't really diagnose this without a crash report, and since this is the only report of it and I'm able to go there just fine, I'm assuming it's just a one off thing
