### ISSUE TITLE
[Bug]: Astra does not work on my server

### ISSUE THREAD

**Issue by KINGOFGAMESALL** [terrarium-earth/Ad-Astra#303]
### Bug Description

I play on a server with a friend, I installed the Astra mod to fly into space with it, but as a result, the mod simply does not work. There are blocks, but there are no crafts and their work. In the local world, everything works.

### Version

1.14.1

### Mod Loader Version

1.19.4

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by KLONOA9X6** [comment]
Did you install Ad Astra on client?

**Comment by AlexNijjar** [comment]
you probably don't have it installed on the server
