### ISSUE TITLE
[Bug]: Extreme worldgen lag and log spam on Mercury

### ISSUE THREAD

**Issue by Questwizard** [terrarium-earth/Ad-Astra#306]
### Bug Description

Whenever I go to Mercury, world generation is incredibly laggy, and spams the log with MultiNoiseBiomeSource warnings. My log was spammed with roughly 150MB of the same warning in about 3 minutes.

Yes I know I'm running 1.20.1 and not 1.20, but the exact same thing also happens on 1.20, and the changes between these two versions of MC are minimal at most. The rest of the mod is working just fine so far.

### How to Reproduce?

1. Go to Mercury, whether by the intended method or by teleporting there with commands.
2. Go to an area that would generate new chunks, and observe how laggy it is.

### Expected Behavior

Expected world generation to be going at a decent speed, especially since I'm on a very high-end PC.

### Version

1.15

### Mod Loader Version

0.14.21-1.20.1

### Mod Loader

Fabric

### Logs or additional context

latest.log: https://gist.github.com/Questwizard/f3e0b470b90b9ce5eeca46cf4e3303ea

Note: I had to truncate 1.8 million lines of the spam, totalling around 150MB. The warning is as follows, with various thread numbers throughout:
[Worker-Main-23/WARN]: Only one biome is available in MultiNoiseBiomeSource!

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I tested on Fabric 1.20 and I'm not able to replicate this issue. Can you try removing your worldgen mods, such as terrablender and terrestrial, and check if that works?

**Comment by Questwizard** [comment]
I started off by removing terrestria, traverse, terrablender and nyctophobia (uses terrablender), and the issue went away. I added both terrablender and nyctophobia back in with no issues, but adding either terrestria or traverse back in starts the lag and log spam.

I also made a new profile with the bare minimum mods to run ad astra, terrestria and traverse and got the same results. Removing both of them fixes it.

**Comment by Questwizard** [comment]
Looks like they fixed it on their end. The insane amount of logging alone that Biolith was doing was responsible for the lag. It seems to have been a valid warning though considering Mercury uses a multi-noise dimension but only has one biome.
