### ISSUE TITLE
[1.19.2 Fabric] Crash

### ISSUE THREAD

**Issue by itsdinkd** [terrarium-earth/Ad-Astra#308]
### Bug Description

Not sure how this happened but i am reporting it anyways. AQM2's official server encountered this crash that i found in its logs earlier today. 

### How to Reproduce?

n/a

### Version

1.12.6

### Mod Loader Version

1.19.2 - 0.14.19

### Mod Loader

Fabric

### Logs or additional context

https://mclo.gs/tZG89yD

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Have you experienced this issue any more times on the server? because it seems to have just been an issue with loading a chunk at the wrong time and is thus probably not an issue with ad astra

**Comment by itsdinkd** [comment]
I dont believe i have experienced it after this one time. i will check my crash logs though
