### ISSUE TITLE
[1.19.2 Forge] crash

### ISSUE THREAD

**Issue by Crazyrussian24** [terrarium-earth/Ad-Astra#309]
### Bug Description

When I try to play with mod version 1.12.6 on game version 1.19.2, my game crashes and I get the exit code 1, which is typically caused by outdated mods

### How to Reproduce?

Install Ad Astra Forge version 1.12.6 for Minecraft version 1.19.2, and try to start the game through the official Minecraft launcher

### Version

1.12.6

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
![IMG_5121](https://github.com/terrarium-earth/Ad-Astra/assets/61668546/10a2cb8b-13df-4d29-8f0f-0cb4cdc49aec)

**Comment by CubeGamer647** [comment]
[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/11908459/latest.log)
Can confirm, here's logs

**Comment by AlexNijjar** [comment]
![IMG_5124](https://github.com/terrarium-earth/Ad-Astra/assets/61668546/129e865a-4f36-4d22-951a-127a1cec178d)
