### ISSUE TITLE
[Suggestion] integration with other tech mods

### ISSUE THREAD

**Issue by yu-re-ka** [terrarium-earth/Ad-Astra#31]
I would like to play Modern Industrialization and Ad Astra together, but they are not well integrated. Both have steel ingots registered to a tag and recipes registered which are using that tag, but producing the steel ingots from Ad Astra is way cheaper and easier (for MI steel you need multiple multiblocks).
It would be nice to have an option to disable a lot of the features in Ad Astra. Like disabling the generator and compressor entirely, instead adding recipes in the MI machines for making the other Ad Astra plates.

**Comment by CodexAdrian** [comment]
You can just remove the recipe for those machines, and everything is recipe based so you can also just remove the recipes for steel and plates.
