### ISSUE TITLE
[Bug]: Player spawn out of the rocket

### ISSUE THREAD

**Issue by Allis122** [terrarium-earth/Ad-Astra#311]
### Bug Description

When traveling to a planet, the player spawns at the same place as the rocket lander but not inside of it. The lander crashes into the planet while the player falls.

### How to Reproduce?

1. Take-off 
2. Select any planet (execept earth)

### Version

1.12.6

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
sounds suspiciously similar to these issues. Do you have transit railway?
https://github.com/search?q=repo%3Aterrarium-earth%2FAd-Astra+transit+railway&type=issues

**Comment by Allis122** [comment]
Yep, I will try to remove it as well, thank you.
