### ISSUE TITLE
[Bug]: visual error

### ISSUE THREAD

**Issue by Rogenar** [terrarium-earth/Ad-Astra#312]
### Bug Description

The Oxygen Distributor slot is not visible.
![ss1](https://github.com/terrarium-earth/Ad-Astra/assets/122460325/e4547780-2976-4dd2-a419-ff5426222e07)

### Version

1.20.1

### Mod Loader Version

0.14.21

### Mod Loader

Fabric

### Logs or additional context

[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/11848355/latest.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
fixed in latest release
