### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Aabaddon** [terrarium-earth/Ad-Astra#314]
### Is your feature request related to a problem?

no no there is no problem, just a couple ideas.

### Solution(s)

you should add an option into the mod to add dimensions as planets, so we could travel to any dimension through the rocket instead of 100000 portals, that and add the option to give certain properties to each dimension, like less gravity in the overworld, oxygen at certain deepness or config the oxygen per dymension so modpacks are funnier and more immersive.

### Describe alternatives you've considered

i mean, that things up there are the alternatives, i think i read somewhere yall recommended to make datapacks and stuff like that but...not everyone knows how to do it so it would be easier if it was an implemented option ingame, thank u for reading and for ur time!

### Mod Version

1.12.6

### Mod Loader Version

1.19.2 - 0.14.21

### Mod Loader

Fabric

### Additional context

love your mod and all my modpacks i use to play with friends have it (?

**Comment by Gilberry** [comment]
They explain how to do exactly what you are requesting on the wiki connected to this repository.

**Comment by AlexNijjar** [comment]
^
