### ISSUE TITLE
[Bug]: Thermal Machine Sounds Loop Forever in Orbit

### ISSUE THREAD

**Issue by Korveyus** [terrarium-earth/Ad-Astra#318]
### Bug Description

I wasn't sure which issue tracker to report this to, but it only seems to happen in Ad Astra's dimensions. After a Thermal machine begins playing its ambient sound, it continues to loop forever even when the machine is no longer active. I'm able to reproduce this with the steps below every time I restart the game. Multiple machines cause their sounds to stack on top of every other sound currently looping.

**Note:** Adjusting the Ambient volume slider to zero and back again will remove these sounds.

### How to Reproduce?

1.) Create a fresh Minecraft instance. (Minecraft 1.19.2, Forge 43.2.0)
2.) Install the mods listed below.
3.) Use Creative Mode to build a Space Station.
4.) Set up an Electric Furnace, Pulverizer, or any Thermal machine that has an ambient sound while crafting.
5.) Place a valid item inside it.
6.) Allow it to finish crafting, or remove it after the machine sound begins.

The sound should now be looping forever. I managed to reproduce this on Planets as well, but after restarting the game it no longer seems to happen with an already existing Thermal setup present on load.

### Expected Behavior

In every non-Ad Astra dimension, Thermal machine sounds stop when the machine itself isn't active. This should always be the case even when in an Ad Astra dimension.

### Version

1.12.6

### Mod Loader Version

1.19.2 - 43.2.0

### Mod Loader

Forge

### Logs or additional context

**Mod Versions:**
ad_astra-forge-1.19.2-1.12.6
botarium-forge-1.19.2-1.8.2
cofh_core-1.19.2-10.2.1.40
resourcefulconfig-forge-1.19.2-1.0.20
resourcefullib-forge-1.19.2-1.1.24
thermal_expansion-1.19.2-10.2.0.21
thermal_foundation-1.19.2-10.2.0.47

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Korveyus** [comment]
Only seems to happen when the following setting is true:

doSpaceMuffler = true

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7. Tickable sounds like that are no longer affected
