### ISSUE TITLE
[Bug]: Getting thrown out of lander

### ISSUE THREAD

**Issue by Drakune** [terrarium-earth/Ad-Astra#319]
### Bug Description

If i fly to any planet, i will be thrown out of the lander and just die. I know its a issue with transit railway mod, but there is a workaround with a carpet script, but doesnt work always. Is this a know problem and being worked on? because i saw a post that is years old, and yet still the problem occurs

### How to Reproduce?

1. Go to any planet
2. Die

### Expected Behavior

Go to planet
Land
Play

### Version

1.15.1

### Mod Loader Version

MC: 1.20.1 Fabric Loader: 0.14.21 Launcher: 0.11.2

### Mod Loader

Fabric

### Logs or additional context

Modlist: https://pastebin.com/kNxJ4x0N

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
We told them how to fix months ago; it's on their end.
https://github.com/jonafanho/Minecraft-Transit-Railway/issues/427#issuecomment-1463074871

**Comment by Drakune** [comment]
Ah okay i see, then i will reopen a new issue on their issue tracker? Because you cant play Ad Astra with transit railway mod installed

**Comment by Drakune** [comment]
https://github.com/jonafanho/Minecraft-Transit-Railway/issues/713
