### ISSUE TITLE
[Bug]: The text is not visible

### ISSUE THREAD

**Issue by VerWave** [terrarium-earth/Ad-Astra#320]
### Bug Description

If you leave the planet on a rocket and go to the planet selection window for landing, and then hover the cursor over the buttons, part of the text that goes beyond the interface disappears. Tested on vanilla minecraft 1.20.1 in creative mode
Screenshots:
https://ibb.co/6yFJ2FR
https://ibb.co/2F0cj0f

### Version

1.15.1

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in latest version

**Comment by VerWave** [comment]
> Исправлено в последней версии

Thanks!
