### ISSUE TITLE
[Bug]: Oxygen Loader Hopper/Pipe Problems

### ISSUE THREAD

**Issue by sarpuser** [terrarium-earth/Ad-Astra#321]
### Bug Description

The oxygen loader seems to not be able to insert into the oxygen tank slot when using a hopper. The empty oxygen tank goes into the water bucket slot. Also, item transport pipes from other mods won't even connect, and Applied Energistics 2 exporters won't export.

### How to Reproduce?

1. Place oxygen loader
2. Try placing item transport pipes on top, see that they won't connect
3. Attach an AE2 exporter and try exporting empty oxygen tanks, see that it won't export
4. Place hopper above oxygen loader
5. Place 2 empty oxygen tanks into the hopper
6. See that one tank will be placed in the water bucket slot and the hopper will not be able to insert the other one

### Expected Behavior

- The oxygen should also be insertable 
- The slots should be set to only accept certain items, water buckets etc for the water slot and oxygen loadables for the oxygen slot
- Item transport pipes from other mods should be able to connect to the oxygen loader

### Version

1.12.3

### Mod Loader Version

43.2.6

### Mod Loader

Forge

### Logs or additional context

Shift clicking an empty oxygen tank also puts into the water slot instead of the oxygen slot.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Should be fixed in 1.15.7. Each machine has it's own side configuration to control what slots do what
