### ISSUE TITLE
[Bug]: Other mods' pipes/cables/energy, fluid, item transport blocks only work if set to extract with ad astra machines

### ISSUE THREAD

**Issue by StormCircuit** [terrarium-earth/Ad-Astra#322]
### Bug Description

I initially found the issue with XNET and noticed others were having the issue on github too but the reports were very very specific. I found that this is a general issue with energy in Ad Astra machines. None of the energy blocks appear to properly push their energy and instead must be extracted by setting the pipe manually. 

This results in issues with mods like XNET which cannot seemingly properly detect the energy that can be extracted from a block such as the coal generator. This means mods like XNET cannot actually be used with Ad astra. It also pops up even with the Create mod and the oxygen loader as you cannot extract oxygen from the oxygen loader unless you use this mod's pipes while at the same time it does work between blocks like the water pump and the oxygen loader (see screenshot)

https://imgur.com/a/4ZzvYKV
In this screenshot you can see that the pump is pumping water into the loader but the loader cannot have its oxygen extracted by create. You can substitute any mod's pipes for this and it seems to have similar behavior

https://imgur.com/a/2XzypUI
in this screenshot a single power cable from Pipez cannot transfer energy from a coal generator to a machine. If I set the pipez end connected to the generator to 'extract' (by hitting it with a wrench) it then works.

Apparently this behavior causes problems for playing nice? McJty, the creator of Xnet (who I initially went to) said I could quote him in that "Energy is ALWAYS pushed. Never extracted. That's very important to get everything working together nicely. You can quote me on that"

Let me know if this is intended behavior or if this is a bug because I would love to use mods like Xnet for my modpack's progression!

### How to Reproduce?

Replicate screenshots, open each machine and observe that energy and fluid extraction behavior is inconsistent both with Ad Astra its self as well as other mods.

### Expected Behavior

Energy is "pushed" such that other mod's transport solutions can take advantage of them and or that behavior is consistent across the mod (IE some machines can seemingly have their fluids extracted without issue and others none at all)

### Version

1.15.1

### Mod Loader Version

1.20.1 - 47.0.49

### Mod Loader

Forge

### Logs or additional context

Let me know if logs apply here. I don't have any crash logs but can upload my client's logs. I just wouldn't know how to replicate the issue properly for logging/it doesn't seem to apply here due to lack of actual error.

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Should be fixed in 1.15.7. All machine side interactions were redone.
