### ISSUE TITLE
[Bug]: Cant open astrodux in 1.20.1 with forge

### ISSUE THREAD

**Issue by water-mi** [terrarium-earth/Ad-Astra#324]
### Bug Description

i cant open astrodux though i've installed a 1.20.1 patchouli mod.
I cannot decide it's a patchouli's bug or an ad-astra's bug

### How to Reproduce?

Install Patchouli
Get Astrodux
Open Astrodux

### Version

1.15.1

### Mod Loader Version

1.20.1-47.0.45

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by water-mi** [comment]
maybe it's because the 1.20 patchouli has a new file structure

**Comment by water-mi** [comment]
[this is how ars-nouveau updated](https://github.com/baileyholl/Ars-Nouveau/commit/9192908cf57c4b03ca43cff3a5cb21c39a79c81b)
i don't know weather it's proper to refer to another mod here.

**Comment by Ellf** [comment]
This is also the case for Fabric version 1.15.1.

**Comment by Taleuxss** [comment]
i have the same problem

**Comment by AlexNijjar** [comment]
Fixed in latest version
