### ISSUE TITLE
[Bug]:  Missing Trims from Ostrum, Desh, Calorite - 1.20.1 Forge

### ISSUE THREAD

**Issue by zachsai** [terrarium-earth/Ad-Astra#325]
### Bug Description

Please add trims compatibility for ingots from your mod.
Thanks

### How to Reproduce?

try and use ingot for trim

### Expected Behavior

trim works

### Version

1.15.1

### Mod Loader Version

47.1.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Linksapprentice** [comment]
install the mod All the Trims by Bawnorton. It adds compat between trims and all modded armor

**Comment by AlexNijjar** [comment]
I assume the ad astra space suit armor wouldn’t work as it uses a custom armor model and renderer
