### ISSUE TITLE
[Feature Request]:  Stellar View Mod Compat

### ISSUE THREAD

**Issue by zachsai** [terrarium-earth/Ad-Astra#329]
### Is your feature request related to a problem?

Hi,
Could you add compatibility with Stellar view to use their sky system if the mod is present?

### Solution(s)

Use their sky renderer for the beautiful dynamic star systems it creates

### Describe alternatives you've considered

a config to toggle on or off ad astra sky renderer so that the stellar view one can be used

### Mod Version

1.20.1-1.15.2

### Mod Loader Version

47.1.1

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
This seems out of scope for ad astra. an addon mod that added this would be better
