### ISSUE TITLE
Villages Spawning Above Meteorite [Bug]: 

### ISSUE THREAD

**Issue by HopefulNeko** [terrarium-earth/Ad-Astra#330]
### Bug Description

Hi it appears villages sometimes spawn floating above meteors.

![image](https://github.com/terrarium-earth/Ad-Astra/assets/139850143/df55bd5d-fadf-4134-a48a-e83247b46fe7)

### How to Reproduce?

kinda just found it this way

### Expected Behavior

for village to not float above a meteorite

### Version

1.20.1

### Mod Loader Version

Forge - 47.1.33

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Removed meteors in 1.15.7
