### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GmanAtheist** [terrarium-earth/Ad-Astra#334]
### Bug Description

MC 1.19.2 crash at start. Using , ad_astra-forge-1.19.2-1.12.7, botarium-forge-1.19.2-1.8.2. resourcefullib-forge-1.19.2-1.1.24 , resourcefullib-forge-1.19.2-1.1.24 . Forge 43.2.3. OCULUS mod and RUBIDIUM.
System I9 cpu, 64GB DDR, GeForce RTX 3090 - Suprim 24GB Vram. SSD 
Please help.
Crash log: 
http://www.gmanatheist2022.co.uk/Testarea/Ad%20astra%20crash%20log.txt
Thanks

### How to Reproduce?

Start MC 1.19.2

### Expected Behavior

Game to start

### Version

ad_astra-forge-1.19.2-1.12.7

### Mod Loader Version

1.19.2 - Forge 43.2.3

### Mod Loader

Forge

### Logs or additional context

http://www.gmanatheist2022.co.uk/Testarea/Ad%20astra%20crash%20log.txt 

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I can't open your link. 1.19.2 is no longer supported and we remade the mod in 1.20.1 so try that version
