### ISSUE TITLE
[Bug]: nothing in planet selection menu

### ISSUE THREAD

**Issue by Xplodin** [terrarium-earth/Ad-Astra#335]
### Bug Description

upon adding a custom dimension via datapack it seems all others broke

![2023-07-24_10 43 19](https://github.com/terrarium-earth/Ad-Astra/assets/13007677/3f62d7b4-0ab9-4b4c-955f-7e91b8acb148)

### How to Reproduce?

add a custom ad astra dimension via datapack/resourcepack
watch nothing appear in the catalog

### Expected Behavior

be able to visit the moon at least with t1 rocket

### Version

1.12.7

### Mod Loader Version

1.19.2 43.2.14

### Mod Loader

Forge

### Logs or additional context

nothing besides normal behavior for logs

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.
tested planetgui and the moon is gone so is earth.
but all others except custom appeared

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7. We redid the planet datapack stuff
