### ISSUE TITLE
[Feature Request]: Alpha Centauri's Skyboxes should have 3 stars 

### ISSUE THREAD

**Issue by Linksapprentice** [terrarium-earth/Ad-Astra#336]
### Is your feature request related to a problem?

IRL alpha Centauri is a tertiary star system consisting of Proxima Centauri, Rigil Kentaurus , and Toliman (AKA alpha centauri B).

### Solution(s)

add two more stars to the alpha Centauri skybox. These could be purely cosmetic, or you could do a neat little reference to the cult favorite sci-fi series Three Body, and have the interactions between the three stars mess with the gravity and temperature of Glacio or any future planned planets. 

### Describe alternatives you've considered

While Alpha Centauri is technically a tertiary star system, it is much better known as a binary star system in the public eye, because for awhile Proxima Centauri and Alpha Centauri were thought to be two star systems close togother, instead of one star system. So you could hypothetically just add one more star to the skybox; this however, is not ideal.

### Mod Version

1.15.2

### Mod Loader Version

1.20.1 - 47.1.3

### Mod Loader

Forge

### Additional context

I'm listing the version I'm using to be thorough, but it shouldn't have anything to do with the feature request.

**Comment by Noobly-Walker** [comment]
Rigil Kentarus and Toliman would appear as faint points from Proxima's system. Definitely much brighter than any of the other background stars, including Sol, but finding them in Glacio's sky would be difficult.

**Comment by AlexNijjar** [comment]
We're actually going to be removing Alpha Centauri in a future update. In the meantime that dimension will not receive any more content updates

**Comment by Noobly-Walker** [comment]
Any reason in particular for the removal? Just curious.

**Comment by AlexNijjar** [comment]
It was originally part of Beyond Earth, the mod ad astra was forked from. It serves no purpose other than to hold one useless planet with no content. We'd rather focus on improving the content of the existing planets rather than simply adding new empty planets for the sake of adding planets. As such, there's no point in it existing, at least for what we currently have planned content wise.
