### ISSUE TITLE
[Bug]: Guide Book Doesn't Work

### ISSUE THREAD

**Issue by BraveCaperCat2** [terrarium-earth/Ad-Astra#337]
### Bug Description

When right clicking the book it brings up the error message "install patchouli"
I don't have optifine installed, as you have to install manually without forge and i was trying to make this modpack for me and my friends quickly.

### How to Reproduce?

1. Open Minecraft with the mod
2. Open a world or create a new one
3. Open the book to find the error message.

### Expected Behavior

Book opens with no error message.

### Version

1.12.7

### Mod Loader Version

43.2.21 (latest version available)

### Mod Loader

Forge

### Logs or additional context

[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/12171315/latest.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
did you.. install patchouli?

**Comment by BraveCaperCat2** [comment]
no because i shouldn't need another mod just for a guide book to work. (plus i don't need it for anything else)

**Comment by AlexNijjar** [comment]
what? the entire guidebook was made using patchouli. either install patchouli or don't use the guide book.

**Comment by NotoriousPyro** [comment]
Need a guide just to read the guide...

Searched through all the game items, then came here to find out a certain mod is needed for the guide...
