### ISSUE TITLE
[Bug]:  1.20.1 - Create integration is broken

### ISSUE THREAD

**Issue by zachsai** [terrarium-earth/Ad-Astra#339]
### Bug Description

![image](https://github.com/terrarium-earth/Ad-Astra/assets/63996164/2e7998d0-4b12-4f69-9c76-84fcacb725dd)
![image](https://github.com/terrarium-earth/Ad-Astra/assets/63996164/3e94437d-0181-4646-9524-54cc944875e7)

### Version

1.15.2

### Mod Loader Version

47.1.3

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by zachsai** [comment]
Still broken in ad_astra-forge-1.20.1-1.15.3.jar

**Comment by StormCircuit** [comment]
Pipes have been broken for months now. Is this planned on being fixed?

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7
