### ISSUE TITLE
[Bug]: Astrodux doesn't explain how to get steel ingots

### ISSUE THREAD

**Issue by C4uTi0N** [terrarium-earth/Ad-Astra#340]
### Bug Description

Title is pretty self explanitory

### Version

1.15.2

### Mod Loader Version

1.20.1 - 0.86.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7 with the addition of the Etrionic Blast Furnace
