### ISSUE TITLE
[Bug]: slabs and oxigen distributor 

### ISSUE THREAD

**Issue by TheBigSTN** [terrarium-earth/Ad-Astra#341]
### Bug Description

if you have a base in a non oxigenated planet and your base has an oxigen distributor 
if you place a slab it wont be oxigenated and you whil take damage 

### How to Reproduce?

1 Go to the moon
2 Create a small base 
3 Oxigenate the base with an oxigen distributor
4 Place a slab 
5 Walk on the slab in survival and you whil take damage

### Expected Behavior

take sufocation damage in a oxigenated base

### Version

1.12.6

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Logs or additional context

Mod list:
ad_astra-forge-1.19.2-1.12.6.jar
architectury-6.5.85-forge.jar
botarium-forge-1.19.2-1.8.2.jar
create-1.19.2-0.5.0.i.jar
dankstorage-1.19.2-5.1.6.jar
EdivadLib-1.19.2-1.2.0.jar
ExtraStorage-1.19.2-3.0.1.jar
FluxNetworks-1.19.2-7.1.3.12.jar
ftb-library-forge-1902.3.16-build.193.jar
ftb-ultimine-forge-1902.4.1-build.90.jar
Jade-1.19.1-forge-8.8.1.jar
jei-1.19.2-forge-11.6.0.1016.jar
journeymap-1.19.2-5.9.7-forge.jar
lightmanscurrency-1.19.2-2.1.0.0f.jar
lightmansdiscord-1.19.3-0.1.0.1-server.jar
mc2discord-forge-1.19.x-3.3.0.jar
mcjtylib-1.19-7.2.5.jar
Mekanism-1.19.2-10.3.8.477.jar
MekanismGenerators-1.19.2-10.3.8.477.jar
MekanismTools-1.19.2-10.3.8.477.jar
refinedstorage-1.11.6.jar
refinedstorageaddons-0.9.0.jar
resourcefulconfig-forge-1.19.2-1.0.20.jar
resourcefullib-forge-1.19.2-1.1.24.jar
rftoolsbase-1.19-4.1.7.jar
rsrequestify-2.3.0.jar
StorageDrawers-1.19-11.1.2.jar
xnet-1.19-5.1.4.jar
xnetgases-1.19.2-4.0.1.jar

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Give it a try in 1.15.7. We improved the oxygen distribution algorithm.
