### ISSUE TITLE
[Feature Request]: Different solution to first-person spacesuit bug

### ISSUE THREAD

**Issue by emoandproud** [terrarium-earth/Ad-Astra#343]
### Is your feature request related to a problem?

https://github.com/terrarium-earth/Ad-Astra/issues/112

### Solution(s)

              it renders with the enchanted renderer so it may have worked at one point but doesn't anymore, ad astras one specifically uses the enchanted vertex buffer so that may have broken separately but create renders theirs solid full bright nothing else so that is likely why theirs works fine because no shader should ever touch the solid renderer

_Originally posted by @ThatGravyBoat in https://github.com/terrarium-earth/Ad-Astra/issues/299#issuecomment-1574038900_
            

Wouldn't it make more sense to add a config option to not use the enchanted renderer instead of removing the custom model entirely? I'd rather be able to see the spacesuit in first person without the enchantment glint than either this or my normal hand:
 
![2023-08-01_21 07 14](https://github.com/terrarium-earth/Ad-Astra/assets/120610938/c4b1fb42-f085-420e-bee9-10fce16662bf)

### Describe alternatives you've considered

i could just cop it ig

### Mod Version

1.15.3

### Mod Loader Version

1.20.1 - 0.14.21

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7. Tested with Complementary and BSL
