### ISSUE TITLE
[Bug]: All of the mod's fluids are broken

### ISSUE THREAD

**Issue by DanonDan630** [terrarium-earth/Ad-Astra#345]
### Bug Description

Can't use any liquid, no other mods installed, I tried on versions 1.19.2 and 1.20.1 and on both versions they don't work. At the same time, if you use a water pump, you can pump water into the oxygen loader

### How to Reproduce?

Just try using liquids

### Version

1.15.2

### Mod Loader Version

1.20.1-0.14.22

### Mod Loader

Fabric

### Logs or additional context

https://github.com/terrarium-earth/Ad-Astra/assets/58370587/4e02f66d-88ca-49a8-9ed7-fdbade992985

https://github.com/terrarium-earth/Ad-Astra/assets/58370587/a2f5492a-e57f-4cdb-b937-891e2f9fbfa1

https://github.com/terrarium-earth/Ad-Astra/assets/58370587/7cedf223-68ce-4cdc-b813-bd24f569fb23

https://github.com/terrarium-earth/Ad-Astra/assets/58370587/e901c68b-1697-4c1c-8466-aa6f82c1e4ce

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by WhatamIdoin2024** [comment]
I have this exact same issue and neither 1.20.1 or 1.19.2 versions are working for me.

**Comment by AlexNijjar** [comment]
I'm unable to reproduce this. Testing on 1.20.1 with ad astra 1.15.3 on fabric. maybe you're using an old config file? try on a brand new instance
<img width="1512" alt="Screenshot 2023-08-06 at 9 03 43 PM" src="https://github.com/terrarium-earth/Ad-Astra/assets/61668546/8aae8efa-3b93-477c-ab71-3b94695ec616">
<img width="1512" alt="Screenshot 2023-08-06 at 9 05 09 PM" src="https://github.com/terrarium-earth/Ad-Astra/assets/61668546/5268f783-7a11-4421-baee-6a9d182fc4d2">

**Comment by AlexNijjar** [comment]
For anyone else having this issue, it's most likely caused by an outdated config or using a config from a different platform, since fluid units are different on fabric and forge. It's fixed in 1.15.7+ as we just use MBs in the config for both platforms now
