### ISSUE TITLE
[Bug]: "you do not own this flag"

### ISSUE THREAD

**Issue by F1leL0aded** [terrarium-earth/Ad-Astra#347]
### Bug Description

I am on a mc server where is this mod and when I rightclick flag that I placed and crafted, "You do not own this flag" appears and I don't know how to fix it. please hep :(

### Version

1.20.1

### Mod Loader Version

1.20.1-forge-47.1.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by antoni0C0des** [comment]
I have this bug too! You're not alone 🥲🥲🥲

**Comment by AlexNijjar** [comment]
Only the placer of the flag can interact with it. If that's not working, you should be able to just break and place it again. We also improved the logic a bit in v1.15.7+ so that shouldn't happen anymore

**Comment by nicolasgomez1** [comment]
This is never fixed for 1.20.1 right? cuz my server in 1.20.1-1.15.18 version and we have the same issue.

**Comment by antoni0C0des** [comment]
Are you in offline mode?

**Comment by nicolasgomez1** [comment]
> Are you in offline mode?

Yes, the server in running in online mode false

**Comment by TomasBeron** [comment]
Same issue here, 1.20.1 too

**Comment by SugomBus** [comment]
same
