### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by xiaozhou123123** [terrarium-earth/Ad-Astra#348]
### Mod Version

4.1

### Mod Loader Version

1.19.4

### Additional context

是否有考虑添加boos,本人特别希望能添加boos，从而增加目标和趣味性

**Comment by KLONOA9X6** [comment]
Translation: 
Is it possible to add a boss?

**Comment by KLONOA9X6** [comment]
> 是否有考虑添加boos,本人特别希望能添加boos，从而增加目标和趣味性

暂时不会

**Comment by CodexAdrian** [comment]
No, adding a boss would require your own mod
