### ISSUE TITLE
[Feature Request]: large doors suffocate you

### ISSUE THREAD

**Issue by Katranune** [terrarium-earth/Ad-Astra#350]
### Is your feature request related to a problem?

Closed doors suffocate you

### Solution(s)

Make closed doors that are oxygenated on both sides also oxygenated instead of only when they are open

### Describe alternatives you've considered

detect if each side of the door is oxygenated and oxygenate that side accodingly

### Mod Version

1.12.7

### Mod Loader Version

1.19.2 - 43.2.21

### Mod Loader

Forge

### Additional context

idk itd just be nice

anyways thanks

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7
