### ISSUE TITLE
[Bug]: Oxygen Distributor is not working properly.

### ISSUE THREAD

**Issue by ImThatguy733** [terrarium-earth/Ad-Astra#358]
### Bug Description

When I use the Oxygen Distributor it turns on and off for no reason, it says that there is not enough energy or oxygen, but both of those are full.

### How to Reproduce?

1. place oxygen generators
2. give oxygen generators power and water/liquid O2
3. It will turn on and off.

### Version

1.12.7

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Give it a try in 1.15.7.
