### ISSUE TITLE
[Bug]: Space Station not functioning

### ISSUE THREAD

**Issue by DruBrandon** [terrarium-earth/Ad-Astra#360]
### Bug Description

Once you launch off of the space station after creation it requires you to submit the materials again to create it and resets any build progress on it

### How to Reproduce?

1. Submit Materials to create space station
2. Arrive at Space station and build something
3. Leave space station via rocket
4. Attempt to go back to already built space station

### Expected Behavior

Not have to submit materials again and for build progress to stay 

### Version

1.20.1-1.15.3

### Mod Loader Version

0.231.1.12152

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
pressing the space station button just builds another space station. you need to press the orbit button which will spawn you in orbit where your built space station already is.

**Comment by DruBrandon** [comment]
Okay, thank you for letting me know! I didn't realize it! Sorry for the trouble!
