### ISSUE TITLE
[Bug]: Create: Astral fuel refinery not working

### ISSUE THREAD

**Issue by LordSluggo** [terrarium-earth/Ad-Astra#361]
### Bug Description

The fuel refinery does not process oil into fuel

### How to Reproduce?

1. Place a fuel refinery (Ad Astra) with an input for oil
2. Place an electrical generator  (Ad Astra, Tech Reborn)
3. Verify both oil and electricity are loaded into the refinery
4. Observe oil not being converted into fuel

### Expected Behavior

For oil to be converted into fuel
![2023-08-22_21 16 05](https://github.com/terrarium-earth/Ad-Astra/assets/51515044/0b8f337a-790d-4643-aa14-47393b3e40ec)

### Version

1.0.9

### Mod Loader Version

0.14.14

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
please report this to Create: Astral. Also, 1.18 is no longer supported
