### ISSUE TITLE
[Bug]:  the oxygen loader won't work on the latest fabric version

### ISSUE THREAD

**Issue by rizzlite** [terrarium-earth/Ad-Astra#362]
### Bug Description

when try to use the oxygen loader by putting a water bucket in the left slot it wouldn't transfer through it acted like there was no water in there even though there was and yes the oxygen loader was fully powered 

### How to Reproduce?

1. make an oxygen loader and power it
2. put a water bucket in the left slot

### Expected Behavior

the water would go through and make oxygen

### Version

ad_astra-fabric-1.20.1-1.15.3.jar

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Give it a try in 1.15.7
