### ISSUE TITLE
[Bug]: Baby Glacian Rams walks and looks backwards

### ISSUE THREAD

**Issue by Shazuli** [terrarium-earth/Ad-Astra#365]
### Bug Description

Baby Glacian Rams walk backwards look at stuff with the back of their head.

### How to Reproduce?

1. Spawn a Baby Glacian Ram.
2. Let them pathfind.
3. Beyhold the interstellar moonwalk.

### Expected Behavior

Not doing the moonwalk.

### Version

1.15.3

### Mod Loader Version

1.20.1 - 0.14.22

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Glacian rams are being removed in a future update. As such they will not longer receive any support and should be considered legacy mobs
