### ISSUE TITLE
[Bug]: Translation error (cringe alert)

### ISSUE THREAD

**Issue by beliboba** [terrarium-earth/Ad-Astra#366]
### Bug Description

![image](https://github.com/terrarium-earth/Ad-Astra/assets/73661136/6ca7824e-0f4e-4c94-9618-c358eb0f76cf)
Russian translation is just hilarious

"Камень с метиорита" - с should not be used here obviously, the translation is just wrong. `метиорита` is a misspelled `метеорита`.

### Expected Behavior

Метеоритный камень

### Version

idk

### Mod Loader Version

43.2.3

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I believe someone fixed that already, however I can't really verify as I don't know the language.
