### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Dav-Lec** [terrarium-earth/Ad-Astra#367]
### Is your feature request related to a problem?

If we want to integrate this mod into realistic gameplay, certain structures such as temples on Mars are not suitable.

### Solution(s)

It would be interesting to be able to disable the generation of structures in the config file, like for mobs.

### Describe alternatives you've considered

Perhaps better, being able to change the patterns of these structures.

### Mod Version

1.15.3

### Mod Loader Version

47.1.10

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
all structures are done via datapack and can be removed like any other structure in the game, either with kubejs or a datapack that disables the structures
