### ISSUE TITLE
[Bug]: A bug correlating with powder snow that could cause crash

### ISSUE THREAD

**Issue by tenshi97** [terrarium-earth/Ad-Astra#368]
### Bug Description

When I accidently pour a bucket of fuel on a large area of powder snow on the Galacia Planet,the game crashed(reproducable)
Strangely my game doesn't crash when I do same thing on earth

![QQ图片20230918195350](https://github.com/terrarium-earth/Ad-Astra/assets/47095775/f735eedb-7965-4b0d-98ec-99f7fc92e365)

### How to Reproduce?

1.Find a large area of power snow on glacia planet
2.Put down a bucket of fuel
3.Game Crash

### Version

1.15.3

### Mod Loader Version

1.20.1-47.1.47

### Mod Loader

Forge

### Logs or additional context

[minecraft-exported-crash-info-2023-09-18T19-48-44.zip](https://github.com/terrarium-earth/Ad-Astra/files/12647404/minecraft-exported-crash-info-2023-09-18T19-48-44.zip)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by tenshi97** [comment]
"Put down" means right click to a power snow with a bucket of fuel in hand

**Comment by AlexNijjar** [comment]
Give it a try on 1.15.7
