### ISSUE TITLE
[Bug]: Spacesuit arms aren't affected by light

### ISSUE THREAD

**Issue by whatsthedealwithairlinefood** [terrarium-earth/Ad-Astra#369]
### Bug Description

All the spacesuits custom arms aren't affected by light
![2023-09-21_10 17 40 - Copy](https://github.com/terrarium-earth/Ad-Astra/assets/144437009/ac837484-4dd2-45a4-8dbe-c51efc45dd19)

### How to Reproduce?

1. Put on a spacesuit
2. Look at your arm

### Expected Behavior

Normal arm

### Version

1.15.3

### Mod Loader Version

1.14.21-1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7
