### ISSUE TITLE
[Bug]: Oxygen Loader Not Working perfectly in SteamPunk Modpack

### ISSUE THREAD

**Issue by LamaraFPS** [terrarium-earth/Ad-Astra#372]
### Bug Description

oxygen loader is broken in steampunk [lps] modpack at least watch the 2 videos 

### How to Reproduce?

https://github.com/terrarium-earth/Ad-Astra/assets/134687594/c45557ae-544b-4bf8-ad99-2f367143ce7d

https://github.com/terrarium-earth/Ad-Astra/assets/134687594/9e744f07-439e-4a64-8ce8-bcfbd7d46298

### Version

ad_astra-forge-1.19.2-1.12.7

### Mod Loader Version

1.19.2 43.2.23

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I believe you mentioned that this fixed itself, so I'll close the issue.
