### ISSUE TITLE
[Bug]: The "Origins" mod breaks oxygen

### ISSUE THREAD

**Issue by D4meno** [terrarium-earth/Ad-Astra#373]
### Bug Description

While playing on a personal modpack, the following problem was revealed: the Origins mod completely breaks oxygen. Items have an NBT tag about their oxygen content, but when you move the item into your inventory it shows "0/500 oxygen". If you place such an “empty” object in an oxygen loader, it will show “500/500 oxygen”. But there will always be 0 in your inventory, even if you somewhere in space. And nope, this isn't only visible bug, game doesn't see oxygen too

I tried to look in the logs for information, but there is nothing about this, as if the game perceives this normally. Sad

### How to Reproduce?

1. Just play with Origins (Forge Version, with Caelus) and Ad Astra
2. Choose any origin
3. Just fill something with Oxygen using oxygen loader
4. Place in your inventory that object (like suit or oxygen tank) and you'll see that oxygen is zero.

### Version

1.15.3

### Mod Loader Version

1.20.1 NeoForge 47.1.79 (and Forge 47.2.0)

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [x] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by DanDragonWolf** [comment]
This also happens with energy, anything that's fully charged shows as 0 energy in your inventory and acts like it has no energy.

**Comment by AlexNijjar** [comment]
I'm not sure how this could be happening. We use normal forge energy and fluid. Can you give it a try on 1.15.7, and with Botarium 2.3.1?

**Comment by AlexNijjar** [comment]
Closing as I have not had any other reports with this in the newer updates
