### ISSUE TITLE
[Bug]: Item Transporters (pipes etc.) won't connect to Cryo Freezer

### ISSUE THREAD

**Issue by rCane0714** [terrarium-earth/Ad-Astra#374]
### Bug Description

I tried pumping ice from all sides into my Cryo Freezer to create cryo fuel but neither Mekanism transporters, nor LaserIO nodes, nor PipeZ pipes will connect to the Cryo Freezer.

If I use a standard Minecraft hopper or the Blast Chiller from Thermal directly next to the Cryo Freezer instead, items get pushed into it just fine.

So I assume it has something to do with inventories pushing something into the Cryo Freezer directly vs all kinds of item transporters.

The example with Mekanism, other pipes have the same issue:
![2023-09-29_15 13 50](https://github.com/terrarium-earth/Ad-Astra/assets/36411556/4338fede-32d5-4dff-b809-93cd145dc4c1)

### How to Reproduce?

1. Place powered Cryo Freezer
2. Try to connect and kind of pipe/item transporter

### Expected Behavior

The pipe/transporter should connect to the Cryo Freezer and the item (Ice, Ice Shard) should be put in the correct slot (bottom left)

### Version

1.12.7

### Mod Loader Version

1.19.2

### Mod Loader

N/A

### Logs or additional context

I am not using the forge loader,  I am using the FTB App.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Give it a try in 1.15.7
