### ISSUE TITLE
[Feature Request]:  Config option to disable Ad Astra meteors

### ISSUE THREAD

**Issue by Gune02** [terrarium-earth/Ad-Astra#375]
### Is your feature request related to a problem?

I would like to be able to disable the meteor structures generated in the overworld as they cause confusion when used with Applied Energistics meteors.

### Mod Version

1.20.1 - 1.15.3

### Mod Loader Version

47.1.44

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
see #149
