### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by leoguigon** [terrarium-earth/Ad-Astra#377]
### Bug Description

Every block we try to put is automatically despawning
Only the astrodux is working, but when we try tu put any block from the mod on the ground is despawning in the same second, does anybody know why ?

### Version

1.20.1

### Mod Loader Version

1.15.4

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Seems like some kind of registry desync? Make sure you're using the same versions of everything on the client and server with the same configs.
