### ISSUE TITLE
[Bug]: fuel simply won't leave it's container without interference from players

### ISSUE THREAD

**Issue by Skellykenz** [terrarium-earth/Ad-Astra#381]
### Bug Description

fuel cannot be extracted through pipes or hopper

### How to Reproduce?

put oil in the fuel refiner
power the fuel refiner
use any possible method of removing fuel without opening the fuel refiner

### Expected Behavior

you place a pipe underneath it and fuel comes out

### Version

1.15.4

### Mod Loader Version

47.1.3

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by DaveDevil** [comment]
I do conferm the same problem in 1.19.2, mod version ad_astra-forge-1.19.2-1.12.7

**Comment by AlexNijjar** [comment]
Should be fixed in 1.15.7
