### ISSUE TITLE
[Feature Request]: include crafting recipes for oxygen tank and oxygen gear

### ISSUE THREAD

**Issue by griato** [terrarium-earth/Ad-Astra#382]
### Is your feature request related to a problem?

noticing a lack of oxygen tank & oxygen gear crafting recipes anywhere on the internet, would appreciate having them in the book

### Mod Version

1.20.1

### Mod Loader Version

1.15.4

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
You can just use JEI/REI to view recipes. It's impractical to add all important recipes to the book.
