### ISSUE TITLE
[Bug]: Machines work with the same speed regardless of the amount of energy they are supplied with

### ISSUE THREAD

**Issue by ItsRBus** [terrarium-earth/Ad-Astra#383]
### Bug Description

As the name says, machines produce oxygen, convert oil to fuel etc. at the same rate, even if they are given less FE than they require to operate.

### Expected Behavior

When supplied with not enough energy Machines should be less efficient or not work at all, obviously

### Version

1.12.7

### Mod Loader Version

1.19.2 - 43.2.21

### Mod Loader

Forge

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7
