### ISSUE TITLE
[Bug]: no rain sound in 1.18.2

### ISSUE THREAD

**Issue by Manuelmc71** [terrarium-earth/Ad-Astra#384]
### Bug Description

I don't exactly know why it causes the rain sound to disappear, but for some reason when this mod is installed, you won't be able to hear the rain.

### How to Reproduce?

1. have ad Astra for version 1.18.2 in mod folder with all required mods
2. launch any type of game
3. witness the lack of rain sound.

### Expected Behavior

If possible, it would be great if you could make it so rain audio works.

### Version

1.0.9

### Mod Loader Version

1.18.2 - 0.14.22

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
1.18.2 is not longer supported.
