### ISSUE TITLE
[Bug]: Glitched Lunarian Models

### ISSUE THREAD

**Issue by The-Artificer** [terrarium-earth/Ad-Astra#385]
### Bug Description

![image](https://github.com/terrarium-earth/Ad-Astra/assets/46545464/642cc71c-d183-492d-b5ba-0856d5073de8)
All Lunarians appear like this.

### How to Reproduce?

1. Spawn in a Lunarian
2. Look at them

### Expected Behavior

Body cube in correct position

### Version

1.12.7

### Mod Loader Version

1.19.2 - 43.3.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Any rendering mods installed? model mods? optimization mods? It's not happening normally so you must have something that's messing with it. 1.19.2 is no longer supported so if it's still happening in 1.20.1 let me know
