### ISSUE TITLE
[Bug]: When adding planet ids to be disabled it resets upon startup

### ISSUE THREAD

**Issue by AGUrGrill** [terrarium-earth/Ad-Astra#387]
### Bug Description

I have tried adding the planet ids to be disabled multiple times and every time I start Minecraft again, it resets the config file. Not sure what's wrong, as all other configs I have modified are not functioning this way. 

### How to Reproduce?

type ids of planets into the "disabledPlanets" section of the config 

### Expected Behavior

planets to stay disabled in config

### Version

 ad_astra-forge-1.20.1-1.15.4.jar

### Mod Loader Version

forge 47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1.15.10
