### ISSUE TITLE
[Bug]: botarium mod causes the game to crash

### ISSUE THREAD

**Issue by CaptainDrak3** [terrarium-earth/Ad-Astra#390]
### Bug Description

When I installed ad Astra to my game it automatically installed the support mod botarium in order to work. Then I we t and launched the game and it worked fine. Then I created a world and loaded into it and that worked fine as well. Though when I went to open my inventory the game froze and then crashed. It did this four times. I went and looked at the crash report and it said that the problem had something to do with botarium. U hope this will be able to be fixed so I can use the mod

### How to Reproduce?

1. Go to curseforge and install ad Astra.
2. If it did not automatically install, install botarium and all the other mods required for ad Astra to work.
3. Launch minecraft.
4. Create a world.
5. Join the world.
6. Try to open your inventory.

### Expected Behavior

When you try and open your inventory the game should free for a couple of seconds and then crash. When minecraft crashes it should show a crash report. When you go to the crash report it should say something about botarium not working.

### Version

1.20.1

### Mod Loader Version

1.20.1-1.15.4

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by davidporras31** [comment]
I have this exact same issue when i use [Minecraft-Transit-Railway](https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway).

**Comment by CaptainDrak3** [comment]
Ive determined that if I changed to an earlier version of the newest version of ad astra and botarium it works

**Comment by AlexNijjar** [comment]
This is transit railway's issue. https://github.com/terrarium-earth/Botarium/issues/28
