### ISSUE TITLE
[Bug]: Render Thread Crash With Custom Fluid Buckets From Thingamajigs Mod

### ISSUE THREAD

**Issue by CreativeMasterBonin** [terrarium-earth/Ad-Astra#394]
### Bug Description

An _instant crash_ when right clicking another mod's fluid bucket in an oxygen filled room on another planet.
Without oxygen the bucket items and fluids place (overworld, nether, the end).

In Ad Astra dimensions specifically, with oxygen in a closed room or if the planet naturally has oxygen, the game will crash when a bucket item is used from Thingamajigs.

On Mars and planets without oxygen, the fluid places and immediately freezes, not causing a crash.

**Installed Mods:** 
_Ad Astra (and dependencies)
Thingamajigs 1.6.6_

### How to Reproduce?

1. Fly to an Ad Astra planet.
2. Build and fill a closed room with oxygen (or go to Glacio).
3. Place a fluid bucket from Thingamajigs in the oxygen filled room.
4. The game will instantly crash.

### Expected Behavior

The fluid bucket item places the fluid or the fluid freezes into ice when the bucket item is right clicked on a block.

### Version

1.15.4

### Mod Loader Version

1.20.1-47.2.0

### Mod Loader

Forge

### Logs or additional context

Crash Report: https://pastebin.com/wuypDFPY

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7
