### ISSUE TITLE
[Feature Request]:  Overworld

### ISSUE THREAD

**Issue by Tomatoh** [terrarium-earth/Ad-Astra#395]
### Is your feature request related to a problem?

Can you alter  code to allow for overworld cloud and weather rendering changes? Like I do not want any clouds for minecraft:overworld aka earth?

### Mod Version

forge-1.20.1-1.15.4

### Mod Loader Version

1.20.1-47.2.1

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
Why? this has nothing to do with Ad Astra. just disable clouds
