### ISSUE TITLE
[Bug]: oxygen wont stay on my tanks or suit

### ISSUE THREAD

**Issue by nuhuhuhuh** [terrarium-earth/Ad-Astra#398]
### Bug Description

whenever i load my oxygen tanks or space suit with oxygen on the oxygen loader, when i put them in my inventory all the oxygen is gone and when i try to refill it with oxygen it shows its full at the oxygen loader, when i equip the armor it shows 0 oxygen and doesnt let me breathe on the moon, these are the mods im using:
![image](https://github.com/terrarium-earth/Ad-Astra/assets/149548082/6c6b7c6d-3842-4f41-a583-7c2ecdcd7d52)
![image](https://github.com/terrarium-earth/Ad-Astra/assets/149548082/2c0a8a81-3841-40b1-88d1-515769d70a2a)
![image](https://github.com/terrarium-earth/Ad-Astra/assets/149548082/737dce7c-d3da-4c62-9138-30eb5e0b923a)
![image](https://github.com/terrarium-earth/Ad-Astra/assets/149548082/4d8093f1-a5f4-48a5-8e70-f491201d6e9d)

### How to Reproduce?

1. place oxygen tanks or space chestplate on the oxygen loader with oxygen in it
2. take it out when its ''full''
3. thats it i think

### Expected Behavior

when i load something with oxygen its supposed to stay full of oxygen

### Version

1.15.4.

### Mod Loader Version

minecraft 1.20.1 forge 47.2.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Can you give it a try in 1.15.7+? If it's still happening reopen the issue
