### ISSUE TITLE
[Feature Request]: "Rocketable" Dimensions

### ISSUE THREAD

**Issue by EvilParagon9999** [terrarium-earth/Ad-Astra#401]
### Is your feature request related to a problem?

I'm currently making a modpack and some consistency with how the world works would be nice to customise.

### Solution(s)

It should be configurable to set which dimensions allow rockets to take off and which don't. By default I would imagine the Nether and End set to false with the Overworld set to true, but with it being a config, these could be changed based on modpack author's choice as well as adding modded dimensions, such as in my instance, disabling the overworld and making the Aether the only way to rocket into space.

Additionally, smaller requests would be like, return dimensions, ie, if you fall from space to the overworld, what dimension you end up in. This way if you have multiple rocketable dimensions, you could always select the same dimension to fall back down to.

This is all assuming only Earth has these characteristics.

### Mod Version

1.12.7

### Mod Loader Version

1.19.2

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7. Now by default, rockets can only be launched from Ad Astra planets. And there's a new config option called "launchFromAnywhere" that allows rockets to be launched from non-planets.
