### ISSUE TITLE
[Feature RIequest]:  API

### ISSUE THREAD

**Issue by Tomatoh** [terrarium-earth/Ad-Astra#403]
### Is your feature request related to a problem?

I would like to have an API so we could more easily link to your mod especially globes, flags, paintings, planets

### Solution(s)

An API would be helpful to mod pack creators

### Mod Version

forge-1.20.1-1.15.4

### Mod Loader Version

1.20.1-47.2.1

### Mod Loader

Forge

### Additional context

This is just a suggestion

**Comment by AlexNijjar** [comment]
Added a few APIs and events for various things in 1.15.7
