### ISSUE TITLE
[Bug]: FPS Drop with armor on 

### ISSUE THREAD

**Issue by Jafooleryy** [terrarium-earth/Ad-Astra#405]
### Bug Description

I was using the astronaut armor from this mod when I noticed my fps was halved. I normally have 140 fps but with the armor on my fps went down to 80. Is there a fix I could do? I provided my other mods below.

3D Skin Layers
Adaptive Tooltips
Advancement Plaques
AmbientSounds
Amplified Nether
AppleSkin
Architectury API
Better Advancements
Better End Cities (Vanilla)
Better Ping Display (Fabric)
Better Third Person
Borderless Mining
CIT Resewn
CameraOverhaul
Chat Heads
ChoiceTherorem's Overhauled Village
Chunksending Mod
Collective
Continuity
Cosmetica
Craftify
CreativeCore
Cristel Lib
Double Doors
Drippy Loading Screen
Dungeons and Taverns
Dungeons and Taverns Ancient City Overhaul
Dungeons and Taverns Pillager Outpost Rework
Dynamic Crosshair
EMI
EMI Addon: Extra Mod Integrations
ESSENTIAL Mod
Eating Animation
Enhanced Block Entities
Euphoria Patches
FPS - Display
Fabric API
Fabric Language Kotlin
Falling Leaves
Fancy Menu
FerritCore
FIrst-person Model
Forge Config API Port
Freecam (Modrinth Edition)
Geckolib
Gpu memory leak fix mod
Iceberg
Immersive Structures
Indium
InvMove
Inventory Profiles Next
Iris Shaders
Item Highlighter
Jade Addons (Fabric)
Jade
JamLib
Just Enough Items
Konkrete
Krypton
Let Me Despawn
Let's Do: API
Litematica
Lithium
MaLiLib
Memory Leak Fix
Mod Menu
More Culling
Mouse Tweaks
Naturalist
Not Enough Animations
Overflowing Bars
Paxi
Presence Footsteps
Puzzle Lib
Reese's Sodium Options
RightClickHarvest
Shoulder Surfing Reloaded
Show Me Your Skin!
Shulker Box Tooltip
Simple Voice Chat
Smoothchunk mod
Sodium
Sodium Extra
Sonance
Sound Physics Remastered
Status Effect Bars
Towers of the Wild: Reworked
Towns and Towers
Traveler's Titles
Vanilla Refresh
Very Many Players (Fabric)
Xaero's Minimap
Xaero's World Map
YDM's Weapon Master
YUNG's API
YUNG's Better Desert Temples
YUNG's Better End Island
YUNG's Better Jungle Temples
YUNG's Better Mineshaft
YUNG's Better Nether Fortresses
YUNG's Better Ocean Monuments
YetAnotherConfigLIb
Zoomify
[EMF] Entity Model Features
[ETF] Entity Texture Features
betterfpsdist mod
cupboard
libIPN

### How to Reproduce?

1. Grab Astronaut Armor
2. Put It On

### Expected Behavior

Should not lower fps

### Version

1.15.4

### Mod Loader Version

1.20.1 - 0.14.24

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Give it a try on 1.15.7
