### ISSUE TITLE
[Bug]: Not compatible with CanvasRenderer

### ISSUE THREAD

**Issue by morrussa** [terrarium-earth/Ad-Astra#407]
### Bug Description

Starting play the globe in the inventory

### How to Reproduce?

block also had but globes in the block state will not be rendered correctly, but it will not cause crashes(without block)

### Expected Behavior

I've seen the code, and adastra had its own class implementation for renderer
Under forge files, I instead see compatible code for other renderer compailnt
Its not optifine so i would reported

### Version

1.15.4

### Mod Loader Version

1.20.1 fabric 0.14.24

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Can you give it a try in 1.15.7? if it's still happening, reopen the issue. but most rendering-related issues should be fixed in that version.

**Comment by morrussa** [comment]
NP
