### ISSUE TITLE
[Bug]: Your Maven is not functioning properly

### ISSUE THREAD

**Issue by baka4n** [terrarium-earth/Ad-Astra#409]
### Bug Description

repo： maven { url "https://maven.resourcefulbees.com/repository/maven-public/" }

dep:  modImplementation("earth.terrarium.adastra:ad_astra-forge-1.19.2:1.12.7")

error:Could not find earth.terrarium.adastra:ad_astra-forge-1.19.2:1.12.7

### Version

all

### Mod Loader Version

all

### Mod Loader

N/A

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Older versions of Ad Astra were published to the maven manually so I probably forgot to upload that one. It'll work now.
