### ISSUE TITLE
[Error]: In Architectury 1.19.2 forge could not properly log into the loom environment.

### ISSUE THREAD

**Issue by baka4n** [terrarium-earth/Ad-Astra#410]
### Bug Description

![image](https://github.com/terrarium-earth/Ad-Astra/assets/60695447/0fe89688-501c-41d3-a65a-632fa522cc5d)

### Version

all

### Mod Loader Version

1.19.2-lastversion

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by baka4n** [comment]
I think I should fork the warehouse and fix it myself and then pull it in.

**Comment by AlexNijjar** [comment]
published in 1.12.8
