### ISSUE TITLE
[Bug]: when going in the planetGUI menu with a 0 tier rocket, there is a strange image

### ISSUE THREAD

**Issue by Geming400** [terrarium-earth/Ad-Astra#413]
### Bug Description

When you execute the command `/planetgui @s 0`, you can see something that you shouldn't see, like shown below.
![image](https://github.com/terrarium-earth/Ad-Astra/assets/101340400/73dedfb4-f81d-45a1-9120-3adf617e3a2e)
I don't think it's usefull to fix it because there is *(normally)* no way of getting the planetGUI with a tier 0 rocket

### How to Reproduce?

- Execute `/planetgui @s 0`
- See an unexpected image

### Expected Behavior

You shouldn't see something, even though there is *(normally)* no way of having the planetGUI with a tier 0.

### Version

(1.20.1) 1.15.2

### Mod Loader Version

Fabric - 0.15.0

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [x] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 1.15.7
