### ISSUE TITLE
[Feature Request]: Add Entities whitelist for not requiring oxygen

### ISSUE THREAD

**Issue by YejiYeah** [terrarium-earth/Ad-Astra#414]
### Is your feature request related to a problem?

I think it would be great to allow us to have some vanilla or modded pets in the planets and allow them to live there, I added a mod for robots and it kinda make no sense seeing them dying in the planets.

### Solution(s)

Add a whitelist for vanilla or modded mobs in the config file

### Describe alternatives you've considered

add an item that allows you right click entities to allows them breath without oxygen or add gear, the problem will be the modded mobs

### Mod Version

1.15.5

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Additional context

If you need I can help you with tests, this is my discord: yejiyeah

**Comment by KLONOA9X6** [comment]
数据包：data/ad_astra/tags/entity_types/entities/lives_without_oxygen
往这个标签里面追加实体ID

**Comment by AlexNijjar** [comment]
^ see the tag

**Comment by Lucas-Carrarini** [comment]
Hi, did you manage to make it work? @YejiYeah
