### ISSUE TITLE
My stuff for some reason disapeer after i log back in[Bug]: 

### ISSUE THREAD

**Issue by Math37** [terrarium-earth/Ad-Astra#415]
### Bug Description

When i was plating a few days ago i lost my space suit that  i placed in a chest the space suit just vanished and it happened today again with the space suit and another item and it used items for the item that i needed to craft and now i dont know what to do

### Expected Behavior

plz help me get my items back

### Version

2.0.5

### Mod Loader Version

0.14.22

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I don't see how Ad Astra could have caused that. and v2.0.5 doesnt exist
