### ISSUE TITLE
[Feature Request]: Have Aernos & Strophar Mushrooms function like Nether Mushrooms

### ISSUE THREAD

**Issue by DeCoded-Void** [terrarium-earth/Ad-Astra#419]
### Is your feature request related to a problem?

Compat mods using certain stems for recipes are visually broken. The image features [Every Compat (Wood Good)](https://modrinth.com/mod/every-compat/versions) along with [quark](https://modrinth.com/mod/quark):
![image](https://github.com/terrarium-earth/Ad-Astra/assets/11778439/6451c4ba-b455-4589-8723-4e1a0a75021f)

Glacian blocks are currently working properly:
![image](https://github.com/terrarium-earth/Ad-Astra/assets/11778439/a04ccd42-d0a6-41e1-b6c7-09e0b78d7126)

My suspicion is how the Aernos Stems and Strophar Mushroom stems are essentially Hyphae blocks rather than traditional stem blocks:
![image](https://github.com/terrarium-earth/Ad-Astra/assets/11778439/87dda6c2-11bf-4734-b360-a2c6a8a816a5)

### Solution(s)

Have current Aernos and Strophar blocks follow the same convention as nether blocks.

![image](https://github.com/terrarium-earth/Ad-Astra/assets/11778439/7f7b54ae-dfbd-4ac5-ba06-74aa55233a16)

### Mod Version

1.12.7

### Mod Loader Version

1.19.2 - 43.3.5

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
These mushroom blocks were originally for a moon mushroom biome we were planning on adding. However that's since been scrapped so these blocks will be removed in the future and should be considered legacy blocks that wont receive any more support.
