### ISSUE TITLE
[Bug]: No Fuel Error Message

### ISSUE THREAD

**Issue by Madslabs420** [terrarium-earth/Ad-Astra#420]
### Bug Description

After filling my rocket for the first time I got in to launch, pressed space and got the error "NO FUEL! Fill the rocket with fuel." I shift-clicked the rocket and it shows that it has full fuel. I went ahead used my reserve fuel to try and fill it again. I got in to launch the rocket and the same message pops up stating there's no fuel.  (works in single player)
![Screenshot (66)](https://github.com/terrarium-earth/Ad-Astra/assets/156415223/222972a9-1f33-4938-a818-afb820b20328)
[
![Screenshot (67)](https://github.com/terrarium-earth/Ad-Astra/assets/156415223/11f38fb0-6b24-43b8-82bf-ceb805bed1c1)
](url)

### Version

1.20.1

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Try 1.15.8.

**Comment by Madslabs420** [comment]
I installed the 1.15.8 onto the server and its telling me that it has a mismatched mod list error. The server apparently still has all the items from the 1.15.5 version loaded and there are conflictions. Even after removing the older version. Is there a way to update a server to include these items, or remove them altogether? 
![Capture](https://github.com/terrarium-earth/Ad-Astra/assets/156415223/49a962ee-eac3-415e-b3d0-355686f13e69)

**Comment by AlexNijjar** [comment]
Is there an actual error? and the server is crashing? in the logs you provided, they are just warnings that happens pretty much any time you update to a new version on forge. It shouldn't break anything

**Comment by Madslabs420** [comment]
I just loaded back into 1.15.5  and the rockets seem to be working properly!! Not sure what happened but it's fixed!
