### ISSUE TITLE
[Bug]: Dev Env Unfixable Conflict

### ISSUE THREAD

**Issue by xanthian** [terrarium-earth/Ad-Astra#422]
### Bug Description

When adding Ad-Astra as a dependency via gradle you get the following error :

Mapping target name conflicts detected:
  METHODs earth/terrarium/adastra/client/screens/PlanetsScreen/[net/minecraft/class_437/method_25419, close]()V -> close
There were unfixable conflicts.

```
    // Ad Astra
    modRuntimeOnly("maven.modrinth:ad-astra:UKU6f8pz") // 1.15.8
    modRuntimeOnly("maven.modrinth:botarium:a6dUCytc") //botarium 2.3.1
    modApi("maven.modrinth:resourceful-config:PlEObkl9") //resourcefulconfig 2.1.2
    modApi("maven.modrinth:resourceful-lib:HGTwQLNx") //resourcefullib 2.1.20
```

### How to Reproduce?

Add Ad Astra + deps to gradle in IntelliJ
For ref im using Yarn mappings

### Expected Behavior

Didn't occur on 1.15.5

### Version

1.15.8

### Mod Loader Version

0.14.25

### Mod Loader

Fabric

### Logs or additional context

Fixable using tiny remapper

```
c	earth/terrarium/adastra/client/screens/PlanetsScreen	earth/terrarium/adastra/client/screens/PlanetsScreen
	m	()V	close	close$fixConflict
```
### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Use tiny remapper to fix it. I am not going to look through all of my stuff just to make sure the names don't conflict with yarn. Yarn is also dwindling in maintainers so I don't think it's going to be around for much longer. Please consider using mojmap.
