### ISSUE TITLE
[Bug]: Wrong slot using in ItemUtils.additem

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#423]
### Bug Description

https://github.com/terrarium-earth/Ad-Astra/blob/d65a69fe827294a0c0b43e396bf453226ec726eb/common/src/main/java/earth/terrarium/adastra/common/utils/ItemUtils.java#L48-L58

In line 52, passed element of toSlots during call from side's canTakeItemThroughFace(slot, fromStack, direction))
https://github.com/terrarium-earth/Ad-Astra/blob/d65a69fe827294a0c0b43e396bf453226ec726eb/common/src/main/java/earth/terrarium/adastra/common/utils/ItemUtils.java#L52

If from's canTakeItemThroughFace returned false, skipped to next slot.
So in to's inventory, items may be pushed in a slot that has been skipped a few offset.

My code
![image](https://github.com/terrarium-earth/Ad-Astra/assets/44163945/dc60e150-4155-4882-86b5-e54c3913bbca)
![image](https://github.com/terrarium-earth/Ad-Astra/assets/44163945/14142b0b-eb3e-4378-af1a-dad74f2987ca)

Ingame screenshot
![image](https://github.com/terrarium-earth/Ad-Astra/assets/44163945/96466599-27f9-4dd5-a991-40da1aaf43ab)
![image](https://github.com/terrarium-earth/Ad-Astra/assets/44163945/d170aee5-d6cc-4bee-b4ba-6fbf8bd2f9d2)
![image](https://github.com/terrarium-earth/Ad-Astra/assets/44163945/04f2038b-c729-4b57-a384-c442918304f4)

### Version

1.15.8

### Mod Loader Version

1.20.1 - 0.88.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
removing the `canTakeItemThroughFace` and `canPlaceItemThroughFace` checks from the method seems to be the best solution. because it also seems to not work with some blocks like furnaces.
