### ISSUE TITLE
[Bug]: You cannot launch from this dimension

### ISSUE THREAD

**Issue by wigarddev** [terrarium-earth/Ad-Astra#424]
### Bug Description

It is impossible to fly to any planet from earth (minecraft:overworld).

### How to Reproduce?

1. Get into a rocket on the ground (overworld)
2. Displayed "You cannot launch from this dimension!"
3. When the rocket takes off, the planets menu is empty

### Expected Behavior

The error message is not displayed and the planets menu is not empty.

### Version

1.15.8

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Logs or additional context

![image](https://github.com/terrarium-earth/Ad-Astra/assets/55100874/acc49cad-c5aa-493f-ad78-ec1782962908)

Botarium v2.3.1
Resourceful Lib v2.1.20
Resourceful Lib Config v2.1.2
Cloth Config v11.1.106

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I believe forge has an issue where the dimensions don't generate sometimes on first load. If you exit the world and rejoin, does it still happen?

**Comment by wigarddev** [comment]
> I believe forge has an issue where the dimensions don't generate sometimes on first load. If you exit the world and rejoin, does it still happen?

Restarting the server does not help, neither does rejoin. I tried to install mods first, and only after that start the server so that the first generation of the world would go with the mod, but also unsuccessfully.

**Comment by wigarddev** [comment]
The problem was noticed on versions 1.15.7-1.15.8

**Comment by AlexNijjar** [comment]
Alright, I was able to reproduce it on a forge server. I'll fix it and push a new update soon.

**Comment by AlexNijjar** [comment]
Try 1.15.9. I made some packet-related changes that should fix this issue. I believe what was happening was that the planet data was being sent to early to the client, hence why the planet menu was empty, because the client never received that data. I tested it on a Forge 1.20.1 server and it worked fine after the changes.

**Comment by wigarddev** [comment]
Yes, the problem disappeared in version 1.15.9. Thanks for the quick fix!
