### ISSUE TITLE
[Bug]: Extreme non-TPS lag when running machines are present

### ISSUE THREAD

**Issue by 9m113konkurs** [terrarium-earth/Ad-Astra#425]
### Bug Description

An area of Moon lags player down; that area had some player-built buildings and Ad Astra machines providing oxygen powered by solar cell arrays (~4 buildings with machines, I estimate no more than 50 machines in total including generators, but there are many cables and pipes).

By "lagging" this refers to non-TPS lag; player interactions (doors, chests etc.) are extremely delayed to unplayable levels. Sometimes the player is kicked due to time-out. Only players within that specific region are affected; players elsewhere on the Moon, overworld or other Ad Astra dimensions are unaffected.

Checking server console shows TPS still around 20.

This phenomenon does not appear in other Ad Astra dimensions that do not have machines; on Mars (previously unexplored and thus no machines) the percieved lag did not occur until players started to spam machines, cables and solar panels.

### How to Reproduce?

**MODLIST:**
• mods_folder saturn-mc1.20.1-0.1.1.jar : saturn (0.1.1) - 1
• mods_folder radium-mc1.20.1-0.12.2+git.5f80f74.jar : radium (0.12.2+git.5f80f74) - 1
• mods_folder notenoughcrashes-4.4.6+1.20.1-forge.jar : notenoughcrashes (4.4.6+1.20.1) - 1
• mods_folder ftb-essentials-forge-2001.2.2.jar : ftbessentials (2001.2.2) - 1
• mods_folder Fastload-Reforged-mc1.20.1-3.4.0.jar : fastload (3.4.0) - 1
• mods_folder supermartijn642configlib-1.1.8-forge-mc1.20.jar : supermartijn642configlib (1.1.8) - 1
• mods_folder rechiseled-1.1.5c-forge-mc1.20.jar : rechiseled (1.1.5c) - 1
• mods_folder botarium-forge-1.20.1-2.2.5.jar : botarium (2.2.5) - 1
• mods_folder connectivity-1.20.1-4.9.jar : connectivity (1.20.1-4.9) - 1
• mods_folder valhelsia_furniture-forge-1.20.1-1.1.2.jar : valhelsia_furniture (1.1.2) - 1
• mods_folder immersive_aircraft-0.6.2+1.20.1-forge.jar : immersive_aircraft (0.6.2+1.20.1) - 1
• mods_folder journeymap-1.20.1-5.9.18-forge.jar : journeymap (5.9.18) - 1
• mods_folder EverlastingSkins-1.20.1-1.0 (1).jar : everlastingskins (1.0) - 1
• mods_folder modernfix-forge-5.11.1+mc1.20.1.jar : modernfix (5.11.1+mc1.20.1) - 1
• mods_folder jei-1.20.1-forge-15.2.0.27.jar : jei (15.2.0.27) - 1
• mods_folder fusion-1.1.0c-forge-mc1.20.1.jar : fusion (1.1.0c) - 1
• mods_folder memoryleakfix-forge-1.17+-1.1.5.jar : memoryleakfix (1.1.5) - 1
• mods_folder cloth-config-11.1.118-forge.jar : cloth_config (11.1.118) - 1
• mods_folder wafflesplaster-v1.0-FORGE-1.20.1.jar : wafflesplaster (1.0) - 1
• mods_folder supplementaries-1.20-2.7.22.jar : supplementaries (1.20-2.7.22) - 1
• mods_folder embeddium-0.2.16+mc1.20.1.jar : embeddium (0.2.16+mc1.20.1) - 2
• mods_folder logprot-1.20.1-3.3.jar : logprot (1.4) - 1
• mods_folder FarmersDelight-1.20.1-1.2.3.jar : farmersdelight (1.20.1-1.2.3) - 1
• mods_folder ends_delight-1.20.1-1.0.1.jar : ends_delight (1.0.1) - 1
• mods_folder betterminecarts-1.20.1-1.8.1-47.1.0.jar : betterminecarts (1.8.1) - 1
• mods_folder moonlight-1.20-2.8.81-forge.jar : moonlight (1.20-2.8.81) - 1
• mods_folder supermartijn642corelib-1.1.16-forge-mc1.20.1.jar : supermartijn642corelib (1.1.16) - 1
• mods_folder smoothboot(reloaded)-mc1.20.1-0.0.4.jar : smoothboot (0.0.4) - 1
• mods_folder nethersdelight-1.20.1-4.0.jar : nethersdelight (1.20.1-4.0) - 1
• mods_folder resourcefulconfig-forge-1.20.1-2.1.2.jar : resourcefulconfig (2.1.2) - 1
• mods_folder servercore-forge-1.3.9+1.20.1.jar : servercore (1.3.9+1.20.1) - 1
• mods_folder spark-1.10.59-forge.jar : spark (1.10.59) - 1
• mods_folder mes-1.3-1.20-forge.jar : mes (1.3-1.20-forge) - 1
• mods_folder entityculling-forge-1.6.2-mc1.20.1.jar : entityculling (1.6.2) - 1
• mods_folder betterchunkloading-1.20.1-2.5.jar : betterchunkloading (1.20.1-2.5) - 1
• mods_folder resourcefullib-forge-1.20.1-2.1.20.jar : resourcefullib (2.1.20) - 1
• mods_folder worldedit-mod-7.2.15.jar : worldedit (7.2.15+6463-5ca4dff) - 1
• mods_folder oceansdelight-1.0.2-1.20.jar : oceansdelight (1.0.2-1.20) - 1
• mods_folder architectury-9.1.12-forge.jar : architectury (9.1.12) - 1
• mods_folder ftb-library-forge-2001.1.4.jar : ftblibrary (2001.1.4) - 1
• mods_folder [1.20.1-forge]-Epic-Knights-8.11.jar : magistuarmory (8.11) - 1
• mods_folder ferritecore-6.0.1-forge.jar : ferritecore (6.0.1) - 1
• mods_folder AI-Improvements-1.20-0.5.2.jar : aiimprovements (0.5.2) - 1
• mods_folder cupboard-1.20.1-2.2.jar : cupboard (1.20.1-2.2) - 1
• mods_folder wafflesmoss-v1.0-FORGE-1.20.1.jar : wafflesmoss (1.0) - 1
• mods_folder smallships-forge-1.20.1-2.0.0-a2.3.3.jar : smallships (2.0.0-a2.3.3) - 1
• mods_folder KryptonReforged-0.2.3.jar : krypton (0.2.3) - 1
• mods_folder valhelsia_core-forge-1.20.1-1.1.1.jar : valhelsia_core (1.1.1) - 1
• mods_folder chunksending-1.20.1-2.8.jar : chunksending (1.20.1-2.8) - 1
• mods_folder deuf-1.20.1-1.3.jar : deuf (1.20.1-1.3) - 1
• mods_folder recruits-1.20.1-1.10.10.jar : recruits (1.10.10) - 1
• mods_folder ad_astra-forge-1.20.1-1.15.5.jar : ad_astra (1.15.5) - 1

**REPRODUCTION:** 
1. install large amounts of Ad Astra machines, including generators and cables;
2. connect them so that all machines are powered and all generators are utilized;
3. non-TPS lag starts, checking TPS should reveal server TPS still at around 20.

I am not sure if this can be reproduced on an internal server. The problem occurred on a dedicated server (Forge server version 47.2.19, not hybrid) hosted remotely.

### Expected Behavior

No obvious lag at such machine counts;
Lag, if any, should be consistent with TPS drop.

### Version

1.15.5

### Mod Loader Version

47.2.19

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [x] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by 9m113konkurs** [comment]
Internet connection (shown in tab player menu) is often shown to be slow.
![image](https://github.com/terrarium-earth/Ad-Astra/assets/128269880/a2167ec8-14fa-4cd5-9c72-5403b72c80dc)
This also restores to normal after leaving the area.

**Comment by AlexNijjar** [comment]
try on 1.15.8, we redid everything in that version. versions older than that are no longer supported

**Comment by 9m113konkurs** [comment]
> try on 1.15.8, we redid everything in that version. versions older than that are no longer supported

OK, will do soon.

**Comment by 9m113konkurs** [comment]
> try on 1.15.8, we redid everything in that version. versions older than that are no longer supported

OK, will do soon.
Be noted that #424 also exists on my setup, so I have to use /tpx instead of normal rockets.
EDIT: ignore the complete tag, sorry :(

**Comment by 9m113konkurs** [comment]
It seems that pre-1.15.8 Ad Astra's machines are incompatible with post-1.15.8's machines? Is this unavoidable?
Launchpads and doors seem to have their block data messed up.

Anyways I will be testing with a brand world generated in 1.15.8.

**Comment by AlexNijjar** [comment]
The doors and launchpads would be messed up. you'll need to break and place them again. The machines shouldn't be incompatible; however they'll lose any data like items, energy fluids in them.

**Comment by 9m113konkurs** [comment]
> The doors and launchpads would be messed up. you'll need to break and place them again. The machines shouldn't be incompatible; however they'll lose any data like items, energy fluids in them.

Understood. Consider adding this to the CF release page? Though this technically does not break setups this can mean significant rebuilds for players upgrading the mod, since block data is messed up (also observed this in cables).

**Comment by 9m113konkurs** [comment]
Under 1.15.8 problem is solved.
