### ISSUE TITLE
[Bug]:  Crash On Startup

### ISSUE THREAD

**Issue by lanwoodall423** [terrarium-earth/Ad-Astra#431]
### Bug Description

Crash on startup

### How to Reproduce?

Neoforge on 1.20.1
Ad Astra 1.15.9
Other mods. 
Launch

### Expected Behavior

Load

### Version

1.15.9

### Mod Loader Version

1.20.1

### Mod Loader

NeoForge

### Logs or additional context

[crash-2024-01-16_14.53.05-client.txt](https://github.com/terrarium-earth/Ad-Astra/files/13955282/crash-2024-01-16_14.53.05-client.txt)
[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/13955279/latest.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ModernGamingWorld** [comment]
@lanwoodall423 Currently, this mod only supports Forge and Fabric. NeoForge is not listed as a currently supported mod loader version, and this is most likely the reason this mod is crashing. Idk if @AlexNijjar has plans to support NeoForge or not, I know for 1.20.4 NeoForge they are still making breaking changes and 1.20.1 is still being worked on from what I see on from their Discord.

**Comment by lanwoodall423** [comment]
Ah ok thank you

**Comment by AlexNijjar** [comment]
> @lanwoodall423 Currently, this mod only supports Forge and Fabric. NeoForge is not listed as a currently supported mod loader version, and this is most likely the reason this mod is crashing. Idk if @AlexNijjar has plans to support NeoForge or not, I know for 1.20.4 NeoForge they are still making breaking changes and 1.20.1 is still being worked on from what I see on from their Discord.

We're switching to neoforge in 1.20.4 and dropping forge support.
