### ISSUE TITLE
[Bug]: Unable to pull fuel from Fuel Refinery using pipes.

### ISSUE THREAD

**Issue by RavenholmZombie** [terrarium-earth/Ad-Astra#436]
### Bug Description

I am unable to pull fuel from the Fuel Refinery using any kind of pipes or pumps. I've tried Immersive Engineering pipes with a pump, Pretty Pipes, Thermal Series Fluiducts with servo, and even Refined Storage importers.

### How to Reproduce?

1. Place a Fuel Refinery.
2. Give it power.
3. Give it oil and let it make fuel.
4. Attach pipes to the block to pull fuel.
5. Nothing happens, it should pull fuel but doesn't.

### Expected Behavior

The Fuel Refinery should be able to have fuel pulled from it using pipes.

### Version

1.15.5

### Mod Loader Version

47.2.6

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Update to 1.15.10
