### ISSUE TITLE
Mod has disappeared from Curse Forge website.

### ISSUE THREAD

**Issue by Zarepheth** [terrarium-earth/Ad-Astra#44]
The Curse Forge website is returning a 404 error when I attempt to load the mod's page there.
Doing a Google search for the mod's other pages, Modrinth also returned a 404.

**Comment by AlexNijjar** [comment]
It was temporarily removed because of this https://github.com/terrarium-earth/Ad-Astra/issues/43

The Modrinth page is still up, the link was just changed from https://modrinth.com/mod/ad-astra-fabric to https://modrinth.com/mod/ad-astra
