### ISSUE TITLE
[Bug]: custom dimension not appearing in the list

### ISSUE THREAD

**Issue by Xplodin** [terrarium-earth/Ad-Astra#444]
### Bug Description

I cant get my planet to show in planet selection for a t4 rocket

### How to Reproduce?

install datapack via openloader data and resources
install ad astra and make new world.
verify the dimension exists with /tpx (it does and is there for sure)
launch t4 rocket from earth and see no galaxy there for custom planet

### Expected Behavior

see galaxy/solar system there and be able to land on it

### Version

1.15.10

### Mod Loader Version

1.20.1-47.2.19

### Mod Loader

Forge

### Logs or additional context

nothing appears in the logs relevant to the datapack or ad astra
but here is my datapack and resourcepack
[planet_bean_datapack.zip](https://github.com/terrarium-earth/Ad-Astra/files/14047047/planet_bean_datapack.zip)
[planet_bean_resources.zip](https://github.com/terrarium-earth/Ad-Astra/files/14047051/planet_bean_resources.zip)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
The format changed. See:
https://github.com/terrarium-earth/Ad-Astra/tree/1.20.1/common/src/main/generated/resources/data/ad_astra/planets
https://github.com/terrarium-earth/Ad-Astra/tree/1.20.1/common/src/main/generated/resources/assets/ad_astra/planet_renderers

Note that the resourcepack stuff is not currently available in 1.15.10, it'll be available soon. Also, the wiki is outdated but I'm currently working on an updated one.
