### ISSUE TITLE
[Crash Report]: Crash with Inventory Tabs

### ISSUE THREAD

**Issue by lostopkk** [terrarium-earth/Ad-Astra#445]
### Bug Description

Inventory Tabs + Ad astra, when exit to the universe the game crash

### How to Reproduce?

1. Download Inventory Tabs + Ad astra
2. Go to the moon
3. Crash

### Expected Behavior

Mod runs normally

### Version

1.15.10

### Mod Loader Version

1.20.1 Fabric api 0.90.0 Fabric loader 0.15.6

### Mod Loader

Fabric

### Logs or additional context

https://mclo.gs/k6QvCQ5

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
I've never used inventory tabs and not sure how it works, but from a quick glance, it looks like it's their issue. Inventory Tabs assume that `tabPositions` isn't empty but it is for the planet screen for whatever reason so it's divided by zero. https://github.com/sisby-folk/inventory-tabs/blob/4f923622fc4edb17f0e20ce45ad354614896aeb4/src/main/java/folk/sisby/inventory_tabs/TabManager.java#L74

**Comment by sleepingdragoninn** [comment]
Yep we'll cover this off no problem.

Sidenote that it looks like your log is displaying broken repair materials (emi anvil recipe index errors) - we recently published [Tinkerer's Smithing 2.6.5](https://modrinth.com/mod/tinkerers-smithing/version/2.6.5+1.20) that happens to rat out instances of mods accessing ingredients too early in the log, which often causes that issue - you're welcome to try it as a form of debugger for that.

**Comment by sleepingdragoninn** [comment]
released as 1.1.6
