### ISSUE TITLE
[Bug]: Steel crafting Recipe missing along with otheres

### ISSUE THREAD

**Issue by PhoxVRC** [terrarium-earth/Ad-Astra#446]
### Bug Description

Quite a few crafting recipe's are missing such as Steel.

### How to Reproduce?

1. Download latest alpha version 1.15.11
2. Start game
3. Check crafting recipe's with EMI
4. Attempt to blast it anyway, Doesnt work.
![image](https://github.com/terrarium-earth/Ad-Astra/assets/42518848/355376dc-d585-4645-a4bd-8a74b49c48e7)

### Expected Behavior

Steel can be created from iron in a blast furnace /  Create blasting.

### Version

1.15.11

### Mod Loader Version

1.20.1 | 0.15.6

### Mod Loader

Fabric

### Logs or additional context

[Mod list](https://pastebin.com/wgXcz9rL)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
the recipe was removed. You now craft steel in an etrionic blast furnace.
