### ISSUE TITLE
Forge Issues

### ISSUE THREAD

**Issue by HttpRafa** [terrarium-earth/Ad-Astra#45]
I started playing with Ad Astra on Forge and found some bugs.

- Placing a rocket in Survival places it but does not remove it from inventory. (Infinite rockets)
- Fuel duplication bug: https://user-images.githubusercontent.com/60099368/202519417-b2c8703f-7e5f-49f3-a5e0-44de94f05cd5.mp4

**Comment by AlexNijjar** [comment]
Thanks. The fluid duping has been fixed in a patch and will be released later today. As for the rockets, I will check it out.

**Comment by AlexNijjar** [comment]
Alright. the rocket duplication glitch is now fixed https://github.com/terrarium-earth/Ad-Astra/commit/a3c3d6b0c224b4afa1b99968a54a03f63e99bf7d

**Comment by HttpRafa** [comment]
I also found a bug with Oxygen and Energy syncing on servers.


https://user-images.githubusercontent.com/60099368/202546814-bcc66440-75d5-4727-bdc6-495a9c87c8e8.mp4

**Comment by AlexNijjar** [comment]
Painfully aware of that one too 😅. Pretty sure it's a [Botarium](https://github.com/terrarium-earth/Botarium) bug. Gonna fix that one and release later today.

**Comment by HttpRafa** [comment]
And another bug when breaking launchpads in survival.


https://user-images.githubusercontent.com/60099368/202547790-e926b62d-7f6c-4e4f-b3b6-8d339ddd246e.mp4

**Comment by AlexNijjar** [comment]
lmao will fix this one too

**Comment by HttpRafa** [comment]
👍

**Comment by AlexNijjar** [comment]
All of these should be now fixed in the latest version
https://www.curseforge.com/minecraft/mc-mods/ad-astra/files/4098415
