### ISSUE TITLE
Gravity stop working when set to low [Bug]: 

### ISSUE THREAD

**Issue by DeadbushCarrot** [terrarium-earth/Ad-Astra#450]
### Bug Description

When trying to set gravity lower then 0.9 or somewhere near that it treats it like its set to 0

### How to Reproduce?

1 Go in game or edit a planet file 
2 place down a gravity normalizer or change the gravity of a planet 
3 Set the gravity to 0.9 or lower 

### Expected Behavior

Expected gravity to go lower and not none

### Version

1.20.1 1.15.16 Fabric

### Mod Loader Version

1.20.1 Fabric 0.15.6

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
This is intended as values below 0.9 start breaking minecraft's movement system

**Comment by DeadbushCarrot** [comment]
So this can't be fix unless Minecraft fixes it?

**Comment by AlexNijjar** [comment]
If I remember correctly what happens is you don't fall down anymore and you can't jump when the gravity is super low. So probably not something I can fix. Why do you need the gravity to be at such a low value?

**Comment by DeadbushCarrot** [comment]
Cause am making a Add-on for Ad Astra call Planets+ and some moons and dwarf planets have really low gravity Like plutos is 0.62 which was already really close to the old limit I found I think it was 0.56. also Planets+ is on Modrinth if you need to know.

**Comment by AlexNijjar** [comment]
I guess I could reduce the limit
