### ISSUE TITLE
[Feature Request]: Consider changing the Energizer's color change ranges

### ISSUE THREAD

**Issue by MuteTiefling** [terrarium-earth/Ad-Astra#451]
### Is your feature request related to a problem?

Visual annoyance. 

The Energizer basically flickers constantly if it's being used to power machines

### Solution(s)

The energizer appears to have 4 colors for different percentages. Red, orange, green, and then blue. Blue appears to mean exactly 100% so as machines are using power from it, it will constantly flicker between blue and green as it charges/discharges. I'd propose changing that threshold for blue to be a little lower, like 95%.

### Mod Version

1.19.2-1.12.7

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Additional context

https://streamable.com/ua8c3n

In the video, power is coming in below the energizer. There's one cable pulling energy from the right down into the oxygen distributor to ensure it keeps running if something is charging on the energizer. 

As a result, the energizer is just flickering constantly.

**Comment by AlexNijjar** [comment]
It's fixed in 1.20.1, it just likely will not be backported to 1.19.2 as I am no longer focusing on that version.

**Comment by MuteTiefling** [comment]
Fair enough! Thanks!
