### ISSUE TITLE
[Bug]: Cant craft steel ingot

### ISSUE THREAD

**Issue by rektchamp12** [terrarium-earth/Ad-Astra#452]
### Bug Description

How am i supposed to craft steel ingot?. Like you cant find as a ore or loot from chests. You have to craft it but you need steel ingots to craft necessary blocks??. Please help

### Version

1.19.2

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by rektchamp12** [comment]
ballz

**Comment by AlexNijjar** [comment]
I'm assuming this is a joke but for anyone else steel is crafted in an etrionic blast furnace

**Comment by AlexNijjar** [comment]
and for 1.19.2 it's crafted by smelting iron in a blast furnace
