### ISSUE TITLE
[Bug]: jukebox and other music player thing cant work properly in space

### ISSUE THREAD

**Issue by CharamitasSaMa** [terrarium-earth/Ad-Astra#456]
### Bug Description

i tried to play music in my space station but i heard a slowed,modulated music.  im very sure that my space station has enough oxygen but this is still happening.

### Expected Behavior

i just want music be normal in these dimension

### Version

1.15.4

### Mod Loader Version

1.20.1-47.2.20

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
it’s already fixed in the latest version

**Comment by CharamitasSaMa** [comment]
> it’s already fixed in the latest version

ok sorry for disturb
