### ISSUE TITLE
[Feature Request]: Add resource pack and datapack driven custom planet back

### ISSUE THREAD

**Issue by CharamitasSaMa** [terrarium-earth/Ad-Astra#457]
### Is your feature request related to a problem?

I'm making an modpack that needs to add new planet but when I tried tu update mod version for fix the audio bug, the custom planet datapack can't run properly anymore.

### Solution(s)

 Add resource pack and datapack driven custom planet back please, like resourcepack controllable rocket solar systems select gui texture in older version.

### Mod Version

1.15.16

### Mod Loader Version

1.20.1-47.2.20

**Comment by AlexNijjar** [comment]
It's changed in the latest version https://ad-astra.terrarium.wiki/custom-planets.html
