### ISSUE TITLE
[Bug]: Steel Ingot cannot be smelted when Tech Reborn mod loaded

### ISSUE THREAD

**Issue by Dark2932** [terrarium-earth/Ad-Astra#459]
### Bug Description

Steel Ingot cannot be smelted in Etrionic Blast Furnace, it will produce Refined Iron Ingot (TR).

### How to Reproduce?

1. Load Ad Astra and Tech Reborn
2. Smelt Steel Ingot in Etrionic Blast Furnace

### Expected Behavior

The Steel Ingot can be produced normally.

### Version

1.16.3

### Mod Loader Version

1.20.4-0.15.6

### Mod Loader

Fabric

### Logs or additional context

Nothing

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by Dark2932** [comment]
https://github.com/terrarium-earth/Ad-Astra/assets/72404859/6f8df1dd-6a30-469a-ab1f-dd87d9b185d6

Please download it to watch, I don't know why it can't play

**Comment by AlexNijjar** [comment]
you have it on blasting mode not alloying mode

**Comment by AlexNijjar** [comment]
<img width="83" alt="Screenshot 2024-02-07 at 12 08 58 AM" src="https://github.com/terrarium-earth/Ad-Astra/assets/61668546/1a92bc3c-9eb7-4e83-bc5d-b0c9d4087bca">
click this to switch the mode. because currently it's being treated as a blast furnace
