### ISSUE TITLE
[Bug]: custom planets & solar system not visible in star-map

### ISSUE THREAD

**Issue by LinuxSquare** [terrarium-earth/Ad-Astra#461]
### Bug Description

When adding a custom planet & solar-system via datapack and type `/adastra planets` to open up the star-map, when clicking on the newly added solar-system, the map with the star and the planets is not visible as it is on the default planets & solar-systems.

### How to Reproduce?

1. Download cheese[-datapack](https://github.com/terrarium-earth/Ad-Astra-Docs/blob/main/Writerside/examples/cheese-datapack.zip) & [-resourcepack](https://github.com/terrarium-earth/Ad-Astra-Docs/blob/main/Writerside/examples/cheese-resourcepack.zip) (for a reference)
2. Put the resourcepack into the resourcepack folder of the minecraft-instance.
3. create a new world and add the cheese-datapack to it.
4. When the world has been loaded, type `/adastra planets`.
5. navigate to the cheese solar system.

### Expected Behavior

The solar-system should be visible with all of it's planets orbiting it.

### Version

1.15.16

### Mod Loader Version

NeoForge: 47.1.98, Fabric: 0.15.6

### Mod Loader

NeoForge, Fabric

### Logs or additional context

Created a dummy modpack for MC version 1.20.1 with only Ad Astra and it's dependencies installed.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Doesn't this make sense? Why would the default system show for a custom solar system? And there's currently no way to show your own solar system and I don't want to add that as we're eventually going to completely redo that screen.

**Comment by LinuxSquare** [comment]
> Doesn't this make sense? Why would the default system show for a custom solar system?

I think you misunderstood me a little:

> the map with the star and the planets is not visible as it is on the default planets & solar-systems.

this part is only a comparison to point out that the newly generated solar-system doesn't show up, as the other system's do.
I didn't want to tell, that not the default solar system shows up in my newly generated solar-system. Of course, this wouldn't make any sense.
I'm sorry if I have confused you.

> I don't want to add that as we're eventually going to completely redo that screen.

Totally understandable, I've already taken note that you're rewriting the mod.
I just wanted to know if it was intended behavior or not.

Cheers :beers:
