### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by PapkaBomja** [terrarium-earth/Ad-Astra#462]
### Bug Description

When I reach altitude 600 on a rocket, the solar system menu does not appear.

### How to Reproduce?

1. Sit in a rocket
2. Press Spacebar
3. Wait

### Expected Behavior

The planet selection menu should appear.

### Version

1.15.13

### Mod Loader Version

1.20.1 — 47.2-47.2.20

### Mod Loader

Forge

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by LinuxSquare** [comment]
@PapkaBomja I can confirm and reproduce the issue with Forge 47.2.20 and Ad Astra 1.15.13
However, version 1.15.16 is available. After updating to this version, I didn't have the issue anymore.

**Comment by AlexNijjar** [comment]
^ update
