### ISSUE TITLE
[Feature Request]: Sliding Doors Can Be Toggled While Animating

### ISSUE THREAD

**Issue by DereC4** [terrarium-earth/Ad-Astra#463]
### Is your feature request related to a problem?

Sliding doors are awesome i love how they fit 3x3 spaces. Is it possible to make it so that they can be toggled mid-animation? That way if you accidentally right click to close/open you can quickly do so again to open the door.

### Solution(s)

Right clicking while the door is opening/closing can toggle the door.

### Mod Version

1.12.7

### Mod Loader Version

Forge 1.19.2 43.2.21

**Comment by MFNmodding** [comment]
is that not already a thing? I can do that, or at least in 1.20 I can.

**Comment by AlexNijjar** [comment]
yeah it is

**Comment by DereC4** [comment]
> is that not already a thing? I can do that, or at least in 1.20 I can.

I'm not sure; I made this back when the spring semester was still going on so they may have upadted it since then
