### ISSUE TITLE
[Bug]: Guidebook not open

### ISSUE THREAD

**Issue by Ttwek** [terrarium-earth/Ad-Astra#465]
### Bug Description

If you right-click the guidebook, it tells you to install the police box, but the guidebook does not open even if you install it

### Version

1.20.1

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
what mod version?

**Comment by Ttwek** [comment]
1.15.1

**Comment by AlexNijjar** [comment]
and have you tested it on the latest version, 1.15.16? because you’re 15 versions behind and you’ve indicated that you’ve tested on the latest version.

**Comment by Ttwek** [comment]
I also tried the latest version, but it didn't run because of a crash in that version.

**Comment by AlexNijjar** [comment]
send the crash report
