### ISSUE TITLE
[Feature Request]: GIFs on flags

### ISSUE THREAD

**Issue by Adameczu** [terrarium-earth/Ad-Astra#468]
### Is your feature request related to a problem?

I want to add a dancing Ricardo on my flag, but it supports only PNGs. So, could someone add a support for gifs?

### Mod Version

1.15.11

### Mod Loader Version

1.20.1 - 0.15.6

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
Due to the way minecraft handles textures and that both tenor and imgur turn gifs to mp4s, the flag dev has stated they dont want to do it
