### ISSUE TITLE
[Bug]: Iron Sliding Door not aligned with hitbox

### ISSUE THREAD

**Issue by RobynIsi** [terrarium-earth/Ad-Astra#469]
### Bug Description

(I am playing ATM9) The model of the Iron Sliding Door (other types not tested) is mismatched with its hitbox. The Model is off by 1 pixel compared to it's hitbox
![2024-02-09_21 31 49](https://github.com/terrarium-earth/Ad-Astra/assets/145802553/3bb85707-56af-4dfe-a6ac-36382387faf4)

### How to Reproduce?

1. Place down an Iron Sliding Door
2. Observe that the hitbox is misaligned with the model

### Expected Behavior

The hitbox and the model should _both_ be centered in the block.

### Version

1.15.5

### Mod Loader Version

1.20.1 | Forge - 47.2.19

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
It's been fixed in 1.15.7 and above, ATM just has not updated to any version above that yet, assumably because it's in beta currently.
