### ISSUE TITLE
[Forge] Large Doors not behaving as expected

### ISSUE THREAD

**Issue by JensenJ** [terrarium-earth/Ad-Astra#47]
Hi,
When playing the mod (most recent version available (1.19.2) on Curseforge for most recent version of Forge) I noticed that when the larger doors added by this mod (Reinforced door, airlock, steel sliding door, iron sliding door, calorite sliding door, desh sliding door, ostrum sliding door) are placed along the North-South axis the collisions are strange. Doors placed along the East-West axis work as expected. This strange behaviour tends to be the collisions are offset and only work on 1 face of the door, so you can walk straight through the closed door from 1 side and get stopped on the other side but in the wrong place. 

Another bug I have noticed is the iron sliding door doesn't seem to have any texture or doesn't render correctly regardless of how it is placed. Checking the latest.log reveals this whenever it is interacted with or placed: 
[16:46:33] [Render thread/WARN]: Block entity ad_astra:sliding_door @ BlockPos{x=12, y=70, z=3} state Block{ad_astra:iron_sliding_door}[facing=east,location=bottom,open=false,powered=false] invalid for ticking

This behaviour is untested on Fabric.

The mod looks very promising though as a space mod for modern versions of Minecraft. Thanks.

**Comment by JensenJ** [comment]
After a little bit more testing it seems to matter depending on which way you are facing when you place the door. The strangest behaviour is experienced when facing west and placing. The hitbox for actually interacting with the door is still offset when placing either east or west however but only on the sliding doors, not on the airlock. Another thing I've noticed which is a bit strange but there may be some technical reason for it is there are loads of smaller hitboxes which are again offset near or inside the door, depending on the direction placed. I'm not sure for the reason for these to exist, would one large hitbox for interaction suffice? Thanks again for this mod, I hope this helps with improving the mod.

**Comment by AlexNijjar** [comment]
Check the latest version. if it's still happening lmk
https://www.curseforge.com/minecraft/mc-mods/ad-astra/files/4098415

**Comment by JensenJ** [comment]
Hi there, thanks for the quick reply and fix. I've just tested this, collision boxes and hitboxes are all fixed and working as expected, the other bug I mentioned about in the original post: the iron sliding door being invisible or not rendering correctly still seems to exist though. Attached is a screenshot which shows this: 
![2022-11-19_23 47 04](https://user-images.githubusercontent.com/13812018/202876009-0aa151fe-98c6-48d3-b70d-5a5b9e35339e.png)

**Comment by AlexNijjar** [comment]
Oh! Forgot about that. Just fixed it now and will release in an update tomorrow. thanks

**Comment by JensenJ** [comment]
No worries, thanks for fixing these bugs so quickly.

**Comment by grantjbutler** [comment]
Hi there! I'm able to replicate the collision box issue with doors on the 1.18.2-1.0.9 version of Ad Astra for Fabric. Would you like a fresh issue for this, or is it fine to reuse this issue for the broken behavior?
