### ISSUE TITLE
[Feature Request]: Coal generator not connecting to other machines

### ISSUE THREAD

**Issue by minerarmi** [terrarium-earth/Ad-Astra#471]
### Is your feature request related to a problem?

When I connect a machine to the coal generator, the enegry in the other machine, for example a compressor, is not going up. It's not working with anything. I tried out loads of ways to connect them, but nothing is happening. I watched tutorials and I don't think that I am doing something wrong. I would be thankul if somebody can help me!

### Mod Version

1.15.5

### Mod Loader Version

1.20.1 - 47.2.18

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
why is this an enhancement?

**Comment by minerarmi** [comment]
> why is this an enhancement?

Oh, sorry, I wasn't watching that.

**Comment by AlexNijjar** [comment]
The bug report option requires you to specify that you don't have optifine, which I'm assuming you have. Optifine breaks energy

**Comment by minerarmi** [comment]
> A hibajelentés opció megköveteli, hogy adja meg, hogy nincs optifine-je, amiről feltételezem, hogy van. Az Optifine megszakítja az energiát

So I should delete Optifine?

**Comment by AlexNijjar** [comment]
Yes

**Comment by minerarmi** [comment]
> Igen

Okay, thanks for the help!
