### ISSUE TITLE
[Bug]: Crash while in space station

### ISSUE THREAD

**Issue by NolanHewitt** [terrarium-earth/Ad-Astra#473]
### Bug Description

![huge_2024-02-12_10 42 38](https://github.com/terrarium-earth/Ad-Astra/assets/52480898/9d6996ca-4f3e-410f-b7e9-f6fa335730b2)

Game continuously crashes

### How to Reproduce?

go to the space station, move around or place blocks

### Expected Behavior

not crashing

### Version

1.15.17

### Mod Loader Version

1.20.1-0.23.1

### Mod Loader

Quilt

### Logs or additional context

[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/14241380/latest.log)

Happens when placing stuff or when moving around

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
try disabling the space muffler client config option as a temporary fix.

**Comment by NolanHewitt** [comment]
> try disabling the space muffler client config option as a temporary fix.

Looks like that does fix it for now, thank you, I never would've guessed to change that setting on my own.
