### ISSUE TITLE
[Bug]: Fuel duplication using Create item drains

### ISSUE THREAD

**Issue by BowBoy1** [terrarium-earth/Ad-Astra#477]
### Bug Description

Create item drains can be used to duplicate fuel. The drain pulls a bucket of fluid from the rockets but the rocket still somehow retains that fuel.

### How to Reproduce?

1. Install Ad Astra with Create
2. Place several item drains in a row
3. Drop a rocket with fuel in it onto the item drains. It will roll across all the item drains, putting fuel into all of them without ever running out of fuel.

### Expected Behavior

The fuel should drain from the rocket item.

### Version

1.15.10

### Mod Loader Version

1.20.1-0.15.6

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in next botarium update
