### ISSUE TITLE
[Bug]: The Ti-69s red and green lights are swapped from the item texture

### ISSUE THREAD

**Issue by Acat1234** [terrarium-earth/Ad-Astra#479]
### Bug Description

Its hard to say in words so this is the image of it ![2024-02-14_14 03 25](https://github.com/terrarium-earth/Ad-Astra/assets/126712560/724ddcc4-6b88-4fd0-8aa7-f11db65753c5)
See that the item in the hotbar has the lights swapped compared to the one on the hand?

### Version

1.15.17

### Mod Loader Version

Minecraft 1.20.1 forge 47.2.20

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in c3a8af9

**Comment by Acat1234** [comment]
I dont know how to use that

**Comment by CodexAdrian** [comment]
just means its fixed in dev, the next version after that commit would have the fix. Latest version of Ad Astra should have this fixed now
