### ISSUE TITLE
coal generator does not support standard input/output item methods.

### ISSUE THREAD

**Issue by QTpyeRose** [terrarium-earth/Ad-Astra#48]
this may need to be verified as im running a mod pack, but using forge version 1.19.2 hoppers (vanilla), transporters (mekanisum), and chutes (create) wont input coal into the coal generator.

i have not been able to find anything that supports into into coal generators

**Comment by AlexNijjar** [comment]
<img width="837" alt="Screenshot 2022-11-20 at 12 57 19 PM" src="https://user-images.githubusercontent.com/61668546/202920580-7f395319-b9c9-460f-9e03-8d43e5b54b40.png">

Can't reproduce. Is there any other info you can provide?

**Comment by QTpyeRose** [comment]
i will look more into this and do testing on my side

**Comment by QTpyeRose** [comment]
after lots of testing
this is caused by an conflict with the mod canary mc https://github.com/AbdElAziz333/Canary that aims to optimize, while its installed, input and output on ad astra blocks breaks. i will make a issue request on canary.

**Comment by QTpyeRose** [comment]
for record keeping, and your own knowledge, here is the report i put out for canary, regarding the compatability issues with this mod. https://github.com/AbdElAziz333/Canary/issues/61
