### ISSUE TITLE
[Bug]: pipes randomly reset

### ISSUE THREAD

**Issue by goodfaithgaming** [terrarium-earth/Ad-Astra#481]
### Bug Description

pipes switch back to their default state often after pipe network updates.

### How to Reproduce?

connect several machines
change the pipe configurations of several pipes
wait a few seconds
notice that some of the pipes have returned to what they were at before you messed with them

### Expected Behavior

pipes will retain their configuration

### Version

1.15.17

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Logs or additional context

There are no log messages when you do this.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
https://github.com/terrarium-earth/Ad-Astra/commit/b5fbc439f8e47cf9ba231aff7db84a9f1fc89a66
Pipes with insert or extract set will now retain that state when machines update. Not closing this yet as I'm not 100% sure if that'll fix this. Can you send a screenshot of your setup if it doesn't work in the next update?

**Comment by goodfaithgaming** [comment]
It works now. Thanks!
