### ISSUE TITLE
[Bug]: Non vanilla ladders block oxygen flow

### ISSUE THREAD

**Issue by Rawrland** [terrarium-earth/Ad-Astra#486]
### Bug Description

The standard space station contains vanilla ladders. However when using Ad Astra in a modpack with different alternatives (my example Create) it does not recognize these ladders as blocks which should transfer oxygen. This leads in a 1x1 shaft, that you would get damage due to missing oxygen.

### How to Reproduce?

1. Create a space station
2. Replace the ladder with a ladder alternative like Create's Brass Ladder (do not know how hard to make this general for more mods..)
3. Add oxygen distribution close enough
4. Climbe the 1x1 ladder
5. Get damage (destroy ladder and see that oxygen would be available)

### Expected Behavior

Ladders from other mods are able to transfer oxygen, to have more options for decoration

### Version

1.20.1-1.15.17

### Mod Loader Version

47.2.20

### Mod Loader

Forge

### Code of Conduct

- [x] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
The blocks can be added to ad_astra:passes_flood_fill tag
