### ISSUE TITLE
[Bug]: Can't Open Mod Settings

### ISSUE THREAD

**Issue by Tresillo2017** [terrarium-earth/Ad-Astra#489]
### Bug Description

Can't open mod Settings

### How to Reproduce?

1. Go to mod menu
2. Click on Ad Astra settings
3. Crash

### Expected Behavior

To be able to customize settings

### Version

1.16.5

### Mod Loader Version

1.20.4

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/raw/EJgxzL6M
There's no recepie for the hammer so I can't not start with the mod

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Update resourcefulconfig to 2.4.5

**Comment by Tresillo2017** [comment]
And why I can't craft the hammer?

**Comment by AlexNijjar** [comment]
the hammer doesnt exist anymore use the compressor

**Comment by Tresillo2017** [comment]
Thank you
