### ISSUE TITLE
Crashed in Forge 1.19.2 because of lander

### ISSUE THREAD

**Issue by AubthurYoung** [terrarium-earth/Ad-Astra#49]
The crash happened when I first arrival on Mars at height 599.79.

Crash reason:

A entity could not functional.
Ad_astra:lander (earth.terrarium.ad_astra.entities.vehicles.lander)
At 80.50 , 599.79 , 65.50

After that. every time I trying to goes into my saves it will crash again.

Addtional information:
Game: 1.19.2 Forge
Forge: 43.1.2
OptiFine: HD_U_H9
Java:17.0.3
System : Windows 11 X86-64
RAM: 6639 MB

The report are as follow:

[minecraft-exported-logs-2022-11-20T23-40-07.log](https://github.com/terrarium-earth/Ad-Astra/files/10049745/minecraft-exported-logs-2022-11-20T23-40-07.log)

[minecraft-exported-crash-info-2022-11-20T23-41-23.zip](https://github.com/terrarium-earth/Ad-Astra/files/10049746/minecraft-exported-crash-info-2022-11-20T23-41-23.zip)

**Comment by AlexNijjar** [comment]
should be fixed in the next update.
