### ISSUE TITLE
[Bug]: JEIWrappedDisplay cannot be cast to class CryoFreezingDisplay

### ISSUE THREAD

**Issue by SuperFeda** [terrarium-earth/Ad-Astra#490]
### Bug Description

https://youtu.be/_EPmkA6drNs

### Version

1.15.18

### Mod Loader Version

1.20.1 - 47.2.17

### Mod Loader

Forge

### Logs or additional context

logs: https://github.com/SuperFeda/AACrash

<details>
<summary>mod list</summary>

ACOFI-SkylightModding-1.20.1-1.0.jar
AdvancementPlaques-1.20.1-forge-1.4.10.jar
ad_astra-forge-1.20.1-1.15.18.jar
aether-1.20.1-1.2.0-neoforge.jar
AI-Improvements-1.20-0.5.2.jar
alexscaves-1.0.9.jar
alexsmobs-1.22.7.jar
Amplified_Nether_1.20.4_v1.2.4.jar
another_furniture-forge-1.20.1-3.0.1.jar
appleskin-forge-mc1.20.1-2.5.1.jar
aquamirae-6.API15.jar
architectury-9.1.13-forge.jar
bagus_lib-1.20.1-4.3.0.jar
balm-forge-1.20.1-7.2.1.jar
BedBenefits-Forge-1.20.1-13.0.3.jar
BetterAdvancements-1.20.1-0.3.2.162.jar
betterarcheology-1.1.5-1.20.1.jar
BetterBurning-Forge-1.20.1-9.0.2.jar
bettercombat-forge-1.8.4+1.20.1.jar
blossom-forge-1.20.1-1.0.7.jar
blueprint-1.20.1-7.0.0.jar
Boat-Item-View-Forge-1.20.1-0.0.5.jar
Bookshelf-Forge-1.20.1-20.1.9.jar
BotanyPots-Forge-1.20.1-13.0.23.jar
botarium-forge-1.20.1-2.3.3.jar
chat_heads-0.10.31-forge-1.20.jar
cherishedworlds-forge-6.1.4+1.20.1.jar
citadel-2.5.3-1.20.1.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.3.jar
ColdSweat-2.2.5.1.jar
CorgiLib-forge-1.20.1-4.0.0.4.jar
creeperoverhaul-3.0.1-forge.jar
curios-forge-5.7.0+1.20.1.jar
CustomSkinLoader_ForgeActive-14.19.1.jar
DivineRPG-1.10.7.3.jar
dungeons-and-taverns-pillager-outpost-rework-1.1.jar
dynamiclightsreforged-1.20.1_v1.6.0.jar
embeddium-0.3.1+mc1.20.1.jar
embeddiumextras-1.20.1-v2.0.0.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.13.jar
enchantwithmob-1.20.1-11.7.2.jar
ends_delight-1.20.1-1.0.1.jar
Enhanced_Celestials-forge-1.20.1-5.0.0.2.jar
explorify-v1.3.0-mc1.20.jar
Fallingleaves-1.20.1-2.1.0.jar
fancymenu_forge_3.0.6_MC_1.20.1.jar
FarmersDelight-1.20.1-1.2.4.jar
ferritecore-6.0.1-forge.jar
firstperson-forge-2.3.3-mc1.20.1.jar
gardens-of-the-dead-forge-4.0.1.jar
geckolib-forge-1.20.1-4.4.2.jar
hardcorerevival-forge-1.20.1-12.0.1.jar
Highlighter-1.20.1-forge-1.1.9.jar
HopoBetterRuinedPortals-[1.20-1.20.2]-1.3.7.jar
iceandfire-2.1.13-1.20.1-beta-4.jar
Iceberg-1.20.1-forge-1.1.18.jar
immersive_weathering-1.20.1-2.0.1-forge.jar
InsaneLib-1.12.1-mc1.20.1.jar
ItemBorders-1.20.1-forge-1.2.1.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
LegendaryTooltips-1.20.1-forge-1.4.5.jar
lithostitched-forge-1.20.1-1.1.5.jar
L_Enders_Cataclysm-1.90 -1.20.1.jar
make_bubbles_pop-0.2.0-forge-mc1.19.4+.jar
melody_forge_1.0.2_MC_1.20.1-1.20.4.jar
memoryleakfix-forge-1.17+-1.1.5.jar
modelfix-1.14.jar
moonlight-1.20-2.9.15-forge.jar
MouseTweaks-forge-mc1.20-2.25.jar
naturalist-forge-4.0.3-1.20.1.jar
netherportalfix-forge-1.20-13.0.1.jar
nethersdelight-1.20.1-4.0.jar
notenoughanimations-forge-1.7.1-mc1.20.1.jar
Nullscape_1.20.4_v1.2.4.jar
obscure_api-15.jar
oculus-mc1.20.1-1.6.15.jar
okzoomer-forge-1.20-3.0.1.jar
OpenLoader-Forge-1.20.1-19.0.3.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
Prism-1.20.1-forge-1.0.5.jar
ProgressiveBosses-3.9.4-mc1.20.1.jar
Quark-4.0-436.jar
REIPluginCompatibilities-forge-12.0.93.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
resourcefullib-forge-1.20.1-2.1.23.jar
RoughlyEnoughItems-12.0.684-forge.jar
RoughlyEnoughProfessions-forge-1.20.1-2.0.2.jar
rubidium-extra-0.5.4+mc1.20.1-build.116.jar
SereneSeasons-1.20.1-9.0.0.46.jar
shulkerboxtooltip-forge-4.0.4+1.20.1.jar
smoothboot(reloaded)-mc1.20.1-0.0.4.jar
sound-physics-remastered-forge-1.20.1-1.3.1.jar
starlight-1.1.2+forge.1cda73c.jar
supplementaries-1.20-2.7.36.jar
Terralith_1.20.4_v2.4.11.jar
textrues_embeddium_options-0.1.5+mc1.20.1.jar
TheOuterEnd-1.0.1.jar
twilightforest-1.20.1-4.3.1893-universal.jar
umbral_skies-1.3.jar
witherstormmod-1.20.1-4.0.1.1.jar
YungsApi-1.20-Forge-4.0.3.jar
YungsBetterDesertTemples-1.20-Forge-3.0.3.jar
YungsBetterDungeons-1.20-Forge-4.0.3.jar
YungsBetterEndIsland-1.20-Forge-2.0.5.jar
YungsBetterJungleTemples-1.20-Forge-2.0.4.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
Zeta-1.0-13.jar
[Forge]ctov-3.4.2.jar

</details>

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by WenXin20** [comment]
This also crashes with the CompressingDisplay
https://gist.github.com/WenXin20/dcd1255e20684d7e8f6b2bf95bd05d8a

**Comment by PixelFederico** [comment]
Hi, i'm having the same issue with all displays on common\src\main\java\earth\terrarium\adastra\common\compat\rei\displays and i tried to add a @REIPluginCompatIgnore (in all display classes) as you done in a merge in the 1.20.x branch (#521) and rebuild, but it seems that in the 1.20.1 branch it is not working this workaround

**Comment by AlexNijjar** [comment]
Has been fixed in dev.
