### ISSUE TITLE
[Feature Request]: Config option to disable lantern extinguishing

### ISSUE THREAD

**Issue by IchHabeHunger54** [terrarium-earth/Ad-Astra#493]
### Is your feature request related to a problem?

I am making a modpack that disables the nether, so Glowstone and Soul Torches are not available. As a result, I need an alternative option for in-space lighting.

### Solution(s)

I'd like to have a config option that allows lanterns to remain lit in space and not be extinguished.

### Describe alternatives you've considered

Require the player to use other means of lighting, which isn't really cool. I feel like lanterns make the most sense to use.

### Mod Version

1.12.7

### Mod Loader Version

1.19.2-43.3.8

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
this was added in 1.20.1+ and wont be backported
