### ISSUE TITLE
Photovoltaic Vesnium Cell

### ISSUE THREAD

**Issue by Rogenar** [terrarium-earth/Ad-Astra#497]
### Bug Description

Cannot make Photovoltaic Vesnium Cell. Is this a mistake or an item that needs to be found?

### How to Reproduce?

.

### Expected Behavior

.

### Version

1.16.5

### Mod Loader Version

1.20.4 0.15.7

### Mod Loader

Fabric

### Logs or additional context

[latest.log](https://github.com/terrarium-earth/Ad-Astra/files/14393206/latest.log)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
It's for a new solar panel tier we are adding in the future. item has no use right now.
