### ISSUE TITLE
[Bug]: Sliding door no longer lockable

### ISSUE THREAD

**Issue by JayBkr** [terrarium-earth/Ad-Astra#501]
### Bug Description

Playing on ATM9 and I recently updated the pack which took my Ad Astra from .15 to .18, on .15 I was able to lock the doors via a wrench however after the update ( and breaking and replacing the doors ) i no longer seem to be able to shift right click with any wrench to toggle the door to locked even on a new test world.

### How to Reproduce?

Place an Iron sliding door
Shift right click with a wrench 
No feedback is given

### Expected Behavior

Door locks and UI shows a locked message

### Version

1.15.18

### Mod Loader Version

1.20.1 Forge 47.2.20

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
https://github.com/terrarium-earth/Ad-Astra/assets/61668546/9c30f940-01c0-419c-b01e-af3f542c129e

Can't reproduce. Keep in mind this only works with an ad astra wrench

**Comment by JayBkr** [comment]
Ok, good to know - there must have been some form of wrench unification going on outside of the mod as .15 i was able to use an rf tools wrench, I can confirm using the ad astra wrench is working
