### ISSUE TITLE
Crash When loading mods in 1.19.2 with Mod Version 1.11.5

### ISSUE THREAD

**Issue by AubthurYoung** [terrarium-earth/Ad-Astra#51]
### Bug Description

Game crashed when I loading mods
I was using Ad_Astra_forge 1.11.4 and it could entry the game.
Now is Ad_Astra_forge 1.11.5
Here is the reports

[minecraft-exported-crash-info-2022-11-21T17-15-39.zip](https://github.com/terrarium-earth/Ad-Astra/files/10054082/minecraft-exported-crash-info-2022-11-21T17-15-39.zip)

[minecraft-exported-logs-2022-11-21T17-15-43.log](https://github.com/terrarium-earth/Ad-Astra/files/10054083/minecraft-exported-logs-2022-11-21T17-15-43.log)

### How to Reproduce?

Trying to entry the game

### Version

1.11.4 Ad_Astra_forge

### Mod Loader Version

43.1.2 Forge

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
<img width="657" alt="Screenshot 2022-11-21 at 4 40 17 PM" src="https://user-images.githubusercontent.com/61668546/203172514-cb210c9d-0278-4abc-9073-f6e037c666c7.png">

Ad Astra rquires [Botarium](https://www.curseforge.com/minecraft/mc-mods/botarium)

**Comment by AubthurYoung** [comment]
thank you very much！
