### ISSUE TITLE
Minecraft Mods Break the Landing Sequence.[Bug]: 

### ISSUE THREAD

**Issue by Gjeff8080** [terrarium-earth/Ad-Astra#510]
### Bug Description

Just for reference, I was on a server with a couple of my friends on a 1.19.4 server and we had the Ad Astra mod installed for space exploration. After messing around with other mods and gearing up for space we started to take off. Everything up to the landing was smooth sailing.  What happened, however, was in fact, the very opposite. All three of us were kicked out of our rockets on sync and we all plummeted to our deaths along with are space ships.  What I found weird was it put me in a swimming animation which might be the reason but its unlikely. Along with that, it's not like our space ships disappeared, we were just kicked out of it. After long and grueling testing with the mods I had installed, I figured out it was the Transit Railway mod (https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway) There are other mods I'm sure that cause this issue but this is the one I had installed. While yes, I do realize it is an issue with Transit Railway, I believe that this information could at least help problem-shoot with other issues people are having. And if there really isn't any fix I would at least like to understand the reason why this is happening because it really was very annoying. 

### How to Reproduce?

1. Install Ad Astra and dependencies
2. Install Minecraft Transit Railway
3. Try to land with a rocket and you will be kicked out.

### Expected Behavior

I was expecting to be in the rocket and be able to hold space to slow down.

### Version

1.14.1

### Mod Loader Version

1.19.4

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [x] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Heres the issue for it on their tracker, it contains why it happens and what they should do but hasnt been fixed for 4 mc versions. https://github.com/Minecraft-Transit-Railway/Minecraft-Transit-Railway/issues/427
