### ISSUE TITLE
[Feature Request]: Adding url to radio in game

### ISSUE THREAD

**Issue by starter3xd** [terrarium-earth/Ad-Astra#514]
### Is your feature request related to a problem?

Can't play my favourite radio stations

### Solution(s)

Add a text field to add stations to the list

### Mod Version

1.15.18

### Mod Loader Version

47.2.20

**Comment by ThatGravyBoat** [comment]
No, if you want to listen to your radio station and know what you are doing you can override the launch property with the json location but you can PR it to the repo for everyone

**Comment by KLONOA9X6** [comment]
Wait, I just found this in the source code[src/main/java/earth/terrarium/adastra/common/utils/radio/StationLoader.java#L46](https://github.com/terrarium-earth/Ad-Astra/blob/1.20.x/common/src/main/java/earth/terrarium/adastra/common/utils/radio/StationLoader.java#L46)

I think it's possible to load station list from local file
