### ISSUE TITLE
[Bug]: steel ingot crafting blocked by refined iron crafting from tech reborn

### ISSUE THREAD

**Issue by Theresnine** [terrarium-earth/Ad-Astra#516]
### Bug Description

While playing the mod pack prominence II, you cannot smelt a iron ingot in a blast furnace to get steel ingots that belong to ad astra. You will only receive Tech reborn steel ingots or refined iron - I've checked multiple forms and YT videos and cannot find a fix. I also have steel blocks from ad astra that I tried to break down to steel ingots and it only gives the steel ingot from tech reborn 

### Version

1.20.1

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
tell prominence to update to the latest Ad astra version, or update Ad Astra yourself. the recipe got moved to a new machine: the etrionic blast furnace in a recent update
