### ISSUE TITLE
[Feature Request]: Add hotkey for enabling/disabling jetsuit flight on jumping

### ISSUE THREAD

**Issue by ajsnarr98** [terrarium-earth/Ad-Astra#519]
### Is your feature request related to a problem?

The jetsuit flight is awesome to have sometimes, and it's a really good set of armor, but I don't always want the flight behavior when sprint-jumping.

### Solution(s)

A quick fix might be to add a hotkey to the controls for ad astra that allows the player to toggle between enabling/disabling the jetsuit flight behavior on jumping.

### Mod Version

1.12.7

### Mod Loader Version

1.19.2-43.2.6

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
This was added in 1.20.1 and wont be backported
