### ISSUE TITLE
[Bug]: Game crashes upon entering world

### ISSUE THREAD

**Issue by Mega-Godzilla3000** [terrarium-earth/Ad-Astra#52]
### Bug Description

I have recently downloaded Ad Astra! for fabric 1.18.2 and when I join any world it crashes instantly. I should mention I am making a custom modpack so maybe its possible there is some conflict? 

The console log mentions its"Trying to access unbound value".

With or without better crashes it closes the game instantly.

### How to Reproduce?

Open minecraft
Attempt to join any world
The game crashes

### Expected Behavior

The world doesnt crash and it loads

### Version

Fabric 1.0.5 (also tried 1.0.3, same thing happens)

### Mod Loader Version

0.14.9

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/0rykTjde 
Here is the crash report

**Comment by AlexNijjar** [comment]
can you report this on teamfusion's Github? I don't think it's an Ad Astra  issue
