### ISSUE TITLE
[Bug]: Tag lives_without_oxygen doesnt work

### ISSUE THREAD

**Issue by Lucas-Carrarini** [terrarium-earth/Ad-Astra#524]
### Bug Description

Mobs in the tag that Prevent dying from oxygen still affected in the planets

### How to Reproduce?

1. Go to a planet
2. Spawn a Warden (is on the tag list)
3. See the mob dying slowy

### Expected Behavior

Is expected that mobs under the tag survive in the planets

### Version

1.15.17

### Mod Loader Version

1.20.1 - 47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
you need to add it to the `can_survive_extreme_cold` and/or `can_survive_extreme_heat` tag as well because it's probably taking temperature damage.
