### ISSUE TITLE
[Bug]: Reinforced door does not work with redstone 1.20.1

### ISSUE THREAD

**Issue by RunTellObama** [terrarium-earth/Ad-Astra#526]
### Bug Description

I assume this is a bug as all the other doors work with redstone

### How to Reproduce?

1: Place a reinforced door
2: Place a lever next to it
3: Power the lever and door doesnt open

### Expected Behavior

The door should open when powered and close when not

### Version

1.15.18

### Mod Loader Version

1.20.1 - Forge 47.2.20

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
is it working now?
