### ISSUE TITLE
[Bug]: Using a Sliding Door and a piston causes the world to crash.

### ISSUE THREAD

**Issue by torikun9971** [terrarium-earth/Ad-Astra#527]
### Bug Description

When you place a piston next to an open Sliding Door, facing the door, and give the piston a signal, the world crashes.

### How to Reproduce?

1. Place a Sliding Door.
2. Position a piston underneath the door, facing towards it.
3. Put a lever in a spot where it will activate both the piston and the door.
4. Click the lever.
5. The world crashes.

### Expected Behavior

The piston breaks the door and extends by one block.

### Version

1.15.18

### Mod Loader Version

1.20.1-47.2.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Send the crash log

**Comment by torikun9971** [comment]
Crash Report: https://mclo.gs/HXXGZK1

**Comment by Burchard36** [comment]
Can confirm this is also a bug in ATM9 - https://mclo.gs/fwNbJv0

**Comment by Torikun9971** [comment]
As stated in the crash report, I only have four mods installed
