### ISSUE TITLE
[Feature Request]: I hope use jpeg url at flag

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#53]
### Is your feature request related to a problem?

Currently, flag url is must be ends with .png
But in imgur, some images is on jpg url.

Surprisingly, if I change the extension from jpeg to png, it loads normally.
Like this (test url: https://i.imgur.com/fgOXKnw.jpg)
![Jpeg](https://user-images.githubusercontent.com/44163945/203095897-b8504929-94cb-4bd3-8bbb-d6cb94df7dea.gif)

I want to directly input the jpeg url without changing the extension.

### Solution(s)

Allow jpg extension in image url.
That's all.

### Mod Version

1.1.5

### Mod Loader Version

(Forge) 1.19.2 - 43.1.52
(Fabric) 1.19.2 - 0.66.0

**Comment by AlexNijjar** [comment]
Fixed. Gravy wants to do more stuff with this though so I'll keep it open
