### ISSUE TITLE
[Bug]: Ad Astra Wiki makes no mention of EMI compatibility

### ISSUE THREAD

**Issue by sylv256** [terrarium-earth/Ad-Astra#531]
### Bug Description

It seems as though EMI is compatible with Ad Astra. If it is not, please state as such. The Optional Dependencies section does not mention EMI.

**Comment by CodexAdrian** [comment]
Ad Astra has no compat with EMI. It is not explicitly incompatible with it, but we don’t feel the need to explicitly state a relationship with EMI as our mod does not have a relationship with EMI.

**Comment by sylv256** [comment]
Would it be reasonable to submit a PR adding EMI support? Why was EMI support removed?

**Comment by CodexAdrian** [comment]
We wouldn’t guarantee that it would be maintained or be kept up to date with new additions to the mod. It’s too much work to maintain compatibility with 3 different recipe viewers. It would honestly be better if you decided to make compat to upload it as its own mod as an addon to Ad Astra
