### ISSUE TITLE
[Feature Request]: Make the wiki open source

### ISSUE THREAD

**Issue by sylv256** [terrarium-earth/Ad-Astra#532]
### Is your feature request related to a problem?

I'm quite perturbed by the fact that I can't contribute to the wiki even if I wanted to.

### Solution(s)

If you don't use anything proprietary, why don't you open source the wiki so others can contribute? This mod doesn't appear to support EMI and it would help EMI users a lot if the wiki had more information about gameplay.

### Describe alternatives you've considered

Add EMI support.

### Mod Version

N/A

### Mod Loader Version

N/A

### Mod Loader

N/A

### Additional context

I've tried looking up recipes of your mod using EMI and none of the custom ones (specifically for the rocket) work.

**Comment by ThatGravyBoat** [comment]
it is opensource https://github.com/terrarium-earth/Ad-Astra-Docs

**Comment by CodexAdrian** [comment]
The documentation *is* open source, https://github.com/terrarium-earth/Ad-Astra-Docs. But it’s for developers. We are not the creators of the Fandom, don’t have any control over it, and don’t recommend you use it as it’s outdated and inaccurate and Fandom is a terrible site.
