### ISSUE TITLE
[Bug]: Oil not spawning in on server

### ISSUE THREAD

**Issue by zyrans** [terrarium-earth/Ad-Astra#537]
### Bug Description

Have all the required mods/relations, i have just progressed to the part of where oil is needed to fuel the rocket. There is no oil anywhere to be seen in the ocean on the server. I copied the seed and loaded into a single player server and to my surprise the oil was there! even created another world with the same seed again to double check and it was there. just to triple check i made a random world with a random seed and the oil appeared. its just not showing on my online hosted server???????? 

very confused, i thought this mod worked for multiplayer. 

### Version

1.20.4

### Mod Loader Version

1.20.4-1.16.5

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
did you create the server and load chunks before you added ad astra?

**Comment by zyrans** [comment]
yea, would this be the reason why? if so is there any way to fix the issue?

**Comment by AlexNijjar** [comment]
yes, that's the issue, you can't add structures to existing chunks. you'll need to either regenerate those chunks or reset your server

**Comment by zyrans** [comment]
ok thanks for the info and for helping me! great mod btw! :D
