### ISSUE TITLE
Add an option to disable the "oil fountain" thingys in the ocean

### ISSUE THREAD

**Issue by SalmonSnakeD** [terrarium-earth/Ad-Astra#538]
I personally don't like them, thats all.

**Comment by arcmega** [comment]
Same need here, trying to do a modpack in 1.19 and can't remove them.

**Comment by AlexNijjar** [comment]
Please use a datapack to remove them. add `"replace": true` and leave the values array empty
https://github.com/terrarium-earth/Ad-Astra/blob/1.20.x/common/src/main/generated/resources/data/ad_astra/tags/worldgen/biome/has_structure/oil_well.json
