### ISSUE TITLE
[Bug]: Fluids not showing correctly in Create Mod Basins

### ISSUE THREAD

**Issue by kienerxyzzy** [terrarium-earth/Ad-Astra#542]
### Bug Description

When pouring Cryo Fuel in to a basin from the Create Mod, it doesn't show the fluid, however, if you pour another fluid, you will see certain particles of it.
MC version:1.20.1

### How to Reproduce?

1. Place a basin from Create Mod (0.5.1)
2. Pour a bucket of Cryo Fuel into the basin

### Expected Behavior

Cryo Fuel should appear in the basin.

### Version

I don't know

### Mod Loader Version

1.20.1 - 47.2.30

### Mod Loader

Forge

### Logs or additional context

I have not tested this with the Fluid Tanks and other Ad Astra liquids.

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by noahonfyre** [comment]
Can confirm, that this also applies to Fluid Tanks and other Ad Astra fluids such as oil and fuel.

Here's a screenshot of Cryo Fuel, Normal Fuel and Oil in Fluid tanks.
https://imgur.com/a/J54T0ix

**Comment by AlexNijjar** [comment]
fixed in dev already
