### ISSUE TITLE
[Bug]: Maven is broken

### ISSUE THREAD

**Issue by Sollace** [terrarium-earth/Ad-Astra#545]
### Bug Description

I want to add ad-astra to my project to test compatibility but following what it says in the README, the project doesn't appear to exist on that maven, nor is there anything. As far as I can tell the maven is completely empty.

The same goes for the one listed in your build.gradle.tks.

Tested using:
```
repositories {
    maven { name 'Ad-Astra'; url "https://maven.teamresourceful.com/repository/maven-public/" }
    maven { name 'Ad-Astra Updated'; url "https://maven.teamresourceful.com/repository/terrarium/" }
}

dependencies {
   modImplementation "earth.terrarium.adastra:adastra-fabric-${project.minecraft_version}:1.15.18" // version from modrinth
}
```

### Version

N/A

### Mod Loader Version

N/A

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
This is my bad. In 1.20.4+ the underscore was removed from the artifact ID and the README was changed to reflect that. However older versions like 1.20.1 still use the underscore. I've updated the README to show both versions

This should work
```groovy
repositories {
    maven { name 'Ad-Astra'; url "https://maven.teamresourceful.com/repository/maven-public/" }
}

dependencies {
   modImplementation "earth.terrarium.adastra:ad_astra-fabric-${project.minecraft_version}:1.15.18" // version from modrinth
}
```

**Comment by Sollace** [comment]
Ah excellent, thank you very much!
