### ISSUE TITLE
[Bug]: Game crashes on steel ingot being placed in coal generator

### ISSUE THREAD

**Issue by science-quiz** [terrarium-earth/Ad-Astra#55]
### Bug Description

I accidentally shift clicked a steel ingot into the coal generator.  This caused the game to crash with the exception:
`The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "net.fabricmc.fabric.api.registry.FuelRegistry.get(net.minecraft.class_1935)" is null`
The world is unable to be recovered and upon loading repeats the error.

### How to Reproduce?

1. Load up a world with Ad Astra and its dependencies, no other mods.
2. Place a coal generator
3. Place a steel ingot in the coal generator.

### Expected Behavior

Either the ingot is unable to be inserted as fuel, or insertion does not cause a crash or any power generation.

### Version

1.11.4

### Mod Loader Version

0.14.9-1.19.2

### Mod Loader

Fabric

### Logs or additional context

Crash report: https://pastebin.com/txeZ0GYv
Logs: https://pastebin.com/8uSHetrx

This occurred both in an established world with minimal lag and a newly-created world with high lag due to initial chunk loading.

**Comment by AlexNijjar** [comment]
It’s fixed in the latest version

**Comment by science-quiz** [comment]
> 

I'm running the latest version as on modrinth, ad astra 1.11.4 for fabric 1.19.2

**Comment by AlexNijjar** [comment]
![75C2138A-7AD0-405C-9B77-F7B52A057E68](https://user-images.githubusercontent.com/61668546/203215232-114b4ac0-e5eb-4890-aaf1-ec2bc04e8944.jpeg)

this is the latest version

**Comment by science-quiz** [comment]
Ah, I am apparently blind.  Thank you!
