### ISSUE TITLE
[Feature Request]: Swap chest and leg armor values.

### ISSUE THREAD

**Issue by Terra-B-Welch** [terrarium-earth/Ad-Astra#551]
### Is your feature request related to a problem?

I know it sounds really stupid, but I always get a little annoyed when I find the chest and leg armors are backwards in mods.

### Solution(s)

Just switch the values of the chests and legs of the space suits.

Space Suit: 5 -> 6
Space Legs: 6 -> 5

Netherite Space Suit: 6 -> 8
Netherite Space Legs: 8 -> 6

Jet Suit: 7 -> 9
Jet Legs: 9 -> 7

### Describe alternatives you've considered

Literally just swap the chest and legs armor values. (Or heck, maybe allow an option to modify the armor values of the suits in the config for modpack creators)

### Mod Version

1.15.18

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Additional context

I'll likely find my own way to do this in my own personal modpack, but I feel like it should just be the default...

Also I guess if this is already a thing in versions for later versions of minecraft then I guess this is redundant aint it?

**Comment by AlexNijjar** [comment]
Oops, had no idea they were reversed.
