### ISSUE TITLE
[Bug]: Astrodux is non existent for beta .18 and .17 and steel cannot be smelted

### ISSUE THREAD

**Issue by EgorAkulyonak** [terrarium-earth/Ad-Astra#561]
### Bug Description

I installed late mod version for (neo)forge 1.20.1 and decided to test dimensions&load in creative. I'm dummy so looked up for guide book. Nothing of sorts in JEI and default creative menu, internet crafts also don't work, be it smelting iron to get steel or creating book itself

At modrinth learned that it's a beta, downgraded to 1.15.17 with no success either

Went straight for release not testing alpha ones and got it all right

I have no other tech mods installed: mostly magic, animals and world generation, couple of dimensions. Maybe lack of tech mods made steel unobtainable by vanilla means (only some kind of... Smeltery? with dark interface, combining iron and coal in upper slots, can't find that recipe now in jei) since there were some issues with mods overriding steel crafts

### How to Reproduce?

1. Happily download latest version for 1.20.1
2. Use jei of sorts
3. Search for any book
3.5 In despair try looking through /give

### Expected Behavior

Internet's crafts are not a lie, steel can be obtained by smelting iron, book and 8 steel give you core what to do

### Version

1.15.17-.18

### Mod Loader Version

1.20.1 (neo)Forge 47.1.106

### Mod Loader

NeoForge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
by "internet crafts," I assume you looked at the fandom page. please do not trust that page, I have no control over it and it's outdated and inaccurate. You need [Patchouli](https://www.curseforge.com/minecraft/mc-mods/patchouli) for the guide book and steel is created by combining coal and iron in an etrionic blast furnace in alloying mode.
