### ISSUE TITLE
[Bug]: lava turns to ice in space when placed from a bucket

### ISSUE THREAD

**Issue by L-D3P0** [terrarium-earth/Ad-Astra#562]
### Bug Description

![2024-06-09_12 01 01](https://github.com/terrarium-earth/Ad-Astra/assets/75185442/e6e2ee55-0581-4674-b6d6-de8a0f3ccb54)

### How to Reproduce?

go to anywhere in the solar system then place lava down from a bucket

### Version

ad_astra-forge-1.19.2-1.12.7

### Mod Loader Version

1.19.2

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
fixed in 1.20.1. I don't support 1.19.2 anymore.

**Comment by L-D3P0** [comment]
> fixed in 1.20.1. I don't support 1.19.2 anymore.

oh, ok...
