### ISSUE TITLE
[Bug]: Oxygen and Fuel don't show up in Tanks and are fully transparental. ViewBug.

### ISSUE THREAD

**Issue by cyberpunkbln** [terrarium-earth/Ad-Astra#563]
### Bug Description

In Mekanism and other Tanks the both liquids oxygen and fuel only show a transparental nothing/air.

### Version

ad_astra-forge-1.20.1-1.15.18.jar

### Mod Loader Version

47.2.32

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
This is fixed in dev already.

**Comment by cyberpunkbln** [comment]
Kool, can you tell me where i can get a dev-build for forge? or only self-compile?
