### ISSUE TITLE
[Bug]: Items missing: hammer and astrodux

### ISSUE THREAD

**Issue by itsDiiMS** [terrarium-earth/Ad-Astra#573]
### Bug Description

hey, im new to ad astra and the mod is missing the starter guide (astrodux) and the hammer. i cant seem to find anything anywhere adressing this issue, im on fabric 1.20.1.

a little help would be appreciated!

### Version

1.15.18

### Mod Loader Version

1.20.1

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by gagahdragon** [comment]
Hammer is replaced with compressor block. For Astrodux, you need Patchouli mod installed.

**Comment by kienerxyzzy** [comment]
It has been solved, somebody please close this
