### ISSUE TITLE
[Feature Request]: Include `stations.json` in mod so that I can be locally edited

### ISSUE THREAD

**Issue by Chris6ix** [terrarium-earth/Ad-Astra#578]
### Is your feature request related to a problem?

Currently, you can only play a handful of pre-selected radio stations from [this list ](https://github.com/terrarium-earth/Ad-Astra/blob/1.20.x/stations.json) hosted on GitHub. This really isn't great, as this file can't be easily edited, and it took quite some effort to even find it.

### Solution(s)

Include the file mentioned above with the mod as a config, which would allow players to easily modify it and listed to their favorite radio stations.

### Describe alternatives you've considered

I guess you could create prs for every radio station you want to add, but this would a) take unnecessarily long as it would take time to have the pr merged and b) would add radio stations for every player that uses the mod which they may not like and would just clutter everyone's radio list for no good reason.

### Mod Version

1.15.18

### Mod Loader Version

1.20.1-47.3.1

### Mod Loader

Forge

### Additional context

/

**Comment by ThatGravyBoat** [comment]
This is already a thing but is hidden behind a flag as to not allow anyone to just do it, as you need to know what stations you are adding to the file as you can add stations with a different audio format or range which can cause audio distortions or can just cause the audio to just turn into ear hurting high pitch sounds.

You can access via the `-Dadastra.stations=fully:qualified/path/to/your.file` JVM argument

**Comment by Chris6ix** [comment]
Eh...kinda weird reason to hide such an important feature, but better than not having it at all.
Thank you for explaining it at least, managed to get it to work now after some tinkering.

The feature desperately needs proper documentation though or at least should be added as a config setting (even if it states that you should only turn it on if you know what you are doing) instead of a hidden, undocumented jvm flag...
