### ISSUE TITLE
[Bug]: Config has no effect on the game

### ISSUE THREAD

**Issue by HttpRafa** [terrarium-earth/Ad-Astra#58]
### Bug Description

If you enter a value greater than 600 in the "Atmosphere Leave" setting in the config. The selection window still opens at 600 and if you close it with ESC you don't hear any more rocket sounds after 600 blocks.

If the value is less than 600 it will be ignored and the window will still open at 600 blocks.

I believe that closing it with ESC is probably not intentional. (Because then you fly upwards to infinity)

What I've also noticed is that "Countdown Ticks" seems to have no effect as well.

### How to Reproduce?

1. Go to the config
2. Change the values
3. And launch a rocket

### Expected Behavior

- The window should not be closable with ESC.
- The window should open at the correct height.
- The rocket should respond to the countdown change.

### Version

1.11.7

### Mod Loader Version

1.19.2 - 0.14.10

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
Were you in creative when you pressed esc? You can only exit the menu with esc in creative, not survival.

**Comment by HttpRafa** [comment]
> Were you in creative when you pressed esc? You can only exit the menu with esc in creative, not survival.

We only tested it in the Creative.

**Comment by ThatGravyBoat** [comment]
does this still happen with the new config?

**Comment by HttpRafa** [comment]
Im going to check that

**Comment by AlexNijjar** [comment]
I'll close this for now. If you're still experiencing this, lmk
