### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Rsepicus** [terrarium-earth/Ad-Astra#581]
### Bug Description

![image](https://github.com/terrarium-earth/Ad-Astra/assets/174942278/4c61397f-c062-4d9b-bedf-a2c5caf24f61)

### How to Reproduce?

Help

### Expected Behavior

help

### Version

1.12.6

### Mod Loader Version

1.19.2

### Mod Loader

Fabric

### Logs or additional context

help

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [ ] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by x13x54** [comment]
What mod's oil is in that bucket?
In the modpack i'm playing, it only allows adastra's oil, and **crude** oil from two other mods
Any other oil isn't accepted by the machine
