### ISSUE TITLE
[Bug]: Crash when someone joins server

### ISSUE THREAD

**Issue by waddon1** [terrarium-earth/Ad-Astra#59]
### Bug Description

When one player joins my server the whole server crashes. Not sure if it is cause by this mod specifically or Botarium.

### How to Reproduce?

1. Start server
2. Player joins and load chunks
3. Crash

### Expected Behavior

Not crash

### Version

1.11.7

### Mod Loader Version

43.1.55

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/jdMahY0Z

**Comment by QTpyeRose** [comment]
forge version:
i have worked out the exact cause, when an ad astra block tries to output fluid (though botarium) to a already full mechanisum fluid pipe. it crashes the entire game.
 
and from then on it will crash when ever that entity is loaded. (or the machine tries to push in more fluid when its loaded next)
 
this will crash the entire server.
 
step 1:
 
set up a coal generator, cryo refinery, basic mecahnical pipe (mekanisum), and basic tank (mekanisum) and use configerator (mekanisum) to change the mechanical pipe to have correct input and output. fill the tank with cryo liquid to make the process faster
 
 (as is seen here)
 ![image](https://user-images.githubusercontent.com/65490493/203695420-1424a3b7-d548-4961-9bb7-f45840cbfaea.png)
 
step 2: let the refinery run untill the tank is full, and then it will start filling up the pipe, once the pipe fully fills the game will then crash.

here is the crash log
[crash-2022-11-23_21.42.15-server.txt](https://github.com/terrarium-earth/Ad-Astra/files/10080866/crash-2022-11-23_21.42.15-server.txt)

extra info: 
mc: 1.19.2
fml: 43.1.52
mods: 
 Mekanism-1.19.2-10.3.5.473.jar
 cloth-config-8.2.88-forge.jar
 forge-1.19.2-43.1.52-universal.jar
 resourcefullib-forge-1.19.2-1.1.16.jar
 botarium-forge-1.19.2-1.7.10.jar
 ad_astra-forge-1.19.2-1.11.7.jar

**Comment by alfredggttv** [comment]
Adding to this, it isn't just Mek pipes. This is on my ATM8 server. Player was pumping from the Cryo Refinery with a fluid pipe from the Pipez mod.

Crash Log: https://mclo.gs/wWuVHzx

**Comment by AlexNijjar** [comment]
Fixed in the latest botarium version
