### ISSUE TITLE
[Bug]: Crafting Steel does not work with etrionic furnace

### ISSUE THREAD

**Issue by pirpirim** [terrarium-earth/Ad-Astra#607]
### Bug Description

I cant make steel ingots in any of the furnaces and I played on 1.15.18 and 1.15.17 and I cant do it in both of the versions

### Expected Behavior

crafting steel ingots

### Version

1.15.17

### Mod Loader Version

1.20.1 47.3.5

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AveryHazel** [comment]
Have you tried setting it to alloy mode and adding coal and iron?

**Comment by ThatGravyBoat** [comment]
As said above you need the machine in alloy mode

**Comment by ReallySadCircle** [comment]
wouldn't this be a completely different bug? The Etrionic Furnace *DELETES* Items instead of simply, *not processing them*
