### ISSUE TITLE
[Bug]: Ostrum Ingot Texture stretched

### ISSUE THREAD

**Issue by souldbminerr** [terrarium-earth/Ad-Astra#612]
### Bug Description

Its very stretched

### How to Reproduce?

Look at ingot

### Expected Behavior

It should not be stretched

### Version

1.15.18

### Mod Loader Version

1.20.1 Fabric 0.15.11

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AveryHazel** [comment]
This is a design choice, not a bug (not a dev, but it’s very obvious when you look at the texture file)
