### ISSUE TITLE
[Bug]: Crash on Startup With FastSuite

### ISSUE THREAD

**Issue by jamesipod** [terrarium-earth/Ad-Astra#63]
### Bug Description

Game Crashes upon startup. After Mojang Screen, before Title screen. 

### How to Reproduce?

Install Ad Astra and FastSuite Simultaneously 

### Expected Behavior

It should launch

### Version

1.11.7

### Mod Loader Version

1.19.2-43.1.57

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/d0D7kZz3

**Comment by AlexNijjar** [comment]
Fixed in latest version. Will be out soon
