### ISSUE TITLE
[Bug]: Ad Astra crashing minecraft on 1.20.1

### ISSUE THREAD

**Issue by muxira** [terrarium-earth/Ad-Astra#635]
### Bug Description

Minecraft crashing when launching

### How to Reproduce?

When I added the last Indium, Nvidium 0.2.9beta, Sodium 0.5.11it crashes

### Expected Behavior

to wark normal

### Version

1.20.1

### Mod Loader Version

1.201

### Mod Loader

Fabric

### Logs or additional context

[crash-2024-10-10_17.54.21-client.txt](https://github.com/user-attachments/files/17330210/crash-2024-10-10_17.54.21-client.txt)

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
This is another mod causing a crash in a mixin
