### ISSUE TITLE
[Bug]: Fluid Issues

### ISSUE THREAD

**Issue by kienerxyzzy** [terrarium-earth/Ad-Astra#639]
### Bug Description

![image](https://github.com/user-attachments/assets/a9857fc3-1557-48bf-a51c-84de0349b2e7)
It shows up in IE but not Mekanism fluid tanks?
![image](https://github.com/user-attachments/assets/e6fb846d-a95e-48ee-bc40-228b3af869a9)
It shows up ir your fuel refinery JEI page, but not on the JEI search bar? And somehow if I use EMI it shows up?
Please fix this, even if this is just a aesthetics issue.

### Expected Behavior

The fluid should shou up

### Version

1.15.18

### Mod Loader Version

1.20.1-47.3.0

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by kienerxyzzy** [comment]
Also, Cryo fuel has the same issue. I can live without fuel (because IE biodiesel) but cryofuel is not a thing to be undervalued.

**Comment by ThatGravyBoat** [comment]
Fixed in latest version

**Comment by kienerxyzzy** [comment]
![image](https://github.com/user-attachments/assets/c70f1698-3e96-4bd6-acd9-1dca3408818f)
thanks
