### ISSUE TITLE
[Bug]: Mod conflict with CraftGR causes a crash without an error message on 1.20.1 Forge

### ISSUE THREAD

**Issue by PwRhGaStPY** [terrarium-earth/Ad-Astra#643]
### Bug Description

the title explains it i think 

Forge Version: 
1.20.1 - 47.3.0

Mods Enabled:
ad_astra-forge-1.20.1-1.15.18 
botarium-forge-1.20.1-2.3.4 
cloth-config-11.1.136-forge 
craftgr-1.5.1-mc1.20.1 
resourcefulconfig-forge-1.20.1-2.1.2
resourcefullib-forge-1.20.1-2.1.29 
YetAnotherConfigLib-3.6.1+1.20.1-forge

Log: 
[https://mclo.gs/qvnRDes](https://mclo.gs/qvnRDes)  

Someone else having the same issue: 
[https://github.com/KabanFriends/CraftGR/issues/19](https://github.com/KabanFriends/CraftGR/issues/19)

### How to Reproduce?

1. Install Forge 

2. Install Ad Astra and its dependencies (If Ad Astra itself isn't installed or enabled, the client will not crash)

3. Install CraftGR and its dependencies (If CraftGR itself isn't installed or enabled, the client will not crash)

4. Open Minecraft 

5. Watch

### Expected Behavior

Minecraft not crashing I guess??

### Version

1.15.18

### Mod Loader Version

1.20.1 - 47.3.0

### Mod Loader

Forge

### Logs or additional context

https://mclo.gs/qvnRDes

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ChiefArug** [comment]
This is CraftGR's fault, they [shadow without relocating](https://github.com/KabanFriends/CraftGR/blob/master/neoforge%2Fbuild.gradle#L24) jlayer. Instead they should jar-in-jar it as Ad Astra does, or if they must shadow (there are very few reasons for this) relocate it to a different package using shadow's relocate feature.

**Comment by ThatGravyBoat** [comment]
^
