### ISSUE TITLE
[Bug]: Ad Astra breaking supplementaries cannons and causing crash

### ISSUE THREAD

**Issue by ZzamZ** [terrarium-earth/Ad-Astra#645]
### Bug Description

Putting tnt or other blocks in the cannon then trying to shoot it crashes the game.

### How to Reproduce?

Install both supplementaries and ad astra then put tnt inside the cannon. When you try to shoot it or position it the client will crash

### Expected Behavior

The cannon shoots the tnt or block just fine

### Version

1.15.18

### Mod Loader Version

1.20.1-47.3.11

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/x8rQYL16

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by MehVahdJukaar** [comment]
error here, unsafe cast to server level -> https://github.com/terrarium-earth/Ad-Astra/blob/bfa70ac3db6dca1c02ed6fad5be62649b2c23906/common/src/main/java/earth/terrarium/adastra/common/systems/TemperatureApiImpl.java#L42

**Comment by ThatGravyBoat** [comment]
Fixed in latest version
