### ISSUE TITLE
[Bug]: Burn Time is not update in Coal Generator GUI

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#65]
### Bug Description

![BurnTime](https://user-images.githubusercontent.com/44163945/204079955-293d2868-6f13-4b53-8a4b-b59295e9d156.gif)

### How to Reproduce?

1. Place 'Coal Generator'.
2. Put any burnable items.
3. Check burn time.

### Expected Behavior

Burn Time be countdown to 0

### Version

1.11.7

### Mod Loader Version

Forge: 43.1.52, Fabric: 0.66.0

### Mod Loader

Forge, Fabric

**Comment by AlexNijjar** [comment]
fixed in latest version

**Comment by AlexNijjar** [comment]
will be out soon
