### ISSUE TITLE
[Bug]: Landing rocket does not descend

### ISSUE THREAD

**Issue by Facest4b** [terrarium-earth/Ad-Astra#75]
### Bug Description

When to go to any planet, Earth or the moon from space, the landing rocket spawns at y=600, at the top of the height meter. You can hold space to activate the thruster, however the rocket doesn't fall or rise at all,

### How to Reproduce?

Launch into space with any rocket.
Go from space to Earth, the moon or any other planet
The rocket will not land

### Expected Behavior

The lander should descend immediately when spawning, allowing you to slow down and hit the ground.

### Version

1.11.8

### Mod Loader Version

1.19.2 - 43.1.47

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
Download Resourceful Config 1.0.11https://modrinth.com/mod/resourceful-config/versions and then delete your config file for ad astra.

**Comment by Facest4b** [comment]
> Download Resourceful Config 1.0.11https://modrinth.com/mod/resourceful-config/versions and then delete your config file for ad astra.

Perfect, all working now, thank you!
