### ISSUE TITLE
[Bug]: Game crash when clicking "moon" for first time

### ISSUE THREAD

**Issue by deadfleshkiller** [terrarium-earth/Ad-Astra#76]
### Bug Description

After building rocketship and flying up to the atmosphere, you have your first choice of "moon" to go to. When I click on "moon" the game immediately crashes. This happens on singleplayer and on a private server. It is a client-side only crash. This is with the ModPack "DreamCraft." My friend also plays on the server and has no crashes when going to "moon."

### How to Reproduce?

1. launch to space
2. view solar system menu
3. click on moon
4. game crash

### Expected Behavior

What was expected to happen was, the "moon" universe loading and being able to land the lander on the moon and play as normal.

### Version

1.0.3

### Mod Loader Version

0.14.9

### Mod Loader

Fabric

### Logs or additional context

https://pastebin.com/n5D1GAnm  <--- latest.log
[CRASH REPORT.txt](https://github.com/terrarium-earth/Ad-Astra/files/10127585/CRASH.REPORT.txt)

**Comment by ThatGravyBoat** [comment]
what GPU do you have?

**Comment by deadfleshkiller** [comment]
> what GPU do you have?

I have a 2080TI

**Comment by nichjamesr** [comment]
I am having this same problem and my log looks almost identical. Any fix for this that has been found?

**Comment by AlexNijjar** [comment]
It seems to only happen to certain GPUS which makes it very hard to reproduce. We rewrote a lot of the rendering in 1.19 however, it's not compatible with 1.18. As we no longer support 1.18 (with the exception for critical bug fixes)  My suggestion is to update to the latest 1.19 version.
