### ISSUE TITLE
[Bug]: Cant launch rocket

### ISSUE THREAD

**Issue by Kasax007** [terrarium-earth/Ad-Astra#77]
### Bug Description

I have this mod added in the 1.19.2 version of my modpack called Dreamcraft. With the latest update of the mod the rockets are unable to launch for some reason. I dont know why that is all of a sudden. Maybe you can find a way to debug it. 

### How to Reproduce?

1. Place Rocket
2. Fuel it
3. Try to launch

### Expected Behavior

No Launch 

### Version

Newest Fabric Release 

### Mod Loader Version

0.14.10

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
Should be fixed in the latest update
