### ISSUE TITLE
[Feature Request]: REI

### ISSUE THREAD

**Issue by theDonse** [terrarium-earth/Ad-Astra#79]
### Is your feature request related to a problem?

no

### Solution(s)

use REI's api over EMI/JEI as it is the widely adopted option 

### Mod Version

1.0.5

### Mod Loader Version

1.18.2 - Fabric

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
What exactly do you mean here?
Are you saying to remove JEI/EMI compat?
Or make REI the default in the dev environment on 1.18?
