### ISSUE TITLE
[Bug]: Crash when going into space

### ISSUE THREAD

**Issue by Ciphers2** [terrarium-earth/Ad-Astra#81]
### Bug Description

Launching the rocket as usual and reaching the space loading point in the sky causes a crash. This also breaks the save as it crashes on loading it.

### How to Reproduce?

1. Launch rocket
2. Reach required height to reach space
3. Crash

### Expected Behavior

Launch Rocket, go to space.

### Version

1.11.8

### Mod Loader Version

1.19.2 - 0.14.11

### Mod Loader

Fabric

### Logs or additional context

Other mods are installed. Game runs fine until loading space.

https://pastebin.com/WUwSgRTn

**Comment by AlexNijjar** [comment]
Will be fixed in the latest update. For now, installing architectury API fixes the problem.
