### ISSUE TITLE
[Bug]: (May be outdated with latest update) Pressing space to launch rocket does nothing, no key bind conflict

### ISSUE THREAD

**Issue by Dominion42** [terrarium-earth/Ad-Astra#85]
### Bug Description

Modpack running version 1.11.8 (Fabric) on multiplayer server, no one is able to launch rockets, pressing space does nothing and there are no key bind conflicts apparent (checked options text file). Saw similar issue but with keybind conflict (create specifically), so wording with 1.11.9 changelog seems unsure if thats what was fixed or the overall problem was fixed.

### How to Reproduce?

Get rocket
Place on launchpad
Fuel it up
Get inside
Press space

### Expected Behavior

Rocket should launch when space is pressed

### Version

1.11.8

### Mod Loader Version

Unkown

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
1.11.9 should fix that issue. I believe it was a conflict with mouse wheelie. lmk if it's still broken in the new version.
