### ISSUE TITLE
[Bug]: Crash On Startup

### ISSUE THREAD

**Issue by kittypawheart** [terrarium-earth/Ad-Astra#87]
### Bug Description

crash on startup w/ error message Error: java.lang.IllegalArgumentException: Failed to create player model for default

### Version

1.11.9

### Mod Loader Version

43.1.52

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/DZaiQBe5

**Comment by AlexNijjar** [comment]
try updating forge an ad astra to the latest version. lmk if it's still happening after that
