### ISSUE TITLE
[Bug][Forge]: Dont' translate name of fluid added from other mods

### ISSUE THREAD

**Issue by gisellevonbingen** [terrarium-earth/Ad-Astra#89]
### Bug Description

![image](https://user-images.githubusercontent.com/44163945/207495044-f4fdca47-7886-4ad3-a463-2ee9b7907516.png)

Found during test after set tag other mods fluids as `"ad_astra:fuel"`.
Looks problem only in forge.

These fluid name are showing normally in this code.
```
FluidStack fluid = new FluidStack(THATMODFLUIDS.THATFLUID.get(), SOME_AMOUNT, null);
Component normalName = fluid.getDisplayName();
String normalKey = fluid.getTranslationKey();
```

### How to Reproduce?

1. Download `'Immersive Engineering'`
2. Set `'#forge:diesel'`, `'#foge:biodiesel'` as `'ad_astra:fuel'` tag.
3. Launch minecraft and put that fluid buckets in Rocket.

![image](https://user-images.githubusercontent.com/44163945/207496245-99559c1b-d2a1-4edb-b767-9035cb285118.png)

### Version

1.11.9

### Mod Loader Version

1.19.2-43.2.0

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
i believe i fixed this a while ago

**Comment by gisellevonbingen** [comment]
1.19.2-1.12.4 has still problem
