### ISSUE TITLE
Cache worldHasOxygen as it is called a lot.

### ISSUE THREAD

**Issue by ghost** [terrarium-earth/Ad-Astra#9]
This method was using 1.98% of the sever thread by itself since every living entity calls it every tick.
For reference mods like AE2 use roughly 5% of the server thread.

For reference here's the modification I made for use on AOF, brings the usage down to 0.01% which I think is as good as spark can measure:
https://github.com/Ellemes/Ad-Astra-Fabric/commit/f66fbabc68bbab216109f85f63995e476860f831

**Comment by Bunny-Proxima** [comment]
Thank you for bringing this up! We'll look into it.

**Comment by HmmmHmmmm** [comment]
maybe do a pull request this : https://github.com/Ellemes/Ad-Astra-Fabric/blob/1.18/src/main/java/com/github/alexnijjar/ad_astra/util/OxygenUtils.java .

**Comment by Bunny-Proxima** [comment]
We already have the code written for this in a later devjar, will likely be released in the next update.

**Comment by ghost** [comment]
Is that code public?

**Comment by HmmmHmmmm** [comment]
uh yes u made it :)

**Comment by Bunny-Proxima** [comment]
Not at the moment.

**Comment by AlexNijjar** [comment]
Thanks for bringing this up. I did not realize the method was that costly. I did some profiling yesterday and managed to improve the performance significantly.

<img width="1092" alt="Screen_Shot_2022-08-24_at_3 13 58_AM" src="https://user-images.githubusercontent.com/61668546/186453878-cb7e263b-065b-44de-a7c5-23953e5456b6.png">
<img width="736" alt="Screen_Shot_2022-08-24_at_3 14 42_AM" src="https://user-images.githubusercontent.com/61668546/186453866-31bee182-748d-465b-9266-f856af9c3ada.png">

https://spark.lucko.me/DB74vaBa0b
https://spark.lucko.me/iiJMHHntRF
