### ISSUE TITLE
[Bug]: Can't fly

### ISSUE THREAD

**Issue by Crida117** [terrarium-earth/Ad-Astra#91]
### Bug Description

there is a bug that don't make me fly in every gamemode beside creative (neither spectator) and i don't know how to resolve it

### How to Reproduce?

1. Go in Spectator 
2. Try to fly
3. You will fall

### Expected Behavior

Falling trough the world or flight items don't work over level -32

### Version

1.11.9

### Mod Loader Version

1.19.2  0.14.11

### Mod Loader

Fabric

**Comment by AlexNijjar** [comment]
how exactly are you causing this and are you sure it's happening because of this mod?
