### ISSUE TITLE
[Bug]: 1.19.2 teleporting back to any planet makes me fly into the sky

### ISSUE THREAD

**Issue by Gayanfalor** [terrarium-earth/Ad-Astra#92]
### Bug Description

Hi, yesterday was fine , but here as long as i go into a planet with the waystone i insta get flying into the sky i dont know why, it was working fine yesterday and even this morning i think.

I relaunched the game but its the same, i touhgt it was from my rabbit boots that gives jump boost but no.

What can i do ?

### How to Reproduce?

I dont know if you can reproduce.

Teleport to any planet with waystone
-should be flying into the sky

### Expected Behavior

Working as normal without flying into the sky 

### Version

ad_astra-forge-1.19.2-1.11.9

### Mod Loader Version

1.19.2 - 43.1.55

### Mod Loader

Forge

### Logs or additional context

My friend is ok he's not flying into the sky i dunno whats different

**Comment by AlexNijjar** [comment]
does this still happen on the latest version? I've not been able to reproduce it on both forge and fabric on both a local and dedicated server if it is reopen the issue
