### ISSUE TITLE
[Bug]: Crash On Startup 1.19.2

### ISSUE THREAD

**Issue by leostudiosTM** [terrarium-earth/Ad-Astra#96]
### Bug Description

Crash run with other mods 

### Version

1.11.9

### Mod Loader Version

1.19.2-43.1.52

### Mod Loader

Forge

### Logs or additional context

https://pastebin.com/RwMss3Zx

**Comment by AlexNijjar** [comment]
Are you sure this is 1.11.9? It's a Cloth config error, which isn't even used in the mod
