### ISSUE TITLE
[Feature Request]: Globes Page In Book

### ISSUE THREAD

**Issue by PikachuGabe** [terrarium-earth/Ad-Astra#99]
### Is your feature request related to a problem?

I'm unable to find any documentation of the globes at all.

### Solution(s)

Adding the globes to the book and what structures they spawn in.

### Describe alternatives you've considered

Haven't really considered anything else because this was the easiest thing I could come up with,but making a mod wiki would work.

### Mod Version

1.11.9

### Mod Loader Version

1.19.2 - 43.1.55

### Mod Loader

Forge

**Comment by AlexNijjar** [comment]
The globes concept isn’t fully complete yet. The only obtainable one is the moon globe. When they’re all obtainable an entry will be added

**Comment by PikachuGabe** [comment]
Ah,i did not realize it was incomplete as the advancement requests all of them instead of all the obtainable ones.

**Comment by AlexNijjar** [comment]
yeah it's not achievable at the moment 😅
